 ./generate_installer_with_sudo brew
 ./generate_installer_with_sudo rbenv
 ./generate_installer_with_sudo pyenv
 ./generate_installer_with_sudo nvm
 ./generate_installer_with_sudo 1password
 ./generate_installer_with_sudo zoom
 ./generate_installer_with_sudo keybase
 ./generate_installer_with_sudo drogon
 ./generate_installer_with_sudo taskwarrior
 ./generate_installer_with_sudo nano
 ./generate_installer_with_sudo kiex
 ./generate_installer_with_sudo evm
 ./generate_installer_with_sudo emacs
 ./generate_installer_with_sudo go
 ./generate_installer_with_sudo masterpdf
 ./generate_installer_with_sudo rubymine
 ./generate_installer_with_sudo webstorm
 ./generate_installer_with_sudo guake
 ./generate_installer_with_sudo yakuake
 ./generate_installer_with_sudo beyondcompare
 ./generate_installer_with_sudo thunderbird
 ./generate_installer_with_sudo virtualbox
 ./generate_installer_with_sudo sublime_dev.sh

 ./generate_installer_with_sudo i3
 ./generate_installer_simple fedora37_preferences
 ./generate_installer_simple fedora38_preferences
