#!/bin/bash
#
# @author Zeus Intuivo <zeus@intuivo.com>
#
#
load_struct_testing_wget(){
    local provider="$HOME/_/clis/execute_command_intuivo_cli/struct_testing"
    [   -e "${provider}"  ] && source "${provider}" && echo "Loaded locally"
    [ ! -e "${provider}"  ] && eval """$(wget --quiet --no-check-certificate  https://raw.githubusercontent.com/zeusintuivo/execute_command_intuivo_cli/master/struct_testing -O -  2>/dev/null )"""   # suppress only wget download messages, but keep wget output for variable
    ( ( ! command -v passed >/dev/null 2>&1; ) && echo -e "\n \n  ERROR! Loading struct_testing \n \n " && exit 69; )
} # end load_struct_testing_wget
load_struct_testing_wget

function _linux_prepare(){
  export  THISSCRIPTNAME
  typeset -gr THISSCRIPTNAME="$(pwd)/$(basename "$0")"
  export _err
  typeset -i _err=0
  load_execute_boot_basic_with_sudo(){
      if ( typeset -p "SUDO_USER"  &>/dev/null ) ; then
        export USER_HOME
        typeset -rg USER_HOME=$(getent passwd $SUDO_USER | cut -d: -f6)
      else
        local USER_HOME=$HOME
      fi
      local -r provider="$USER_HOME/_/clis/execute_command_intuivo_cli/execute_boot_basic.sh"
      echo source "${provider}"
      [   -e "${provider}"  ] && source "${provider}"
      [ ! -e "${provider}"  ] && eval """$(wget --quiet --no-check-certificate  https://raw.githubusercontent.com/zeusintuivo/execute_command_intuivo_cli/master/execute_boot_basic.sh -O -  2>/dev/null )"""   # suppress only wget download messages, but keep wget output for variable
      if ( command -v failed >/dev/null 2>&1; ) ; then
      {
        return 0
      }
      else
      {
        echo -e "\n \n  ERROR! Loading execute_boot_basic.sh \n \n "
        exit 1;
      }
      fi
      return 0
  } # end load_execute_boot_basic_with_sudo

  load_execute_boot_basic_with_sudo
  _err=$?
  if [ $_err -ne 0 ] ;  then
  {
    >&2 echo -e "ERROR There was an error loading load_execute_boot_basic_with_sudo Err:$_err "
    exit $_err
  }
  fi

  function _trap_on_exit(){
    echo -e "\033[01;7m*** TRAP $THISSCRIPTNAME EXITS ...\033[0m"
  
  }
  #trap kill ERR
  trap _trap_on_exit EXIT
  #trap kill INT
} # end _linux_prepare

_version() {
  # Usage:
  local PLATFORM="${1}"
  local PATTERN="${2}"
  # https://nano-project.org/download.php?platform=linux64
  # https://nano-project.org/download.php?platform=linux32
  # https://nano-project.org/download.php?platform=win64
  # https://nano-project.org/download.php?platform=win32
  # https://nano-project.org/download.php?platform=osx Requires OS X 10.13.2 or newer
  local url="https://nano-project.org/download.php"
  local CODEFILE=$(curl -d "zz=dl4&platform=${PLATFORM}" -H "Content-Type: application/x-www-form-urlencoded" -X POST  -sSLo - "${url}"  2>&1;) # suppress only wget download messages, but keep wget output for variable
  # https://dl2.cdn.nano-project.org/client/nano_3.50.0_macosx-x86.app.tar.bz2?h=rjBi_Z2lil6O76EGwA9Xqw&x=1598793414
  # https://dl3.cdn.nano-project.org/client/nano_3.50.0_x86_64-linux-gnu.tar.bz2?h=GHvx3uPV-PuIXkUKf1Oc9Q&x=1598795875
  # https://dl2.cdn.nano-project.org/client/nano_3.50.0_i686-linux-gnu.tar.bz2?h=e5YY0z4yBZyp7b8hp-COQQ&x=1598795941
  # https://download.nano-project.org/client/nano_3.50.0_win64_sponsored-setup.exe
  # https://download.nano-project.org/client/nano_3.50.0_win32_sponsored-setup.exe

  local LASTESTBUILD=$(echo $CODEFILE | sed s/\</\\n\</g | grep "${PATTERN}" | sed s/\"/\\n/g | grep "/" | cüt "/")
  # fedora 32 local LASTESTBUILD=$(echo $CODEFILE | sed s/\</\\n\</g | grep "nano*.*.*.*.i386.rpm" | sed s/\"/\\n/g | grep "/" | cüt "/")
  wait
  [[ -z "${LASTESTBUILD}" ]] && failed "nano Version not found! :${LASTESTBUILD}:"


  # assert not empty "${USER_HOME}"
  # assert not empty "${LASTESTBUILD}"

  local CODENAME="${LASTESTBUILD}"
  echo "${LASTESTBUILD}"
  unset PATTERN
  unset PLATFORM
  unset CODEFILE
  unset LASTESTBUILD
} # end _version

_version_test(){
  local CODENAME=$(_version "mac" "nanoOSX*.*.*.*.zip")
}
_version_test
exit 1
_darwin__64() {
  # /usr/bin/curl --disable --globoff --show-error --user-agent Homebrew/2.6.2-222-g880eb2d\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 10.15.7\)\ curl/7.64.1 --header Accept-Language:\ en --retry 3 --location --silent --head --request GET https://homebrew.bintray.com/bottles/nano-5.4.catalina.bottle.tar.gz
  # tar xof /Users/benutzer/Library/Caches/Homebrew/downloads/91845ed41d14ccff1a66f16db7c7ec93f7d7958bb08be637dae24d2aa70a214d--nano-5.4.catalina.bottle.tar.gz -C /var/folders/8x/9phrghz97g38v9m8m6r59_0w0000gn/T/d20201221-96141-1fi6gd9
  # cp -pR /var/folders/8x/9phrghz97g38v9m8m6r59_0w0000gn/T/d20201221-96141-1fi6gd9/nano/. /usr/local/Cellar/nano
  # chmod -Rf +w /var/folders/8x/9phrghz97g38v9m8m6r59_0w0000gn/T/d20201221-96141-1fi6gd9
  brew install nano
  nano --version

  # REF: https://github.com/scopatz/nanorc
  # curl https://raw.githubusercontent.com/scopatz/nanorc/master/install.sh | sh
  wget https://raw.githubusercontent.com/scopatz/nanorc/master/install.sh -O- | sh
  ls ~/.nanorc
  cd ~/.nano/
  cp ~/.nano/javascript.nanorc ~/.nano/typescript.nanorc
  ersetzeindatei ~/.nano/typescript.nanorc "JavaScript" "Typescript"
  ersetzeindatei ~/.nano/typescript.nanorc "\.js$"  "\.ts$"   
  sed -i'' 's/\.js$/\.ts$/g' ~/.nano/typescript.nanorc
  # from 
  # syntax "JavaScript" "\.js$"  
  # syntax "Typescript" "\.ts$"   
  # in   ~/.nano/typescript.nanorc
ersetzeindatei ~/.nanorc 'include "~/.nano/tex.nanorc"' 'include "~/.nano/tex.nanorc"
include "~/.nano/typescript.nanorc"'

}
_darwin__64_manual() {

  git clone -b https://git.savannah.gnu.org/git/nano.git
  cd nano
  git pull 
  git config pull.rebase false
  # PKG_CONFIG Path to the executable
  # PKG_CONFIG_PATH path to where the .pc files are located 
  # PKG_CONFIG_LIBDIR overrides PKG_CONFIG_PATH 
  PKG_CONFIG="/usr/local/bin/pkg-config" \
PKG_CONFIG_PATH="/usr/local/lib/pkgconfig" \
PKG_CONFIG_LIBDIR="/usr/local/lib/pkgconfig" \
  ./autogen.sh
  cat -n INSTALL | grep configure
   brew install automake 
   brew install libtool
   brew install pkg-config
  ./configure

PKG_CONFIG="/usr/local/bin/pkg-config" \
PKG_CONFIG_PATH="/usr/local/lib/pkgconfig" \
PKG_CONFIG_LIBDIR="/usr/local/lib/pkgconfig" \
  ./configure --enable-debug \
              --disable-dependency-tracking \
              --prefix=/usr/local/opt \
                          --sysconfdir=/usr/local/etc \
                          --enable-color \
                          --enable-extra \
                          --enable-multibuffer \
                          --enable-nanorc \
                          --enable-utf8
  make -j3 -B --debug
  make check -j3 -B --debug
  make install  -j3 -B --debug

} # end _darwin__64

_ubuntu__64() {
  _linux_prepare
    local CODENAME=$(_version "linux" "nano-*.*.*.*amd64.deb")
    # THOUGHT          local CODENAME="nano-4.3.3.24545_amd64.deb"
    local URL="https://www.nano-editor.org/dist/v5/${CODENAME}"
https://www.nano-editor.org/dist/v5/
    cd $USER_HOME/Downloads/
    _download "${URL}"
    sudo dpkg -i ${CODENAME}
# install lastest nano 
sudo add-apt-repository ppa:n-muench/programs-ppa
sudo apt install nano
sudo apt update nano

# task_compile_lastest_nano 
# _get_version()
# _download
cd $USER_HOME
cd $HOME 

curl -O https://www.nano-editor.org/dist/v5/nano-5.2.tar.gz
tar -xvf nano-5.2.tar.gz
cd nano-5.2

cat -n INSTALL | grep configure
sudo apt install libncursesw5-dev -y
sudo apt install groff -y
./install-sh
./autogen.sh
./configure
make -j3 -B --debug
make -j3
sudo make install | grep 

# Make sure we are using nano we compiled and not the boring system nano
nano --version  should match 5.2 
which nano
/usr/local/share/nano --version
sudo /usr/local/share/nano --version
sudo /usr/local/bin/nano --version
sudo mv /bin/nano /bin/nano_old
nano --version

# REF: https://github.com/scopatz/nanorc
curl https://raw.githubusercontent.com/scopatz/nanorc/master/install.sh | sh
wget https://raw.githubusercontent.com/scopatz/nanorc/master/install.sh -O- | sh

# 
.nanorc
~/.nano/
cp ~/.nano/javascript.nanorc ~/.nano/typescript.nanorc
ersetseindatei 
syntax "JavaScript" "\.js$"  
> 
syntax "Typescript" "\.ts$"   
in   ~/.nano/typescript.nanorc

ersetseindatei 
include "~/.nano/tex.nanorc"                                          
>
include "~/.nano/tex.nanorc"
include "~/.nano/typescript.nanorc"
in .nanorc

PORT=3000
curl -X POST http://$HOST:$PORT -H "accept: application/json" -H "Content-Type: application/json" -d "{}"
curl -X POST http://$HOST:$PORT -H "accept: application/json" -H "Content-Type: application/json" -d "{"":"" }"
} # end _ubuntu__64

_ubuntu__32() {
  _linux_prepare
    local CODENAME=$(_version "linux" "nano-*.*.*.*i386.deb")
    # THOUGHT local CODENAME="nano-4.3.3.24545_i386.deb"
    local URL="https://www.nano-editor.org/dist/v5/${CODENAME}"
    cd $USER_HOME/Downloads/
    _download "${URL}"
    sudo dpkg -i ${CODENAME}
} # end _ubuntu__32

_fedora__32() {
  _linux_prepare
  local CODENAME=$(_version "linux" "nano*.*.*.*.i386.rpm")
  # THOUGHT                          nano-4.3.3.24545.i386.rpm
  local TARGET_URL="https://www.nano-editor.org/dist/v5/${CODENAME}"
  file_exists_with_spaces $USER_HOME/Downloads
  cd $USER_HOME/Downloads
  _download "${TARGET_URL}"
  file_exists_with_spaces "$USER_HOME/Downloads/${CODENAME}"
  ensure tar or "Canceling Install. Could not find tar command to execute unzip"

  # provide error handling , once learned goes here. LEarn under if, once learned here.
  # Start loop while ERROR flag in case needs to try again, based on error
  _try "rpm --import https://www.nano-editor.org/dist/v5/RPM-GPG-KEY-nano"
  local msg=$(_try "rpm -ivh \"$USER_HOME/Downloads/${CODENAME}\"" )
  local ret=$?
  if [ $ret -gt 0 ] ; then
  {
    failed "${ret}:${msg}"
    # add error handling knowledge while learning.
  }
  else
  {
    passed Install with RPM success!
  }
  fi
  ensure nano or "Failed to install Beyond Compare"
  rm -f "$USER_HOME/Downloads/${CODENAME}"
  file_does_not_exist_with_spaces "$USER_HOME/Downloads/${CODENAME}"
} # end _fedora__32


_fedora__64() {
  _linux_prepare
  # Lives Samples
  # https://www.nano-editor.org/dist/v5/nano-2019.3.4.tar.gz
  local CODENAME=$(_version "linux" "nano*.*.*.tar.gz")

  CODENAME=$(echo "nano-2020.2")
  local TARGET_URL="https://www.nano-editor.org/dist/v5/${CODENAME}.tar.gz"
  if  it_exists_with_spaces "$USER_HOME/Downloads/${CODENAME}.tar.gz" ; then
  {
    file_exists_with_spaces "$USER_HOME/Downloads/${CODENAME}.tar.gz"
  }
  else
  {
    file_exists_with_spaces $USER_HOME/Downloads
    cd $USER_HOME/Downloads
    _download "${TARGET_URL}" $USER_HOME/Downloads  ${CODENAME}.tar.gz
    file_exists_with_spaces "$USER_HOME/Downloads/${CODENAME}.tar.gz"
  }
  fi
  if  it_exists_with_spaces "$USER_HOME/Downloads/${CODENAME}" ; then
  {
    rm -rf "$USER_HOME/Downloads/${CODENAME}"
    directory_does_not_exist_with_spaces "$USER_HOME/Downloads/${CODENAME}"
  }
  fi

  ensure tar or "Canceling Install. Could not find tar command to execute unzip"
  ensure awk or "Canceling Install. Could not find awk command to execute unzip"
  ensure pv or "Canceling Install. Could not find pv command to execute unzip"
  ensure du or "Canceling Install. Could not find du command to execute unzip"
  ensure gzip or "Canceling Install. Could not find gzip command to execute unzip"
  ensure gio or "Canceling Install. Could not find gio command to execute gio"
  ensure update-mime-database or "Canceling Install. Could not find update-mime-database command to execute update-mime-database"
  ensure update-desktop-database or "Canceling Install. Could not find update-desktop-database command to execute update"
  ensure touch or "Canceling Install. Could not find touch command to execute touch"

  # provide error handling , once learned goes here. LEarn under if, once learned here.
  # Start loop while ERROR flag in case needs to try again, based on error
  cd $USER_HOME/Downloads
  #_try "tar xvzf  \"$USER_HOME/Downloads/${CODENAME}.tar.gz\"--directory=$USER_HOME/Downloads"
  # GROw bar with tar Progress bar tar REF: https://superuser.com/questions/168749/is-there-a-way-to-see-any-tar-progress-per-file
  # Compress tar cvfj big-files.tar.bz2 folder-with-big-files
  # Compress tar cf - $USER_HOME/Downloads/${CODENAME}.tar.gz --directory=$USER_HOME/Downloads -P | pv -s $(du -sb $USER_HOME/Downloads/${CODENAME}.tar.gz | awk '{print $1}') | gzip > big-files.tar.gz
  # Extract tar Progress bar REF: https://coderwall.com/p/l_m2yg/tar-untar-on-osx-linux-with-progress-bars
  # Extract tar sample pv file.tgz | tar xzf - -C target_directory
  # Working simplme tar:  tar xvzf $USER_HOME/Downloads/${CODENAME}.tar.gz --directory=$USER_HOME/Downloads
  pv $USER_HOME/Downloads/${CODENAME}.tar.gz  | tar xzf - -C $USER_HOME/Downloads
  #local msg=$(_try "tar xvzf  \"$USER_HOME/Downloads/${CODENAME}.tar.gz\" --directory=$USER_HOME/Downloads " )
  #  tar xvzf file.tar.gz
  # Where,
  # x: This option tells tar to extract the files.
  # v: The “v” stands for “verbose.” This option will list all of the files one by one in the archive.
  # z: The z option is very important and tells the tar command to uncompress the file (gzip).
  # f: This options tells tar that you are going to give it a file name to work with.
  local msg
  local folder_date
  local ret=$?
  if [ $ret -gt 0 ] ; then
  {
    failed "${ret}:${msg}"
    # add error handling knowledge while learning.
  }
  else
  {
    passed Install with Untar Unzip success!
  }
  fi

  local NEWDIRCODENAME=$(ls -1tr /home/zeus/Downloads/  | tail  -1)
  local FROMUZIPPED="$USER_HOME/Downloads/${NEWDIRCODENAME}"
  directory_exists_with_spaces  "${FROMUZIPPED}"


  if  it_exists_with_spaces "$USER_HOME/_/software/nano" ; then
  {
     folder_date=$(date +"%Y%m%d")
     if  it_exists_with_spaces "$USER_HOME/_/software/nano_${folder_date}" ; then
     {
       warning A backup already exists for today "${ret}:${msg} \n ... adding time"
       folder_date=$(date +"%Y%m%d%H%M")
     }
     fi
     msg=$(mv "$USER_HOME/_/software/nano" "$USER_HOME/_/software/nano_${folder_date}")
     ret=$?
     if [ $ret -gt 0 ] ; then
     {
       warning failed to move backup "${ret}:${msg} \n"
     }
     fi
     directory_exists_with_spaces "$USER_HOME/_/software/nano_${folder_date}"
     file_does_not_exist_with_spaces "$USER_HOME/_/software/nano"
  }
  fi
  mkdir -p "$USER_HOME/_/software"
  directory_exists_with_spaces "$USER_HOME/_/software"
  mv "${FROMUZIPPED}" "$USER_HOME/_/software/nano"
  directory_does_not_exist_with_spaces "${FROMUZIPPED}"
  directory_exists_with_spaces "$USER_HOME/_/software/nano"
  directory_exists_with_spaces "$USER_HOME/_/software/nano/bin"
  mkdir -p "$USER_HOME/.local/share/applications"
  directory_exists_with_spaces "$USER_HOME/.local/share/applications"
  mkdir -p "$USER_HOME/.local/share/mime/packages"
  directory_exists_with_spaces "$USER_HOME/.local/share/mime/packages"
  file_exists_with_spaces "$USER_HOME/_/software/nano/bin/nano.sh"

  chown $SUDO_USER:$SUDO_USER -R "$USER_HOME/_/software/nano"

  # Now Proceed to register REF:  https://gist.github.com/c80609a/752e566093b1489bd3aef0e56ee0426c
  ensure cat or "Failed to use cat command does not exists"
  ensure xdg-mime or "Failed to install run xdg-mime"

   cat << EOF > $USER_HOME/_/software/nano/bin/nano-open.rb
#!/usr/bin/env ruby

# $USER_HOME/_/software/nano/bin/nano-open.rb
# script opens URL in format nano://open?file=%{file}:%{line} in nano

require 'uri'

begin
    url = ARGV.first
    u = URI.parse(url)
    # puts u
    q = URI.decode_www_form(u.query)
    # puts q
    h = q.to_h
    # puts h
    file = h['file']
    line = h['line']
    # puts file
    # puts line
    if line
        arg = "#{file}:#{line}"
    else
        arg = "#{file}"
    end
rescue
    arg = ""
end
puts arg
EOF
  file_exists_with_spaces "$USER_HOME/_/software/nano/bin/nano-open.rb"
  chown $SUDO_USER:$SUDO_USER -R "$USER_HOME/_/software/nano/bin/nano-open.rb"
  chmod +x $USER_HOME/_/software/nano/bin/nano-open.rb


    cat << EOF > $USER_HOME/_/software/nano/bin/nano-open.sh
#!/usr/bin/env bash
#encoding: UTF-8
# $USER_HOME/_/software/nano/bin/nano-open.sh
# script opens URL in format nano://open?file=%{file}:%{line} in nano

echo "\${@}"
echo "\${@}" >>  $USER_HOME/_/work/requested.log
$USER_HOME/_/software/nano/bin/nano-open.rb \${@}
filetoopen=\$($USER_HOME/_/software/nano/bin/nano-open.rb "\${@}")
echo filetoopen "\${filetoopen}"
echo "\${filetoopen}" >>  $USER_HOME/_/work/requestedfiletoopen.log
nano "\${filetoopen}"

EOF
  mkdir -p $USER_HOME/_/work/
  directory_exists_with_spaces $USER_HOME/_/work/
  chown $SUDO_USER:$SUDO_USER $USER_HOME/_/work/
  touch $USER_HOME/_/work/requestedfiletoopen.log
  file_exists_with_spaces $USER_HOME/_/work/requestedfiletoopen.log
  chown $SUDO_USER:$SUDO_USER -R $USER_HOME/_/work/requestedfiletoopen.log
  file_exists_with_spaces "$USER_HOME/_/software/nano/bin/nano-open.sh"
  chown $SUDO_USER:$SUDO_USER -R "$USER_HOME/_/software/nano/bin/nano-open.sh"
  chmod +x $USER_HOME/_/software/nano/bin/nano-open.sh

 cat << EOF > $USER_HOME/.local/share/mime/packages/application-x-nano.xml
<?xml version="1.0" encoding="UTF-8"?>
<mime-info xmlns="http://www.freedesktop.org/standards/shared-mime-info">
  <mime-type type="application/x-nano">
    <comment>new mime type</comment>
    <glob pattern="*.x-nano;*.rb;*.html;*.html.erb;*.js.erb;*.html.haml;*.js.haml;*.erb;*.haml;*.js"/>
  </mime-type>
</mime-info>
EOF
  file_exists_with_spaces "$USER_HOME/.local/share/mime/packages/application-x-nano.xml"
  chown $SUDO_USER:$SUDO_USER -R "$USER_HOME/.local/share/mime/packages/application-x-nano.xml"




  cat << EOF > $USER_HOME/.local/share/applications/gnu-nano.desktop
# $USER_HOME/.local/share/applications/gnu-nano.desktop
[Desktop Entry]
Encoding=UTF-8
Version=2020.2
Type=Application
Name=nano
Icon=$USER_HOME/_/software/nano/bin/nano.svg
Exec="$USER_HOME/_/software/nano/bin/nano.sh" %f
MimeType=application/x-nano;text/x-nano;text/plain;text/x-chdr;text/x-csrc;text/x-c++hdr;text/x-c++src;text/x-java;text/x-dsrc;text/x-pascal;text/x-perl;text/x-python;application/x-php;application/x-httpd-php3;application/x-httpd-php4;application/x-httpd-php5;application/xml;text/html;text/css;text/x-sql;text/x-diff;x-directory/normal;inode/directory;
Comment=The Most Intelligent Php IDE
Categories=Development;IDE;
Terminal=true
StartupWMClass=gnu-nano
EOF
  file_exists_with_spaces "$USER_HOME/.local/share/applications/gnu-nano.desktop"
  chown $SUDO_USER:$SUDO_USER -R "$USER_HOME/.local/share/applications/gnu-nano.desktop"


  cat << EOF > $USER_HOME/.local/share/applications/nano.mimeinfo.cache
# $USER_HOME/.local/share/applications/mimeinfo.cache

[MIME Cache]
x-scheme-handler/nano=nano-open.desktop;
EOF
  file_exists_with_spaces "$USER_HOME/.local/share/applications/nano.mimeinfo.cache"
  chown $SUDO_USER:$SUDO_USER -R "$USER_HOME/.local/share/applications/nano.mimeinfo.cache"

  cat << EOF > $USER_HOME/.local/share/applications/nano-open.desktop
# $USER_HOME/.local/share/applications/nano-open.desktop
[Desktop Entry]
Encoding=UTF-8
Version=1.0
Type=Application
Terminal=true
Exec="$USER_HOME/_/software/nano/bin/nano-open.sh" %f
MimeType=application/nano;x-scheme-handler/nano;
Name=MineOpen
Comment=BetterErrors
EOF
  file_exists_with_spaces "$USER_HOME/.local/share/applications/nano-open.desktop"
  chown $SUDO_USER:$SUDO_USER -R "$USER_HOME/.local/share/applications/nano-open.desktop"

  # xdg-mime default gnu-nano.desktop text/plain;text/x-chdr;text/x-csrc;text/x-c++hdr;text/x-c++src;text/x-java;text/x-dsrc;text/x-pascal;text/x-perl;text/x-python;application/x-php;application/x-httpd-php3;application/x-httpd-php4;application/x-httpd-php5;application/xml;text/html;text/css;text/x-sql;text/x-diff;x-directory/normal;inode/directory;
  # xdg-mime default nano-open.desktop x-scheme-handler/nano
  # msg=$(_try "xdg-mime default nano-open.desktop x-scheme-handler/nano" )
  su - "${SUDO_USER}" -c "xdg-mime default nano-open.desktop x-scheme-handler/nano"
  su - "${SUDO_USER}" -c "xdg-mime default nano-open.desktop text/nano"
  su - "${SUDO_USER}" -c "xdg-mime default nano-open.desktop application/nano"
  su - "${SUDO_USER}" -c "xdg-mime default gnu-nano.desktop x-scheme-handler/x-nano"
  su - "${SUDO_USER}" -c "xdg-mime default gnu-nano.desktop text/x-nano"
  su - "${SUDO_USER}" -c "xdg-mime default gnu-nano.desktop application/x-nano"

#   cat << EOF > $USER_HOME/.config/mimeapps.list
#   cat << EOF > $USER_HOME/.local/share/applications/mimeapps.list
# [Default Applications]
# x-scheme-handler/nano=nano-open.desktop
# text/nano=nano-open.desktop
# application/nano=nano-open.desktop
# x-scheme-handler/x-nano=gnu-nano.desktop
# text/x-nano=gnu-nano.desktop
# application/x-nano=gnu-nano.desktop

# [Added Associations]
# x-scheme-handler/nano=nano-open.desktop;
# text/nano=nano-open.desktop;
# application/nano=nano-open.desktop;
# x-scheme-handler/x-nano=gnu-nano.desktop;
# text/x-nano=gnu-nano.desktop;
# application/x-nano=gnu-nano.desktop;
# EOF
#   file_exists_with_spaces "$USER_HOME/.local/share/applications/mimeapps.list"
#   file_exists_with_spaces "$USER_HOME/.config/mimeapps.list"
ln -fs "$USER_HOME/.config/mimeapps.list" "$USER_HOME/.local/share/applications/mimeapps.list"
softlink_exists_with_spaces "$USER_HOME/.local/share/applications/mimeapps.list>$USER_HOME/.config/mimeapps.list"
chown $SUDO_USER:$SUDO_USER -R  "$USER_HOME/.local/share/applications/mimeapps.list"

file_exists_with_spaces "$USER_HOME/_/software/nano/bin/nano-open.sh"

  su - "${SUDO_USER}" -c "xdg-mime query default x-scheme-handler/nano"
  su - "${SUDO_USER}" -c "xdg-mime query default x-scheme-handler/x-nano"
  su - "${SUDO_USER}" -c "xdg-mime query default text/x-nano"
  su - "${SUDO_USER}" -c "xdg-mime query default application/x-nano"
  su - "${SUDO_USER}" -c "xdg-mime query default text/nano"
  su - "${SUDO_USER}" -c "xdg-mime query default application/nano"
  msg=$(_try "su - \"${SUDO_USER}\" -c \"xdg-mime query default x-scheme-handler/nano\"")
  ret=$?
  if [ $ret -gt 0 ] ; then
  {

    failed "${ret}:${msg} Install with xdg-mime scheme failed!"
  }
  else
  {
    passed Install with xdg-mime scheme success!
  }
  fi
  su - "${SUDO_USER}" -c "update-mime-database \"$USER_HOME/.local/share/mime\""
  su - "${SUDO_USER}" -c "update-desktop-database \"$USER_HOME/.local/share/applications\""
  su - "${SUDO_USER}" -c "touch test12345.rb "
  su - "${SUDO_USER}" -c "gio info test12345.rb  | grep \"standard::content-type\""
  su - "${SUDO_USER}" -c "touch test12345.erb "
  su - "${SUDO_USER}" -c "gio info test12345.erb  | grep \"standard::content-type\""
  su - "${SUDO_USER}" -c "touch test12345.js.erb "
  su - "${SUDO_USER}" -c "gio info test12345.js.erb  | grep \"standard::content-type\""
  su - "${SUDO_USER}" -c "touch test12345.html.erb "
  su - "${SUDO_USER}" -c "gio info test12345.html.erb  | grep \"standard::content-type\""
  su - "${SUDO_USER}" -c "touch test12345.haml "
  su - "${SUDO_USER}" -c "gio info test12345.haml  | grep \"standard::content-type\""
  su - "${SUDO_USER}" -c "touch test12345.html.haml "
  su - "${SUDO_USER}" -c "gio info test12345.html.haml  | grep \"standard::content-type\""
  su - "${SUDO_USER}" -c "touch test12345.js.haml "
  su - "${SUDO_USER}" -c "gio info test12345.js.haml  | grep \"standard::content-type\""

  su - "${SUDO_USER}" -c "gio mime x-scheme-handler/nano"
  su - "${SUDO_USER}" -c "gio mime x-scheme-handler/x-nano"
  su - "${SUDO_USER}" -c "gio mime text/x-nano"
  su - "${SUDO_USER}" -c "gio mime application/x-nano"
  su - "${SUDO_USER}" -c "gio mime text/nano"
  su - "${SUDO_USER}" -c "gio mime application/nano"
  su - "${SUDO_USER}" -c "rm test12345.rb"
  su - "${SUDO_USER}" -c "rm test12345.erb"
  su - "${SUDO_USER}" -c "rm test12345.js.erb"
  su - "${SUDO_USER}" -c "rm test12345.html.erb"
  su - "${SUDO_USER}" -c "rm test12345.haml"
  su - "${SUDO_USER}" -c "rm test12345.js.haml"
  su - "${SUDO_USER}" -c "rm test12345.html.haml"
  echo " "
  echo "HINT: Add this to your config/initializers/better_errors.php file "
  echo "better_errors.rb
  # ... /path_to_php_project/ ... /config/initializers/better_errors.php

  if (defined?(\$BetterErrors) {
    \$BetterErrors.editor = \"nano://open?file=%{file}:%{line}\"
    \$BetterErrors.editor = \"x-nano://open?file=%{file}:%{line}\"
  }
  "
} # end _fedora__64

_mingw__64() {
    local CODENAME=$(_version "win" "nano*.*.*.*.exe")
    # THOUGHT        local CODENAME="nano-4.3.3.24545.exe"
    local URL="https://www.nano-editor.org/dist/v5/${CODENAME}"
    cd $HOMEDIR
	  cd Downloads
    curl -O $URL
    ${CODENAME}
} # end _mingw__64

_mingw__32() {
    local CODENAME=$(_version "win" "nano*.*.*.*.exe")
    # THOUGHT        local CODENAME="nano-4.3.3.24545.exe"
    local URL="https://www.nano-editor.org/dist/v5/${CODENAME}"
    cd $HOMEDIR
    cd Downloads
	  curl -O $URL
	  ${CODENAME}
} # end


_main() {
  determine_os_and_fire_action
} # end _main

_main

echo ":)"


