#!/usr/bin/env bash
#!/bin/bash
#
# @author Zeus Intuivo <zeus@intuivo.com>
#
#


function loader_installer(){
	local _sudoer="$(<0tasks_base/sudoer.bash)"
  local _sudoer_lines="$(cat 0tasks_base/linuxes.bash | wc -l)"
  local _linuxes_body_templates="$(<0tasks_base/linuxes.bash)"

  local _main="$(<0tasks_base/main.bash)"
  echo "${_sudoer}" > "install_${1}.bash"
  echo -e "\n\n\n #--------\/\/\/\/-- Work here below \/, test, and transfer to 1tasks_templates/${1} having a working version -\/\/\/\/-------\n\n" >> "install_${1}.bash"
  echo "${_linuxes_body_templates}" >>  "2tasks_templates_sudo/${1}"
  echo -e "\n\n\n #--------/\/\/\/\-- Work here above /\, test, and transfer to 1tasks_templates/${1} having a working version -/\/\/\/\-------\n\n" >> "install_${1}.bash"
  touch "2tasks_templates_sudo/${1}"
  echo "${_main}" >> "install_${1}.bash"
	chmod a+x "install_${1}.bash"
  subl "2tasks_templates_sudo/${1}:${_sudoer_lines}"
} # end loader_installer
[[ -z "${1}" ]] && echo -e "ERROR $0 requires one argument. \n A task name   like    \n $0 brew    to create  install_brew.bash and 2tasks_templates_sudo/brew " && exit 1
[[ -f "./2tasks_templates_sudo/${1}" ]] && echo -e "ERROR ./2tasks_templates_sudo/$1 already exists  " && exit 1
loader_installer "${1}"

