#!/usr/bin/env bash

#set -u

function ._main() {
  local -i _err=0
  local _files=""
	_files="$(ls -1 ./2tasks_templates_sudo)"
  _err=$?
	if [ ${_err:-0} -ne 0 ] || [[ -z "${_files:-}" ]] ; then 
	{
	  echo "Error When loading templares not found ./2tasks_templates_sudo "
    exit 1 
	}
	fi
	local _one
	while read -r _one ; do
	{
    [[ "${_one}" ]] && continue
		./generate_installer_with_sudo "${_one}"
	}
  done <<< "${_files}" 

} # end ._main

._main
