#!/usr/bin/env bash
#
#
LIGHTGREEN="\033[38;5;83m"
LIGHTPINK="\033[1;204m"
LIGHTYELLOW="\033[38;5;227m"
RESET="\033[0m"
CERO="\033[01;0m"

echo "${*}"
# unlink it
# unlink ~/.linuxbrew/bin/yarn
# Fix it back
# cd  ~/.linuxbrew/bin/
# ln -s ../Cellar/yarn/1.22.10/bin/yarn
/home/salba/.linuxbrew/Cellar/yarn/1.22.10/bin/yarn #"${*}"
yorn
if [ -d ./packages/core ] ; then
{
  [ ! -f ./dev.sh ] && cp /home/salba/_/work/pixum/projects/pixum-web/breakage/dev_lerna.sh ./dev.sh
  cd ./packages/core
  nur reporter.info\(\`Zipping | grep reporter.info\(\`Zipping
  [ $? -eq ] && äö  reporter.info\(\`Zipping return\;reporter.info\(\`Zipping
  cd ..
  cd ..
}
else
{
  [ ! -f ./dev.sh ] && cp /home/salba/_/work/pixum/projects/pixum-web/0001-initial-commit-a8cfc75a/dev.sh ./dev.sh

}
fi

[ -f ./dev.sh ] && BUILDONLY=1 REMOVECACHE=1 ./dev.sh


echo -e "${LIGHTGREEN} ✔ yarn ${LIGHTPINK} ${*}  ${RESET}"
