#!/bin/bash
echo based on REF: https://support.1password.com/install-linux/
_debian_flavor_install() {
echo "
Debian or Ubuntu (or derivatives)

    Add the key for the 1Password apt repository again:
"
    curl -sS https://downloads.1password.com/linux/keys/1password.asc | sudo gpg --dearmor --output /usr/share/keyrings/1password-archive-keyring.gpg
echo "
    Update the key for the debsig-verify policy:
"
    curl -sS https://downloads.1password.com/linux/keys/1password.asc | sudo gpg --dearmor --output /usr/share/debsig/keyrings/AC2D62742012EA22/debsig.gpg

	echo "

  1. Add the key for the 1Password apt repository:
  "
  curl -sS https://downloads.1password.com/linux/keys/1password.asc | sudo gpg --dearmor --output /usr/share/keyrings/1password-archive-keyring.gpg
  echo "
    2. Add the 1Password apt repository:
  "
  echo 'deb [arch=amd64 signed-by=/usr/share/keyrings/1password-archive-keyring.gpg] https://downloads.1password.com/linux/debian/amd64 stable main' | sudo tee /etc/apt/sources.list.d/1password.list
  echo "
    3. Add the debsig-verify policy:
  "
  sudo mkdir -p /etc/debsig/policies/AC2D62742012EA22/
  curl -sS https://downloads.1password.com/linux/debian/debsig/1password.pol | sudo tee /etc/debsig/policies/AC2D62742012EA22/1password.pol
  sudo mkdir -p /usr/share/debsig/keyrings/AC2D62742012EA22
  curl -sS https://downloads.1password.com/linux/keys/1password.asc | sudo gpg --dearmor --output /usr/share/debsig/keyrings/AC2D62742012EA22/debsig.gpg
  echo "
    4. Install 1Password:
  "
  sudo apt update && sudo apt install 1password -y
  sudo apt update && sudo apt upgrade 1password -y

} # end _debian_flavor_install

_redhat_flavor_install() {
  echo "

    1. Add the key for the 1Password yum repository:
  "
  sudo rpm --import https://downloads.1password.com/linux/keys/1password.asc
  echo "
    2. Add the 1Password yum repository:
  "
  sudo sh -c 'echo -e "[1password]\nname=1Password Stable Channel\nbaseurl=https://downloads.1password.com/linux/rpm/stable/\$basearch\nenabled=1\ngpgcheck=1\nrepo_gpgcheck=1\ngpgkey=\"https://downloads.1password.com/linux/keys/1password.asc\"" > /etc/yum.repos.d/1password.repo'
  echo "
    3. Install 1Password:
  "
  sudo dnf install 1password -y
  sudo dnf upgrade 1password --refresh

} # end _redhat_flavor_install

_arch_flavor_install() {
  echo "

    1. Get the 1Password signing key:
  "
  curl -sS https://downloads.1password.com/linux/keys/1password.asc | gpg --import
  echo "
    2. Clone the 1Password package:
  "
  git clone https://aur.archlinux.org/1password.git
  echo "
    3. Install 1Password:
  "
  cd 1password ||  exit 1
  makepkg -si

} # end _readhat_flavor_install

_arch__32() {
  _arch_flavor_install
} # end _arch__32

_arch__64() {
  _arch_flavor_install
} # end _arch__64

_centos__32() {
  _redhat_flavor_install
} # end _centos__32

_centos__64() {
  _redhat_flavor_install
} # end _centos__64

_debian__32() {
  _debian_flavor_install
} # end _debian__32

_debian__64() {
  _debian_flavor_install
} # end _debian__64

_fedora__32() {
  local -i _err=0
	enforce_variable_with_value USER_HOME "${USER_HOME}"
  local TARGET_URL=https://downloads.1password.com/linux/rpm/stable/x86_64/1password-latest.rpm
  Comment TARGET_URL "${TARGET_URL}"
  enforce_variable_with_value TARGET_URL "${TARGET_URL}"
  local CODENAME=""
	CODENAME=$(basename "${TARGET_URL}")
  Comment CODENAME "${CODENAME}"
  enforce_variable_with_value CODENAME "${CODENAME}"
  local DOWNLOADFOLDER=""
	DOWNLOADFOLDER="$(_find_downloads_folder)"
  Comment DOWNLOADFOLDER "${DOWNLOADFOLDER}"
  enforce_variable_with_value DOWNLOADFOLDER "${DOWNLOADFOLDER}"
  _do_not_downloadtwice "${TARGET_URL}" "${DOWNLOADFOLDER}"  "${CODENAME}"
  _install_rpm "${TARGET_URL}" "${DOWNLOADFOLDER}"  "${CODENAME}" 0
  _err=$?
  _remove_downloaded_codename_or_err  $_err "${DOWNLOADFOLDER}/${CODENAME}"
  _err=$?
  return  $_err
} # end _fedora__32

_fedora__64() {
  _redhat_flavor_install
} # end _fedora__64

_fedora_39__64() {
  trap "echo Error:$?" ERR INT
  local _parameters="${*-}"
  local -i _err=0
  _redhat_flavor_install "${_parameters-}"
	_err=$?
  if [ ${_err} -gt 0 ] ; then
  {
    failed "$0:$LINENO while running callsomething above _err:${_err}"
  }
  fi
} # end _fedora_39__64

_fedora_41__64() {
  trap 'echo Error:$?' ERR INT
  local _parameters="${*-}"
  local -i _err=0
echo "
	Fedora, Red Hat Enterprise Linux, SUSE, or openSUSE

    Remove the old signing key:
"
set -x
    yes | rpm -e gpg-pubkey-2012ea22-591e021e
set +x
		echo "

    Add the key for the 1Password RPM repository again:
"
set -x
    yes | rpm --import https://downloads.1password.com/linux/keys/1password.asc
set +x
	Installing install 1Password manually:

  Checking  Add the key for the 1Password yum repository:
  set -x
  yes | rpm --import https://downloads.1password.com/linux/keys/1password.asc
  set +s
  Checking  Add the 1Password yum repository:
  set -x
  yes | sh -c 'echo -e "[1password]\nname=1Password Stable Channel\nbaseurl=https://downloads.1password.com/linux/rpm/stable/\$basearch\nenabled=1\ngpgcheck=1\nrepo_gpgcheck=1\ngpgkey=\"https://downloads.1password.com/linux/keys/1password.asc\"" > /etc/yum.repos.d/1password.repo'
  set +x
  Installing 1Password:

  dnf install 1password -y

  Comment The packages and repository are signed with the GPG key 3FEF9748469ADBE15DA7CA80AC2D62742012EA22.i

  # callsomething "${_parameters-}"
  _err=$?
  if [ ${_err} -gt 0 ] ; then
  {
    failed "$0:$LINENO while running callsomething above _err:${_err}"
  }
  fi
  local -i _err=0
	enforce_variable_with_value USER_HOME "${USER_HOME}"
  local TARGET_URL=https://downloads.1password.com/linux/rpm/stable/x86_64/1password-latest.rpm
  Comment TARGET_URL "${TARGET_URL}"
  enforce_variable_with_value TARGET_URL "${TARGET_URL}"
  local CODENAME=""
	CODENAME=$(basename "${TARGET_URL}")
  Comment CODENAME "${CODENAME}"
  enforce_variable_with_value CODENAME "${CODENAME}"
  local DOWNLOADFOLDER=""
	DOWNLOADFOLDER="$(_find_downloads_folder)"
  Comment DOWNLOADFOLDER "${DOWNLOADFOLDER}"
  enforce_variable_with_value DOWNLOADFOLDER "${DOWNLOADFOLDER}"
  _do_not_downloadtwice "${TARGET_URL}" "${DOWNLOADFOLDER}"  "${CODENAME}"
  _install_rpm "${TARGET_URL}" "${DOWNLOADFOLDER}"  "${CODENAME}" 0
  _err=$?
  _remove_downloaded_codename_or_err  $_err "${DOWNLOADFOLDER}/${CODENAME}"
  _err=$?
  return  $_err

} # end _fedora_41__64

_gentoo__32() {
  _redhat_flavor_install
} # end _gentoo__32

_gentoo__64() {
  _redhat_flavor_install
} # end _gentoo__64

_madriva__32() {
  _redhat_flavor_install
} # end _madriva__32

_madriva__64() {
  _redhat_flavor_install
} # end _madriva__64

_suse__32() {
  _redhat_flavor_install
} # end _suse__32

_suse__64() {
  _redhat_flavor_install
} # end _suse__64

_ubuntu__32() {
  _debian_flavor_install
} # end _ubuntu__32

_ubuntu__64() {
  _debian_flavor_install
} # end _ubuntu__64

_darwin__64() {
  echo "Procedure not yet implemented. I don't know what to do."
} # end _darwin__64

_tar() {
  echo "
    1. Download 1Password:
  "
  curl -sSO https://downloads.1password.com/linux/tar/stable/x86_64/1password-latest.tar.gz
  echo "
    2. Extract and move the files:
  "
  tar -xf 1password-latest.tar.gz
  sudo mkdir -p /opt/1Password
  sudo mv 1password-*/* /opt/1Password
  echo "
    3. Run the installation script:
  "
  sudo /opt/1Password/after-install.sh

} # end tar
