#!/usr/bin/env bash
#!/bin/bash
#
# @author Zeus Intuivo <zeus@intuivo.com>
#
#
_rpm_bc_installer(){
	set -e
	local BC_LIB=/usr/lib64/beyondcompare


	##
	# Calculate *.rpm file location to use for BC#Key.txt search location
	##
	local parent_env=""
	parent_env=$(ps -p $PPID e) || :
	local cmd_line=""
	# shellcheck disable=SC2001
	cmd_line="$(sed 's/ /\n/g' <<< "$parent_env" | grep -m 1 "bcompare-.*\.rpm$")" || :
	local cmd_path=${cmd_line%bcompare*.rpm} || :
	local work_dir=""
	# shellcheck disable=SC2001
	work_dir="$(sed 's/ /\n/g' <<< "$parent_env" | grep -w "PWD=")" || :
	work_dir="${work_dir##PWD=}" || :
	local slash_pos=""
	# shellcheck disable=SC2001,SC2308
	slash_pos=$(expr index "$cmd_path" /) || :
	local full_path=""
  full_path="$work_dir/$cmd_path"
	if [ "$slash_pos" = "1" ]; then
		full_path=$cmd_path
	fi

	##
	# Copy BC#Key.txt file into install directory if it exists
	##
	if [[ -f "$full_path/BC5Key.txt" ]]; then
		cp "$full_path/BC5Key.txt" "${BC_LIB}/" || :
		chmod a+r "${BC_LIB}/BC5Key.txt" || :
	fi

	##
	# Add our repo address to yum repository list
	##
	local repo_dir=""
	if [ -d /etc/yum.repos.d ]; then
		repo_dir=/etc/yum.repos.d
	fi
	if [ -d /etc/yum/repos.d ]; then
		repo_dir=/etc/yum/repos.d
	fi
	if [[ -n "$repo_dir" ]]; then
		if [[ -f "$repo_dir/scootersoftware.repo" ]]; then
			rm "$repo_dir/scootersoftware.repo"
		fi
		cp "${BC_LIB}/scootersoftware.repo" "$repo_dir"
		chmod 644 "$repo_dir/scootersoftware.repo"
	fi

	##
	# Change permissions on ContextMenu extensions and copy the appropriate one
	# into it's operating location
	##
	chmod a+x "${BC_LIB}/ext/"*.so*

	##
	# Set EXT_ARCH to appropriate value
	##
	local MACH=""
	MACH="$(uname -m)"

	local -i NUM=0
	# shellcheck disable=SC2001,SC1073,SC2308
	NUM=$(expr match "$MACH" 'i[0-9]86') || :

	local EXT_ARCH=""
	local LDCONFIG_ARCH=""
	if [ $NUM -ge 4 ]; then
		EXT_ARCH="i386"
		LDCONFIG_ARCH=""
	else
		EXT_ARCH="amd64"
		LDCONFIG_ARCH="x86-64"
	fi

	##
	# Need to create link to libbz2.so.1.0.  Executable is built on machine with
	# libbz2.so soname = libbz2.so.1.0.  RPM's are installed with machines with
	# libbz2.so soname = libbz2.so.1. Making link here solves problem.
	##
	local libbz2so=""
	libbz2so="$(ldconfig -p | awk -F" " '$1=="libbz2.so.1" && $2~/'${LDCONFIG_ARCH}'/ {print $NF}')"
	ln -sf "$libbz2so" "${BC_LIB}/libbz2.so.1.0"

	##
	# remove old context menu scripts
	##
	for i in /home/* /root; do
		if [ -d "$i/.gnome2/nautilus-scripts" ]; then
			rm -f "$i/.gnome2/nautilus-scripts/compare" || :
			rm -f "$i/.gnome2/nautilus-scripts/compare_to_selected" || :
			rm -f "$i/.gnome2/nautilus-scripts/select_for_compare" || :
		fi
		if [ -d "\$i/.local/share/kservices6/ServiceMenus" ]; then
			rm -f "\$i/.local/share/kservices6/ServiceMenus/beyondcompare.desktop" || :
			rm -f "\$i/.local/share/kservices6/ServiceMenus/beyondcompare_compare.desktop" || :
			rm -f "\$i/.local/share/kservices6/ServiceMenus/beyondcompare_more.desktop" || :
			rm -f "\$i/.local/share/kservices6/ServiceMenus/beyondcompare_select.desktop" || :
		fi
		if [ -d "\$i/.local/share/kservices5/ServiceMenus" ]; then
			rm -f "\$i/.local/share/kservices5/ServiceMenus/beyondcompare.desktop" || :
			rm -f "\$i/.local/share/kservices5/ServiceMenus/beyondcompare_compare.desktop" || :
			rm -f "\$i/.local/share/kservices5/ServiceMenus/beyondcompare_more.desktop" || :
			rm -f "\$i/.local/share/kservices5/ServiceMenus/beyondcompare_select.desktop" || :
		fi
	done


	##
	# Now install appropriate Context extension files
	##
	for EXT_LIB in /usr/lib /usr/lib64
	do
		if [[ -d "$EXT_LIB/qt6/plugins/kf6/kfileitemaction" ]]; then
			cp "${BC_LIB}/ext/bcompare_ext_kde6.$EXT_ARCH.so" \
				"$EXT_LIB/qt6/plugins/kf6/kfileitemaction/bcompare_ext_kde6.so" || :
		elif [[ -d "$EXT_LIB/qt5/plugins/kf5/kfileitemaction" ]]; then
			cp "${BC_LIB}/ext/bcompare_ext_kde5.$EXT_ARCH.so" \
				"$EXT_LIB/qt5/plugins/kf5/kfileitemaction/bcompare_ext_kde5.so" || :
		fi

		for FILE_MANAGER_NAME in nautilus caja nemo
		do
			for EXT_VER in extensions-4 extensions-3.0 extensions-2.0 extensions-1.0
			do
				if [[ -d "$EXT_LIB/$FILE_MANAGER_NAME/$EXT_VER" ]]; then
					if [[ "${EXT_VER}" == "extensions-4" ]]; then
						cp "${BC_LIB}/ext/bcompare-ext-$FILE_MANAGER_NAME.$EXT_ARCH.so.ext4" \
							"$EXT_LIB/$FILE_MANAGER_NAME/$EXT_VER/bcompare-ext-$FILE_MANAGER_NAME.so"
					else
						cp "${BC_LIB}/ext/bcompare-ext-$FILE_MANAGER_NAME.$EXT_ARCH.so" \
							"$EXT_LIB/$FILE_MANAGER_NAME/$EXT_VER/bcompare-ext-$FILE_MANAGER_NAME.so"
					fi
				fi
			done
		done

		for EXT_VER in thunarx-3 thunarx-2
		do
			if [[ -d "$EXT_LIB/$EXT_VER" ]]; then
				cp "${BC_LIB}/ext/bcompare-ext-$EXT_VER.$EXT_ARCH.so" \
					"$EXT_LIB/$EXT_VER/bcompare-ext-thunarx.so"
			fi
		done
	done

	##
	# Set up Beyond Compare mime types and associations
	##
	update-mime-database /usr/share/mime > /dev/null 2>&1
	if [[ -f /usr/share/applications/mimeinfo.cache ]]; then
		echo "application/beyond.compare.snapshot=bcompare.desktop" >> \
			/usr/share/applications/mimeinfo.cache
	fi

	# exit 0 Why is there an exit here ?
	echo "uninstaller ?"

	BC_LIB=/usr/lib64/beyondcompare

	rm -f "${BC_LIB}/BC5Key.txt"



	if [ "$1" = 0 ]; then

	##
	# remove old context menu scripts
	##
	for i in /home/* /root; do
		if [ -d "$i/.gnome2/nautilus-scripts" ]; then
			rm -f "$i/.gnome2/nautilus-scripts/compare"
			rm -f "$i/.gnome2/nautilus-scripts/compare_to_selected"
			rm -f "$i/.gnome2/nautilus-scripts/select_for_compare"
		fi
		if [[ -d "$i/.local/share/kservices5/ServiceMenus" ]]; then
			rm -f "$i/.local/share/kservices5/ServiceMenus/beyondcompare.desktop"
			rm -f "$i/.local/share/kservices5/ServiceMenus/beyondcompare_compare.desktop"
			rm -f "$i/.local/share/kservices5/ServiceMenus/beyondcompare_more.desktop"
			rm -f "$i/.local/share/kservices5/ServiceMenus/beyondcompare_select.desktop"
		fi
		if [ -d "$i/.kde4/share/kde4/services/ServiceMenus" ]; then
			rm -f "$i/.kde4/share/kde4/services/ServiceMenus/beyondcompare.desktop"
			rm -f "$i/.kde4/share/kde4/services/ServiceMenus/beyondcompare_compare.desktop"
			rm -f "$i/.kde4/share/kde4/services/ServiceMenus/beyondcompare_more.desktop"
			rm -f "$i/.kde4/share/kde4/services/ServiceMenus/beyondcompare_select.desktop"
		fi
		if [ -d "$i/.kde/share/kde4/services/ServiceMenus" ]; then
			rm -f "$i/.kde/share/kde4/services/ServiceMenus/beyondcompare.desktop"
			rm -f "$i/.kde/share/kde4/services/ServiceMenus/beyondcompare_compare.desktop"
			rm -f "$i/.kde/share/kde4/services/ServiceMenus/beyondcompare_more.desktop"
			rm -f "$i/.kde/share/kde4/services/ServiceMenus/beyondcompare_select.desktop"
		fi
		if [ -d "$i/.kde/share/apps/konqueror/servicemenus" ]; then
			rm -f "$i/.kde/share/apps/konqueror/servicemenus/beyondcompare.desktop"
			rm -f "$i/.kde/share/apps/konqueror/servicemenus/beyondcompare_compare.desktop"
			rm -f "$i/.kde/share/apps/konqueror/servicemenus/beyondcompare_more.desktop"
			rm -f "$i/.kde/share/apps/konqueror/servicemenus/beyondcompare_select.desktop"
		fi
	done

	##
	# Remove context extensions
	##
	for EXT_LIB in /usr/lib /usr/lib64
	do
		if [[ -d "$EXT_LIB/qt6/plugins/kf6/kfileitemaction" ]]; then
			rm -f "$EXT_LIB/qt6/plugins/kf6/kfileitemaction/bcompare_ext_kde6.so"
		elif [[ -d "$EXT_LIB/qt5/plugins/kf5/kfileitemaction" ]]; then
			rm -f "$EXT_LIB/qt5/plugins/kf5/kfileitemaction/bcompare_ext_kde5.so"
		elif [[ -d "$EXT_LIB/qt5/plugins" ]]; then
			rm -f "$EXT_LIB/qt5/plugins/bcompare_ext_kde.so"
			rm -f /usr/share/kservices5/bcompare_ext_kde.desktop
		fi
		if [[ -d "$EXT_LIB/kde4" ]]; then
			rm -f "$EXT_LIB/kde4/bcompare_ext_konq.so"
			rm -f /usr/share/kde4/services/bcompare_ext_konq.desktop
			rm -f "$EXT_LIB/kde4/bcompare_ext_kde.so"
			rm -f /usr/share/kde4/services/bcompare_ext_kde.desktop
		fi

		for FILE_MANAGER_NAME in nautilus caja nemo
		do
			for EXT_VER in extensions-4 extensions-3.0 extensions-2.0 extensions-1.0
			do
				if [[ -d "$EXT_LIB/$FILE_MANAGER_NAME/$EXT_VER" ]]; then
					rm -f "$EXT_LIB/$FILE_MANAGER_NAME/$EXT_VER/bcompare-ext-$FILE_MANAGER_NAME.so"
				fi
			done
		done

		for EXT_VER in thunarx-3 thunarx-2 thunarx-1
		do
			if [[ -d "$EXT_LIB/$EXT_VER" ]]; then
				rm -f "$EXT_LIB/$EXT_VER/bcompare-ext-thunarx.so"
			fi
		done
	done
	fi

	##
	# Update mime types after Beyond Compare types are removed
	##
	update-mime-database /usr/share/mime > /dev/null 2>&1

	exit 0


}
_version() {
	# fedora_32 https://www.scootersoftware.com/bcompare-4.3.3.24545.i386.rpm
	# https://www.scootersoftware.com/bcompare-4.3.3.24545.x86_64.rpm
	# zz=dl4&platform=mac, zz=dl4&platform=linux, zz=dl4&platform=win

	local PLATFORM="${1}"
	local PATTERN="${2}"
	# THOUGHT: local CODEFILE=$(curl -d "zz=dl4&platform=linux" -H "Content-Type: application/x-www-form-urlencoded" -X POST  -sSLo -  https://www.scootersoftware.com/download.php  2>&1;) # suppress only wget download messages, but keep wget output for variable
	local CODEFILE=""
	CODEFILE="$(curl -d "zz=dl4&platform=${PLATFORM}" -H "Content-Type: application/x-www-form-urlencoded" -X POST  -sSLo -  https://www.scootersoftware.com/download.php  2>&1;)" # suppress only wget download messages, but keep wget output for variable
	# THOUGHT: local CODELASTESTBUILD=$(echo $CODEFILE | sed s/\</\\n\</g | grep "bcompare*.*.*.*.x86_64.rpm" | sed s/\"/\\n/g | grep "/" | cuet "/")
	# local CODELASTESTBUILD=$(echo $CODEFILE | sed s/\</\\n\</g | grep "${PATTERN}" | sed s/\"/\\n/g | grep "/" | cüt "/")
	local CODELASTESTBUILD=""
	# shellcheck disable=SC2001
	CODELASTESTBUILD="$(sed s/\</\\n\</g <<< "$CODEFILE" | grep "${PATTERN}" | sed s/\"/\\n/g | grep "/" | cüt "/files/")"
	# fedora 32 local CODELASTESTBUILD=$(echo $CODEFILE | sed s/\</\\n\</g | grep "bcompare*.*.*.*.i386.rpm" | sed s/\"/\\n/g | grep "/" | cuet "/")
	wait
	[[ -z "${CODELASTESTBUILD}" ]] && failed "Beyond Compare Version not found! :${CODELASTESTBUILD}:"



	# enforce_variable_with_value USER_HOME "${USER_HOME}"
	# enforce_variable_with_value CODELASTESTBUILD "${CODELASTESTBUILD}"

	local CODENAME="${CODELASTESTBUILD}"
	echo "${CODELASTESTBUILD}"
	unset PATTERN
	unset PLATFORM
	unset CODEFILE
	unset CODELASTESTBUILD
} # end _version

_version_test(){
	local CODENAME=$(_version "linux" "bcompare*.*.*.*.x86_64.rpm")
	Checking "CODENAME:${CODENAME}"
	enforce_variable_with_value CODENAME "${CODENAME}"
	exit 0
} # end _version_test
#_version_test

_darwin__64() {
	# sudo_it
	# export USER_HOME="/Users/${SUDO_USER}"
	enforce_variable_with_value USER_HOME "${USER_HOME}"

	local CODENAME=""
	CODENAME=$(_version "mac" "BCompareOSX*.*.*.*.zip")
	enforce_variable_with_value CODENAME "${CODENAME}"
	# THOUGHT        local CODENAME="BCompareOSX-4.3.3.24545.zip"
	local URL="https://www.scootersoftware.com/${CODENAME}"

	# local TARGET_URL
	# TARGET_URL="${CODENAME}|Beyond Compare.app|${URL}"
	# enforce_variable_with_value TARGET_URL "${TARGET_URL}"
	# _install_dmgs_list "${TARGET_URL}"
	local DOWNLOADFOLDER="$USER_HOME/Downloads"
	enforce_variable_with_value DOWNLOADFOLDER "${DOWNLOADFOLDER}"
	cd "${DOWNLOADFOLDER}"
	echo _download_mac
	_download_mac "${URL}" "${DOWNLOADFOLDER}"
	local APPDIR="Beyond Compare.app"    # same as  $(basename "${APPDIR}")
	echo _remove_dmgs_app_if_exists
	_remove_dmgs_app_if_exists "${APPDIR}"
	echo _process_dmgs_dmg_or_zip
	_process_dmgs_dmg_or_zip "zip" "${DOWNLOADFOLDER}" "${CODENAME}" "${APPDIR}" "${CODENAME}"
	echo directory_exists_with_spaces
	directory_exists_with_spaces "/Applications/${APPDIR}"
	ls -d "/Applications/${APPDIR}"

	_trust_dmgs_application "${APPDIR}"
	ln -s /Applications/Beyond\ Compare.app/Contents/MacOS/bcomp /usr/local/bin/bcompare
	ln -s /Applications/Beyond\ Compare.app/Contents/MacOS/bcomp /usr/local/bin/bcomp
	# sudo hdiutil attach ${CODENAME}
	# sudo cp -R /Volumes/Beyond\ Compare/Beyond\ Compare.app /Applications/
	# sudo hdiutil detach /Volumes/Beyond \ Compare
} # end _darwin__64

_debian_flavor_install() {
	# sudo_it
	trap 'echo -e "${RED}" && echo -e "ERROR failed \n$0:$LINENO _debian_flavor_install beyondcomapre" && echo -e "${RESET}" && return 0' ERR

	# export USER_HOME="/home/${SUDO_USER}"
	enforce_variable_with_value USER_HOME "${USER_HOME}"
	enforce_variable_with_value SUDO_USER "${SUDO_USER}"
	# THOUGHT          local CODENAME="bcompare-4.3.3.24545_amd64.deb"
	local CODENAME=""
	CODENAME=$(_version "linux" "bcompare-*.*.*.*amd64.deb")
	enforce_variable_with_value CODENAME "${CODENAME}"
	local TARGET_URL="https://www.scootersoftware.com/${CODENAME}"
	enforce_variable_with_value TARGET_URL "${TARGET_URL}"
	local DOWNLOADFOLDER=""
	DOWNLOADFOLDER="$(_find_downloads_folder)"
	enforce_variable_with_value DOWNLOADFOLDER "${DOWNLOADFOLDER}"
	cd "${DOWNLOADFOLDER}"
	_download_mac "${TARGET_URL}" "${DOWNLOADFOLDER}"
	dpkg -i ${CODENAME}
} # end _debian_flavor_install

_package_list_installer() {
	local package packages="${*-}"
	trap 'echo -e "${RED}" && echo -e "ERROR failed \n$0:$LINENO _package_list_installer rbenv" && echo -e "${RESET}" && return 0' ERR

	if ! install_requirements "linux" "${packages}" ; then
	{
		warning "installing requirements. ${CYAN} attempting to install one by one"
		while read -r package; do
		{
			[[ -z ${package} ]] && continue
			install_requirements "linux" "${package}"
			_err=$?
			if [ ${_err} -gt 0 ] ; then
			{
					failed to install requirements "${package}"
			}
			fi
		}
		done <<< "${packages}"
  }
	fi
} # end _package_list_installer

_ubuntu__64() {
	trap 'echo -e "${RED}" && echo "ERROR failed $0:$LINENO _ubuntu__64 beyondcomapre" && echo -e "${RESET}" && return 0' ERR

	local package packages="
	poppler-utils
	"
	_package_list_installer "${packages}"
	_debian_flavor_install
} # end _ubuntu__64

_ubuntu__aarch64() {
	trap  '_trap_on_error $0 "${?}" LINENO BASH_LINENO FUNCNAME BASH_COMMAND $FUNCNAME $BASH_LINENO $LINENO   $BASH_COMMAND'  ERR
	local package packages="
	poppler-utils
	"
	_package_list_installer "${packages}"

	_debian_flavor_install
} # end _ubuntu__aarch64

_ubuntu_22__aarch64() {
	trap  '_trap_on_error $0 "${?}" LINENO BASH_LINENO FUNCNAME BASH_COMMAND $FUNCNAME $BASH_LINENO $LINENO   $BASH_COMMAND'  ERR
	local package packages="
	poppler-utils
	"
	_package_list_installer "${packages}"
	_debian_flavor_install
} # end _ubuntu_22__aarch64

_ubuntu__32() {
	#sudo_it
	# export USER_HOME="/Users/${SUDO_USER}"
	enforce_variable_with_value USER_HOME "${USER_HOME}"
	# _linux_prepare
	# THOUGHT local CODENAME="bcompare-4.3.3.24545_i386.deb"
	local CODENAME=""
	CODENAME=$(_version "linux" "bcompare-*.*.*.*i386.deb")
	enforce_variable_with_value CODENAME "${CODENAME}"
	local TARGET_URL="https://www.scootersoftware.com/${CODENAME}"
	enforce_variable_with_value TARGET_URL "${TARGET_URL}"

	local DOWNLOADFOLDER=""
	DOWNLOADFOLDER="$(_find_downloads_folder)"
	enforce_variable_with_value DOWNLOADFOLDER "${DOWNLOADFOLDER}"
	cd "${DOWNLOADFOLDER}"
	_download_mac "${TARGET_URL}" "${DOWNLOADFOLDER}"
	sudo dpkg -i ${CODENAME}
} # end _ubuntu__32

_fedora__32() {
	#sudo_it
	# export USER_HOME="/Users/${SUDO_USER}"
	enforce_variable_with_value USER_HOME "${USER_HOME}"
	# _linux_prepare
	local CODENAME=""
	CODENAME=$(_version "linux" "bcompare*.*.*.*.i386.rpm")
	enforce_variable_with_value CODENAME "${CODENAME}"
	# THOUGHT                          bcompare-4.3.3.24545.i386.rpm
	local TARGET_URL="https://www.scootersoftware.com/${CODENAME}"
	enforce_variable_with_value TARGET_URL "${TARGET_URL}"
	local DOWNLOADFOLDER=""
	DOWNLOADFOLDER="$(_find_downloads_folder)"
	enforce_variable_with_value DOWNLOADFOLDER "${DOWNLOADFOLDER}"
	cd "${DOWNLOADFOLDER}"
	wget --max-redirect=10 -O "${DOWNLOADFOLDER}/${CODENAME}" "${TARGET_URL}"
  # _download "${TARGET_URL}" "${USER_HOME}/Downloads" "${CODENAME}"
	file_exists_with_spaces "${DOWNLOADFOLDER}/${CODENAME}"
	ensure rpm or "Canceling Install. Could not find rpm command to execute install"
	# provide error handling , once learned goes here. LEarn under if, once learned here.
	# Start loop while ERROR flag in case needs to try again, based on error
	_try "rpm --import https://www.scootersoftware.com/RPM-GPG-KEY-scootersoftware"
	local msg=""
	msg=$(_try "rpm -ivh \"${DOWNLOADFOLDER}/${CODENAME}\"" )
	local ret=$?
	if [ $ret -gt 0 ] ; then
		{
			failed "${ret}:${msg}"
			# add error handling knowledge while learning.
		}
else
	{
		passed Install with RPM success!
	}
	fi
	ensure bcompare or "Failed to install Beyond Compare"
	rm -f "${DOWNLOADFOLDER}/${CODENAME}"
	file_does_not_exist_with_spaces "${DOWNLOADFOLDER}/${CODENAME}"
} # end _fedora__32

_centos__64() {
	_fedora__64
} # end _centos__64

_fedora__64() {
	#sudo_it
	# export USER_HOME="/Users/${SUDO_USER}"
	enforce_variable_with_value USER_HOME "${USER_HOME}"
	# _linux_prepare
	local CODENAME=""
	CODENAME=$(_version "linux" "bcompare*.*.*.*.x86_64.rpm")
	Checking "_version:${CODENAME}"
	enforce_variable_with_value CODENAME "${CODENAME}"
	# THOUGHT  https://www.scootersoftware.com/bcompare-4.3.3.24545.x86_64.rpm
	local TARGET_URL=""
	# shellcheck disable=SC2001
	TARGET_URL="$(sed 's@//@/@g' <<<"www.scootersoftware.com/files/${CODENAME}")"
	TARGET_URL="https://${TARGET_URL}"
	Checking "TARGET_URL:${TARGET_URL}"
	enforce_variable_with_value TARGET_URL "${TARGET_URL}"
	local DOWNLOADFOLDER=""
	DOWNLOADFOLDER="$(_find_downloads_folder)"
	enforce_variable_with_value DOWNLOADFOLDER "${DOWNLOADFOLDER}"
	cd "${DOWNLOADFOLDER}"
  _do_not_downloadtwice "${TARGET_URL}" "${DOWNLOADFOLDER}"  "${CODENAME}"
  # wget --max-redirect=10 -O "${DOWNLOADFOLDER}/${CODENAME}" "${TARGET_URL}"
	_err=$?
	if [ ${_err} -gt 0 ] ; then
	{
		warm "failed download:$LINENO $0:$LINENO above _err:${_err}"
	}
	fi

  _install_rpm "${TARGET_URL}" "${DOWNLOADFOLDER}"  "${CODENAME}" 0

	ensure bcompare or "Failed to install Beyond Compare"
	rm -f "${DOWNLOADFOLDER}/${CODENAME}"
	file_does_not_exist_with_spaces "${DOWNLOADFOLDER}/${CODENAME}"
} # end _fedora__64

_fedora_37__64() {
	trap 'echo Error:$?' ERR INT
	local _parameters="${*-}"
	local -i _err=0
	_fedora__64 "${_parameters-}"
	_err=$?
	if [ ${_err} -gt 0 ] ; then
	{
		failed "struct_testing:$LINENO $0:$LINENO while running callsomething above _err:${_err}"
	}
	fi
} # end _fedora_37__64

_mingw__64() {
	# sudo_it
	export USER_HOME="/Users/${SUDO_USER}"
	enforce_variable_with_value USER_HOME "${USER_HOME}"
	# _linux_prepare
	local CODENAME=""
	CODENAME=$(_version "win" "BCompare*.*.*.*.exe")
	# THOUGHT        local CODENAME="BCompare-4.3.3.24545.exe"
	local URL="https://www.scootersoftware.com/${CODENAME}"
	cd "$HOMEDIR"
	cd Downloads
	curl -O "$URL"
	${CODENAME}
} # end _mingw__64

_mingw__32() {
	_linux_prepare
	local CODENAME=""
	CODENAME=$(_version "win" "BCompare*.*.*.*.exe")
	# THOUGHT        local CODENAME="BCompare-4.3.3.24545.exe"
	local URL="https://www.scootersoftware.com/${CODENAME}"
	cd "$HOMEDIR"
	cd Downloads
	curl -O "$URL"
	${CODENAME}
} # end

_main() {
	determine_os_and_fire_action
} # end _main

_main

echo ":)"
