#!/usr/bin/bash

_debian_flavor_install() {
  trap  '_trap_on_error $0 "${?}" LINENO BASH_LINENO FUNCNAME BASH_COMMAND $FUNCNAME $BASH_LINENO $LINENO   $BASH_COMMAND'  ERR
  enforce_variable_with_value USER_HOME "${USER_HOME}"
  if (
  install_requirements "linux" "
    unzip
    curl
    wget
  "
  ); then
    {
      apt install base64 -y
      apt install unzip -y
      apt install nginx -y
    }
  fi
  verify_is_installed "
    unzip
    curl
    wget
    tar
  "
  cat << EOF > "${USER_HOME}/install_powerlevel10k_sub.zsh"
#!/usr/bin/env zsh
#!/bin/zsh

export  THISSCRIPTNAME
typeset -r THISSCRIPTNAME="\$(basename "\$0")"

  function _trap_on_error(){
    local -ir __trapped_error_exit_num="\${2:-0}"
		echo -e "\\n \033[01;7m*** install_powerlevel10k_sub.zsh:$LINENO  _trap_on_error() ERROR TRAP \$THISSCRIPTNAME \\n\${BASH_SOURCE}:\${BASH_LINENO[-0]} \${FUNCNAME[1]}() \\n\$0:\${BASH_LINENO[1]} \${FUNCNAME[2]}()  \\n\$0:\${BASH_LINENO[2]} \${FUNCNAME[3]}() \\n ERR ...\033[0m  \n \n "
    echo ". \${1}"
    echo ". exit  \${__trapped_error_exit_num}  "
    echo ". caller \$(caller) "
    echo ". \${BASH_COMMAND}"
    local -r __caller=\$(caller)
    local -ir __caller_line=\$(echo "\${__caller}" | cut -d' ' -f1)
    local -r __caller_script_name=\$(echo "\${__caller}" | cut -d' ' -f2)
    awk 'NR>L-10 && NR<L+10 { printf "%-10d%10s%s\n",NR,(NR==L?"☠ » » » > ":""),\$0 }' L="\${__caller_line}" "\${__caller_script_name}"

    # \$(eval \${BASH_COMMAND}  2>&1; )
    # echo -e " ☠ \${LIGHTPINK} Offending message:  \${__bash_error} \${RESET}"  >&2
    exit \${__trapped_INT_num}
  }
  trap  '_trap_on_error \$0 "\${?}" LINENO BASH_LINENO FUNCNAME BASH_COMMAND \$FUNCNAME \$BASH_LINENO \$LINENO   \$BASH_COMMAND'  ERR

    emulate -L zsh -o xtrace -o err_return
    ZDOTDIR=/no/such/dir command zsh -ic '[[ \$ZDOTDIR == /no/such/dir ]]'
    command mkdir -p -- ~/zsh-backup
    local rc
    for rc in ~/.zshenv ~/.zprofile ~/.zshrc ~/.zlogin ~/.zlogout ~/.oh-my-zsh; do
      [[ -e \$rc ]] || continue
      [[ ! -e ~/zsh-backup/\${rc:t} ]] || {
        command rm -rf -- \$rc
        continue
      }
      command rm -rf -- ~/zsh-backup/\${rc:t}.tmp.\$\$
      command cp -r -- \$rc ~/zsh-backup/\${rc:t}.tmp.\$\$
      command mv -- ~/zsh-backup/\${rc:t}.tmp.\$\$ ~/zsh-backup/\${rc:t}
      command rm -rf -- \$rc
    done
    command git clone -- https://github.com/ohmyzsh/ohmyzsh.git ~/.oh-my-zsh
    command git clone --depth=1 -- https://github.com/romkatv/powerlevel10k.git ~/.oh-my-zsh/custom/themes/powerlevel10k
    command sed -- 's|robbyrussell|powerlevel10k/powerlevel10k|' ~/.oh-my-zsh/templates/zshrc.zsh-template >~/.zshrc
    ZDOTDIR=~ exec zsh -i
  # }
EOF
  cd "${USER_HOME}"
  chmod a+x "${USER_HOME}/install_powerlevel10k_sub.zsh"
  chown -R $SUDO_USER  "${USER_HOME}/install_powerlevel10k_sub.zsh"
  su - "${SUDO_USER}" -c "( "${USER_HOME}/install_powerlevel10k_sub.zsh" )"
  chown -R "${SUDO_USER}" "${USER_HOME}/.oh-my-zsh"
  install_requirements "darwin" "
    zsh-syntax-highlighting
    zsh-autosuggestions
  "
  cd "${USER_HOME}"
  su - "${SUDO_USER}" -c "git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${USER_HOME}/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting"
  su - "${SUDO_USER}" -c "git clone https://github.com/zsh-users/zsh-autosuggestions ${USER_HOME}/.oh-my-zsh/custom/plugins/zsh-autosuggestions"
  rm ./install_powerlevel10k_sub.zsh

} # end _debian_flavor_install

_redhat_flavor_install() {
  trap  '_trap_on_error $0 "${?}" LINENO BASH_LINENO FUNCNAME BASH_COMMAND $FUNCNAME $BASH_LINENO $LINENO   $BASH_COMMAND'  ERR
_darwin__arm64
#  echo "_redhat_flavor_install Procedure not yet implemented. I don't know what to do."
} # end _redhat_flavor_install

_arch_flavor_install() {
  trap  '_trap_on_error $0 "${?}" LINENO BASH_LINENO FUNCNAME BASH_COMMAND $FUNCNAME $BASH_LINENO $LINENO   $BASH_COMMAND'  ERR
  echo "_arch_flavor_install Procedure not yet implemented. I don't know what to do."
} # end _readhat_flavor_install

_arch__32() {
  trap  '_trap_on_error $0 "${?}" LINENO BASH_LINENO FUNCNAME BASH_COMMAND $FUNCNAME $BASH_LINENO $LINENO   $BASH_COMMAND'  ERR
  _arch_flavor_install
} # end _arch__32

_arch__64() {
  trap  '_trap_on_error $0 "${?}" LINENO BASH_LINENO FUNCNAME BASH_COMMAND $FUNCNAME $BASH_LINENO $LINENO   $BASH_COMMAND'  ERR
  _arch_flavor_install
} # end _arch__64

_centos__32() {
  trap  '_trap_on_error $0 "${?}" LINENO BASH_LINENO FUNCNAME BASH_COMMAND $FUNCNAME $BASH_LINENO $LINENO   $BASH_COMMAND'  ERR
  _redhat_flavor_install
} # end _centos__32

_centos__64() {
  trap  '_trap_on_error $0 "${?}" LINENO BASH_LINENO FUNCNAME BASH_COMMAND $FUNCNAME $BASH_LINENO $LINENO   $BASH_COMMAND'  ERR
  _redhat_flavor_install
} # end _centos__64

_debian__32() {
  trap  '_trap_on_error $0 "${?}" LINENO BASH_LINENO FUNCNAME BASH_COMMAND $FUNCNAME $BASH_LINENO $LINENO   $BASH_COMMAND'  ERR
  _debian_flavor_install
} # end _debian__32

_debian__64() {
  trap  '_trap_on_error $0 "${?}" LINENO BASH_LINENO FUNCNAME BASH_COMMAND $FUNCNAME $BASH_LINENO $LINENO   $BASH_COMMAND'  ERR
  _debian_flavor_install
} # end _debian__64

_fedora__32() {
  trap  '_trap_on_error $0 "${?}" LINENO BASH_LINENO FUNCNAME BASH_COMMAND $FUNCNAME $BASH_LINENO $LINENO   $BASH_COMMAND'  ERR
  _redhat_flavor_install
} # end _fedora__32

_fedora__64() {
  trap  '_trap_on_error $0 "${?}" LINENO BASH_LINENO FUNCNAME BASH_COMMAND $FUNCNAME $BASH_LINENO $LINENO   $BASH_COMMAND'  ERR
  _redhat_flavor_install
} # end _fedora__64

_gentoo__32() {
  trap  '_trap_on_error $0 "${?}" LINENO BASH_LINENO FUNCNAME BASH_COMMAND $FUNCNAME $BASH_LINENO $LINENO   $BASH_COMMAND'  ERR
  _redhat_flavor_install
} # end _gentoo__32

_gentoo__64() {
  trap  '_trap_on_error $0 "${?}" LINENO BASH_LINENO FUNCNAME BASH_COMMAND $FUNCNAME $BASH_LINENO $LINENO   $BASH_COMMAND'  ERR
  _redhat_flavor_install
} # end _gentoo__64

_madriva__32() {
  trap  '_trap_on_error $0 "${?}" LINENO BASH_LINENO FUNCNAME BASH_COMMAND $FUNCNAME $BASH_LINENO $LINENO   $BASH_COMMAND'  ERR
  _redhat_flavor_install
} # end _madriva__32

_madriva__64() {
  trap  '_trap_on_error $0 "${?}" LINENO BASH_LINENO FUNCNAME BASH_COMMAND $FUNCNAME $BASH_LINENO $LINENO   $BASH_COMMAND'  ERR
  _redhat_flavor_install
} # end _madriva__64

_suse__32() {
  trap  '_trap_on_error $0 "${?}" LINENO BASH_LINENO FUNCNAME BASH_COMMAND $FUNCNAME $BASH_LINENO $LINENO   $BASH_COMMAND'  ERR
  _redhat_flavor_install
} # end _suse__32

_suse__64() {
  trap  '_trap_on_error $0 "${?}" LINENO BASH_LINENO FUNCNAME BASH_COMMAND $FUNCNAME $BASH_LINENO $LINENO   $BASH_COMMAND'  ERR
  _redhat_flavor_install
} # end _suse__64

_ubuntu__32() {
  trap  '_trap_on_error $0 "${?}" LINENO BASH_LINENO FUNCNAME BASH_COMMAND $FUNCNAME $BASH_LINENO $LINENO   $BASH_COMMAND'  ERR
  _debian_flavor_install
} # end _ubuntu__32

_ubuntu__64() {
  trap  '_trap_on_error $0 "${?}" LINENO BASH_LINENO FUNCNAME BASH_COMMAND $FUNCNAME $BASH_LINENO $LINENO   $BASH_COMMAND'  ERR
  _debian_flavor_install
} # end _ubuntu__64

_ubuntu__aarch64() {
  trap 'echo Error:$?' ERR INT
  local _parameters="${*-}"
  local -i _err=0
  _debian_flavor_install "${_parameters-}"
  _err=$?
  if [ ${_err} -gt 0 ] ; then
  {
    failed "$0:$LINENO  while running callsomething above _err:${_err}"
  }
  fi
} # end _ubuntu__aarch64

_darwin__64() {
  trap  '_trap_on_error $0 "${?}" LINENO BASH_LINENO FUNCNAME BASH_COMMAND $FUNCNAME $BASH_LINENO $LINENO   $BASH_COMMAND'  ERR
  echo "_darwin__64 Procedure not yet implemented. I don't know what to do."
} # end _darwin__64

_darwin__arm64() {
  trap  '_trap_on_error $0 "${?}" LINENO BASH_LINENO FUNCNAME BASH_COMMAND $FUNCNAME $BASH_LINENO $LINENO   $BASH_COMMAND'  ERR
  # () {
  cat << EOF > "${USER_HOME}/install_powerlevel10k_sub.zsh"
#!/usr/bin/env zsh
#!/bin/zsh

export  THISSCRIPTNAME
typeset -r THISSCRIPTNAME="\$(basename "\$0")"

  function _trap_on_error(){
    local -ir __trapped_error_exit_num="\${2:-0}"
    echo -e "\\n \033[01;7m*** install_powerlevel10k_sub.zsh:$LINENO  _trap_on_error() ERROR TRAP \$THISSCRIPTNAME \\n\${BASH_SOURCE}:\${BASH_LINENO[-0]} \${FUNCNAME[1]}() \\n\$0:\${BASH_LINENO[1]} \${FUNCNAME[2]}()  \\n\$0:\${BASH_LINENO[2]} \${FUNCNAME[3]}() \\n ERR ...\033[0m  \n \n "
    echo ". \${1}"
    echo ". exit  \${__trapped_error_exit_num}  "
    echo ". caller \$(caller) "
    echo ". \${BASH_COMMAND}"
    local -r __caller=\$(caller)
    local -ir __caller_line=\$(echo "\${__caller}" | cut -d' ' -f1)
    local -r __caller_script_name=\$(echo "\${__caller}" | cut -d' ' -f2)
    awk 'NR>L-10 && NR<L+10 { printf "%-10d%10s%s\n",NR,(NR==L?"☠ » » » > ":""),\$0 }' L="\${__caller_line}" "\${__caller_script_name}"

    # \$(eval \${BASH_COMMAND}  2>&1; )
    # echo -e " ☠ \${LIGHTPINK} Offending message:  \${__bash_error} \${RESET}"  >&2
    exit \${__trapped_INT_num}
  }
  trap  '_trap_on_error \$0 "\${?}" LINENO BASH_LINENO FUNCNAME BASH_COMMAND \$FUNCNAME \$BASH_LINENO \$LINENO   \$BASH_COMMAND'  ERR

    emulate -L zsh -o xtrace -o err_return
    ZDOTDIR=/no/such/dir command zsh -ic '[[ \$ZDOTDIR == /no/such/dir ]]'
    command mkdir -p -- ~/zsh-backup
    local rc
    for rc in ~/.zshenv ~/.zprofile ~/.zshrc ~/.zlogin ~/.zlogout ~/.oh-my-zsh; do
      [[ -e \$rc ]] || continue
      [[ ! -e ~/zsh-backup/\${rc:t} ]] || {
        command rm -rf -- \$rc
        continue
      }
      command rm -rf -- ~/zsh-backup/\${rc:t}.tmp.\$\$
      command cp -r -- \$rc ~/zsh-backup/\${rc:t}.tmp.\$\$
      command mv -- ~/zsh-backup/\${rc:t}.tmp.\$\$ ~/zsh-backup/\${rc:t}
      command rm -rf -- \$rc
    done
    command git clone -- https://github.com/ohmyzsh/ohmyzsh.git ~/.oh-my-zsh
    command git clone --depth=1 -- https://github.com/romkatv/powerlevel10k.git ~/.oh-my-zsh/custom/themes/powerlevel10k
    command sed -- 's|robbyrussell|powerlevel10k/powerlevel10k|' ~/.oh-my-zsh/templates/zshrc.zsh-template >~/.zshrc
    ZDOTDIR=~ exec zsh -i
  # }
EOF
  cd "${USER_HOME}"
  chmod a+x "${USER_HOME}/install_powerlevel10k_sub.zsh"
  chown -R $SUDO_USER  "${USER_HOME}/install_powerlevel10k_sub.zsh"
  su - "${SUDO_USER}" -c "( "${USER_HOME}/install_powerlevel10k_sub.zsh" )"
  chown -R "${SUDO_USER}" "${USER_HOME}/.oh-my-zsh"
  install_requirements "darwin" "
    zsh-syntax-highlighting
    zsh-autosuggestions
  "
  cd "${USER_HOME}"
  su - "${SUDO_USER}" -c "git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${USER_HOME}/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting"
  su - "${SUDO_USER}" -c "git clone https://github.com/zsh-users/zsh-autosuggestions ${USER_HOME}/.oh-my-zsh/custom/plugins/zsh-autosuggestions"
  rm ./install_powerlevel10k_sub.zsh
  # echo "_darwin__arm64 Procedure not yet implemented. I don't know what to do."
} # end _darwin__arm64

_tar() {
  trap  '_trap_on_error $0 "${?}" LINENO BASH_LINENO FUNCNAME BASH_COMMAND $FUNCNAME $BASH_LINENO $LINENO   $BASH_COMMAND'  ERR
  echo "_tar Procedure not yet implemented. I don't know what to do."
} # end tar

_windows__64() {
  trap  '_trap_on_error $0 "${?}" LINENO BASH_LINENO FUNCNAME BASH_COMMAND $FUNCNAME $BASH_LINENO $LINENO   $BASH_COMMAND'  ERR
  echo "_windows__64 Procedure not yet implemented. I don't know what to do."
} # end _windows__64

_windows__32() {
  trap  '_trap_on_error $0 "${?}" LINENO BASH_LINENO FUNCNAME BASH_COMMAND $FUNCNAME $BASH_LINENO $LINENO   $BASH_COMMAND'  ERR
  echo "_windows__32 Procedure not yet implemented. I don't know what to do."
} # end _windows__32
