#!/usr/bin/bash
alias egrep='grep -E --color=auto --exclude-dir={.bzr,CVS,.git,.hg,.svn,.idea,.tox}'
_add_variables_to_bashrc_zshrc(){
  # trap 'echo -e "${RED}" && echo "ERROR failed $0:$LINENO _add_variables_to_bashrc_zshrc cargo" && echo -e "${RESET}" && return 0' ERR
  local FINDCARGO_USER="${USER_HOME}/.cargo"
  local FINDCARGO_ROOT="/root/.cargo"


  if [[ -e "/root/.cargo/bin/cargo" ]] ; then
  {
    FINDCARGO_ROOT="/root/.cargo"
  }
  fi

  if [[ -e "${USER_HOME}/.cargo/bin/cargo" ]] ; then
  {
    FINDCARGO_USER="${USER_HOME}/.cargo"
  }
  elif [[ -e "/opt/cargo/bin/cargo" ]] ; then
  {
    FINDCARGO_USER="/opt/cargo"
  }
  fi

  local CARGO_SH_CONTENT_ROOT='

# CARGO - RUST
source "'${FINDCARGO_ROOT}'/env"

'
  local CARGO_SH_CONTENT_USER='

# CARGO - RUST
source "'${FINDCARGO_USER}'/env"

'
  echo "${CARGO_SH_CONTENT_USER}"
  local INITFILE INITFILES="
   .bashrc
   .zshrc
   .bash_profile
   .profile
   .zshenv
   .zprofile
  "
  local changed_files=""
  while read INITFILE; do
  {
    [ -z ${INITFILE} ] && continue
		# USER
    [[ ! -e "${USER_HOME}/${INITFILE}" ]] && continue
    Checking "${USER_HOME}/${INITFILE}"
    chown "${SUDO_USER}" "${USER_HOME}/${INITFILE}"
    (_if_not_contains  "${USER_HOME}/${INITFILE}" "# CARGO - RUST" ) || Configuring "${USER_HOME}/${INITFILE}"
    (_if_not_contains  "${USER_HOME}/${INITFILE}" "# CARGO - RUST" ) && Skipping configuration for "${USER_HOME}/${INITFILE}"
    #                             filename            value          || do this .............
    (_if_not_contains  "${USER_HOME}/${INITFILE}" "# CARGO - RUST" ) || echo -e "${CARGO_SH_CONTENT_USER}" >> "${USER_HOME}/${INITFILE}"
    (_if_not_contains  "${USER_HOME}/${INITFILE}" "# CARGO - RUST" ) && changed_files="${changed_files} \"${USER_HOME}/${INITFILE}\" "

		# ROOT
    [[ ! -e "${HOME}/${INITFILE}" ]] && continue
    Checking "${HOME}/${INITFILE}"
    # chown "${SUDO_USER}" "${HOME}/${INITFILE}"
    (_if_not_contains  "${HOME}/${INITFILE}" "# CARGO - RUST" ) || Configuring "${HOME}/${INITFILE}"
    (_if_not_contains  "${HOME}/${INITFILE}" "# CARGO - RUST" ) && Skipping configuration for "${HOME}/${INITFILE}"
    #                             filename            value          || do this .............
    (_if_not_contains  "${HOME}/${INITFILE}" "# CARGO - RUST" ) || echo -e "${CARGO_SH_CONTENT_ROOT}" >> "${HOME}/${INITFILE}"
    (_if_not_contains  "${HOME}/${INITFILE}" "# CARGO - RUST" ) && changed_files="${changed_files} \"${HOME}/${INITFILE}\" "


  }
  done <<< "${INITFILES}"
  # if it_exists /home/linuxcargo ; then
  # {
  #   rm -rf /home/linuxcargo
  # }
  # fi
  file_exists_with_spaces "${FINDCARGO_USER}"
  source "${FINDCARGO_USER}/env"
  Checking "all files changed files command for you" :
  echo "sudo vim ${changed_files}"
  echo "sudo nano ${changed_files}"
} # _add_variables_to_bashrc_zshrc


_debian_flavor_install() {
  # trap  '_trap_on_exit $0 "${?}" LINENO BASH_LINENO FUNCNAME BASH_COMMAND $FUNCNAME $BASH_LINENO $LINENO   $BASH_COMMAND'  EXIT
  trap  '_trap_on_error $0 "${?}" LINENO BASH_LINENO FUNCNAME BASH_COMMAND $FUNCNAME $BASH_LINENO $LINENO   $BASH_COMMAND'  ERR
  enforce_variable_with_value USER_HOME "${USER_HOME}"
  if
    (
    install_requirements "linux" "
      base64
      unzip
      curl
      wget
      ufw
      nginx
    "
    ); then
    {
      apt install base64 -y
      apt install unzip -y
    }
  fi
  verify_is_installed "
    unzip
    curl
    wget
    tar
  "
  export ARCHFLAGS="-arch $(uname -m)"
  ARCHFLAGS="-arch $(uname -m)" curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
  [[ ! -e "${USER_HOME}/.cargo" ]] && cp -R /root/.cargo "${USER_HOME}/.cargo"
  chmod -R 755 "${USER_HOME}/.cargo"
  chown -R "${SUDO_USER}"   "${USER_HOME}/.cargo"
  chown -R "${SUDO_USER}"   "${USER_HOME}/.cargo/bin"
  chown -R "${SUDO_USER}"   "${USER_HOME}/.cargo/env"
 #  su - "${SUDO_USER}" -c "ARCHFLAGS='-arch $(uname -m)' curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh"
 if su - "${SUDO_USER}" -c "ARCHFLAGS='-arch $(uname -m)' curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh" ; then
          {
                  echo "oops"
          }
  fi

  _add_variables_to_bashrc_zshrc
  rustup default stable
  su - "${SUDO_USER}" -c "rustup default stable"
} # end _debian_flavor_install

_redhat_flavor_install() {
  trap  '_trap_on_error $0 "${?}" LINENO BASH_LINENO FUNCNAME BASH_COMMAND $FUNCNAME $BASH_LINENO $LINENO   $BASH_COMMAND'  ERR
  enforce_variable_with_value USER_HOME "${USER_HOME}"
  Checking if rust is installed by brew and attempting remove it
  if ( ! su - "${SUDO_USER}" -c "command -v /home/linuxbrew/.linuxbrew/bin/brew" >/dev/null 2>&1; ); then
  {
    if su - "${SUDO_USER}" -c "/home/linuxbrew/.linuxbrew/bin/brew remove rust" ; then
    {
      warning "could not remove rust from user root brew"
    }
    else
    {
      passed "removed rust from brew user root"
    }
    fi
  }
  fi

  if ( ! command -v /home/linuxbrew/.linuxbrew/bin/brew >/dev/null 2>&1; ); then
  {
    if /home/linuxbrew/.linuxbrew/bin/brew remove rust ; then
    {
      warning "could not remove rust from user root brew"
    }
    else
    {
      passed "removed rust from brew user root"
    }
    fi
  }
  fi

  dnf build-dep rust  -y --allowerasing --skip-broken
  if (install_requirements "linux" "
      unzip
      curl
      wget
    "
    ); then
  {
      echo "warning: failed to install some deps"
  }
  fi
  verify_is_installed "
    unzip
    curl
    wget
    tar
  "
  Installing "_add_variables_to_bashrc_zshrc for ROOT and USER"
  _add_variables_to_bashrc_zshrc

  export ARCHFLAGS="-arch $(uname -m)"

  ARCHFLAGS="-arch $(uname -m)"
  Installing "ROOT install:ARCHFLAGS='-arch ${ARCHFLAGS-}' curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh"
  curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs > rustup.sh
  local cpwd=$(realpath .)
  local -i _err=0
  chmod +x "${cpwd}/rustup.sh"
  ARCHFLAGS='-arch ${ARCHFLAGS-}' "${cpwd}/rustup.sh" --no-modify-path --target /root --quiet -y
  _err=$?
  if [ ${_err} -gt 0 ] ; then
  {
    rm -rf "${cpwd}/rustup.sh"
    failed "Failed to install for root err:${_err}"
  }
  else
  {
    passed "install for root"
  }
  fi
  [[ ! -e "${USER_HOME}/.cargo" ]] && cp -R /root/.cargo "${USER_HOME}/.cargo"
  chmod -R 755 "${USER_HOME}/.cargo"
  chown -R "${SUDO_USER}"   "${USER_HOME}/.cargo"
  chown -R "${SUDO_USER}"   "${USER_HOME}/.cargo/bin"
  chown -R "${SUDO_USER}"   "${USER_HOME}/.cargo/env"
  Installing "USER install(${USER_HOME}):su - \"${SUDO_USER}\" -c \"ARCHFLAGS='-arch $(uname -m)' curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh\""
  # if su - "${SUDO_USER}" -c "ARCHFLAGS='-arch $(uname -m)' curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh" ; then
  chown -R "${SUDO_USER}" "${cpwd}/rustup.sh"
  su - "${SUDO_USER}" -c "ARCHFLAGS='-arch $(uname -m)' "${cpwd}/rustup.sh" --no-modify-path --target /home/zeus --quiet -y"
  _err=$?
  if [ ${_err} -gt 0 ] ; then
  {
    rm -rf "${cpwd}/rustup.sh"
    failed "Failed to install for user err:${_err}"
  }
  else
  {
    passed "install for user"
  }
  fi
  rm -rf "${cpwd}/rustup.sh"
  Installing "_add_variables_to_bashrc_zshrc for ROOT and USER"
  _add_variables_to_bashrc_zshrc

	chown -R "${SUDO_USER}"   "${USER_HOME}/.rustup"
  chown -R "${SUDO_USER}"   "${USER_HOME}/.cargo"
  chown -R "${SUDO_USER}"   "${USER_HOME}/.cargo/bin"
  chown -R "${SUDO_USER}"   "${USER_HOME}/.cargo/env"

  Installing "ROOT: rustup default stable"
  rustup default stable
  Installing "USER: su - \"${SUDO_USER}\" -c \"rustup default stable\""
  su - "${SUDO_USER}" -c "rustup default stable"
	chown -R "${SUDO_USER}"   "${USER_HOME}/.rustup"
  chown -R "${SUDO_USER}"   "${USER_HOME}/.cargo"
  chown -R "${SUDO_USER}"   "${USER_HOME}/.cargo/bin"
  chown -R "${SUDO_USER}"   "${USER_HOME}/.cargo/env"

} # end _redhat_flavor_install

_arch_flavor_install() {
  trap  '_trap_on_error $0 "${?}" LINENO BASH_LINENO FUNCNAME BASH_COMMAND $FUNCNAME $BASH_LINENO $LINENO   $BASH_COMMAND'  ERR
  echo "_arch_flavor_install Procedure not yet implemented. I don't know what to do."
} # end _readhat_flavor_install

_arch__32() {
  trap  '_trap_on_error $0 "${?}" LINENO BASH_LINENO FUNCNAME BASH_COMMAND $FUNCNAME $BASH_LINENO $LINENO   $BASH_COMMAND'  ERR
  _arch_flavor_install
} # end _arch__32

_arch__64() {
  trap  '_trap_on_error $0 "${?}" LINENO BASH_LINENO FUNCNAME BASH_COMMAND $FUNCNAME $BASH_LINENO $LINENO   $BASH_COMMAND'  ERR
  _arch_flavor_install
} # end _arch__64

_centos__32() {
  trap  '_trap_on_error $0 "${?}" LINENO BASH_LINENO FUNCNAME BASH_COMMAND $FUNCNAME $BASH_LINENO $LINENO   $BASH_COMMAND'  ERR
  _redhat_flavor_install
} # end _centos__32

_centos__64() {
  trap  '_trap_on_error $0 "${?}" LINENO BASH_LINENO FUNCNAME BASH_COMMAND $FUNCNAME $BASH_LINENO $LINENO   $BASH_COMMAND'  ERR
  _redhat_flavor_install
} # end _centos__64

_debian__32() {
  trap  '_trap_on_error $0 "${?}" LINENO BASH_LINENO FUNCNAME BASH_COMMAND $FUNCNAME $BASH_LINENO $LINENO   $BASH_COMMAND'  ERR
  _debian_flavor_install
} # end _debian__32

_debian__64() {
  trap  '_trap_on_error $0 "${?}" LINENO BASH_LINENO FUNCNAME BASH_COMMAND $FUNCNAME $BASH_LINENO $LINENO   $BASH_COMMAND'  ERR
  _debian_flavor_install
} # end _debian__64

_fedora__32() {
  trap  '_trap_on_error $0 "${?}" LINENO BASH_LINENO FUNCNAME BASH_COMMAND $FUNCNAME $BASH_LINENO $LINENO   $BASH_COMMAND'  ERR
  _redhat_flavor_install
} # end _fedora__32

_fedora_37__64(){
  _redhat_flavor_install
} # end _fedora_37__64

_fedora_38__64(){
  _redhat_flavor_install
} # end _fedora_38__64

_fedora_39__64(){
  _redhat_flavor_install
} # end _fedora_39__64

_fedora_40__64(){
  _redhat_flavor_install
} # end _fedora_40__64

_fedora__64() {
  trap  '_trap_on_error $0 "${?}" LINENO BASH_LINENO FUNCNAME BASH_COMMAND $FUNCNAME $BASH_LINENO $LINENO   $BASH_COMMAND'  ERR
  _redhat_flavor_install
} # end _fedora__64

_gentoo__32() {
  trap  '_trap_on_error $0 "${?}" LINENO BASH_LINENO FUNCNAME BASH_COMMAND $FUNCNAME $BASH_LINENO $LINENO   $BASH_COMMAND'  ERR
  _redhat_flavor_install
} # end _gentoo__32

_gentoo__64() {
  trap  '_trap_on_error $0 "${?}" LINENO BASH_LINENO FUNCNAME BASH_COMMAND $FUNCNAME $BASH_LINENO $LINENO   $BASH_COMMAND'  ERR
  _redhat_flavor_install
} # end _gentoo__64

_madriva__32() {
  trap  '_trap_on_error $0 "${?}" LINENO BASH_LINENO FUNCNAME BASH_COMMAND $FUNCNAME $BASH_LINENO $LINENO   $BASH_COMMAND'  ERR
  _redhat_flavor_install
} # end _madriva__32

_madriva__64() {
  trap  '_trap_on_error $0 "${?}" LINENO BASH_LINENO FUNCNAME BASH_COMMAND $FUNCNAME $BASH_LINENO $LINENO   $BASH_COMMAND'  ERR
  _redhat_flavor_install
} # end _madriva__64

_suse__32() {
  trap  '_trap_on_error $0 "${?}" LINENO BASH_LINENO FUNCNAME BASH_COMMAND $FUNCNAME $BASH_LINENO $LINENO   $BASH_COMMAND'  ERR
  _redhat_flavor_install
} # end _suse__32

_suse__64() {
  trap  '_trap_on_error $0 "${?}" LINENO BASH_LINENO FUNCNAME BASH_COMMAND $FUNCNAME $BASH_LINENO $LINENO   $BASH_COMMAND'  ERR
  _redhat_flavor_install
} # end _suse__64

_ubuntu__32() {
  trap  '_trap_on_error $0 "${?}" LINENO BASH_LINENO FUNCNAME BASH_COMMAND $FUNCNAME $BASH_LINENO $LINENO   $BASH_COMMAND'  ERR
  _debian_flavor_install
} # end _ubuntu__32

_ubuntu__64() {
  trap  '_trap_on_error $0 "${?}" LINENO BASH_LINENO FUNCNAME BASH_COMMAND $FUNCNAME $BASH_LINENO $LINENO   $BASH_COMMAND'  ERR
  _debian_flavor_install
} # end _ubuntu__64

_ubuntu__aarch64() {
  trap  '_trap_on_error $0 "${?}" LINENO BASH_LINENO FUNCNAME BASH_COMMAND $FUNCNAME $BASH_LINENO $LINENO   $BASH_COMMAND'  ERR
  _debian_flavor_install
} # end _ubuntu__aarch64

_ubuntu_22__aarch64() {
  trap  '_trap_on_error $0 "${?}" LINENO BASH_LINENO FUNCNAME BASH_COMMAND $FUNCNAME $BASH_LINENO $LINENO   $BASH_COMMAND'  ERR
  _debian_flavor_install
} # end _ubuntu_22__aarch64

_darwin__64() {
  trap  '_trap_on_error $0 "${?}" LINENO BASH_LINENO FUNCNAME BASH_COMMAND $FUNCNAME $BASH_LINENO $LINENO   $BASH_COMMAND'  ERR
  enforce_variable_with_value USER_HOME "${USER_HOME}"
  Checking "if rust is installed by brew and attempting remove it"
  local -i _err=0
 	local _target_bin_brew=""
 	_target_bin_brew="$(_find_executable_for "brew" "--prefix"  "bin/brew")"   # tail -1
  _err=$?
  if [ $_err -gt 0 ] ; then # failed
  {
    echo "${_target_bin_brew}"
    failed "to find brew"
  }
  fi
  Checking "_target_bin_brew:<${_target_bin_brew}>"
  _target_bin_brew="$(echo "${_target_bin_brew}" | tail -1 | xargs)"
  ensure "${_target_bin_brew}" or "failed to check executable for brew <${_target_bin_brew}>"
  _target_bin_brew="$(echo -n "${_target_bin_brew}" | tail -1)"
	enforce_variable_with_value _target_bin_brew "${_target_bin_brew}"
  su - "${SUDO_USER}" -c "${_target_bin_brew} list --formula"
  if ( ! su - "${SUDO_USER}" -c "${_target_bin_brew} list rust" >/dev/null 2>&1; ); then
  {
	  passed "rust not found"
	}
  else
	{
		passed "rust found"
		if ( ! su - "${SUDO_USER}" -c "${_target_bin_brew} remove rust" >/dev/null 2>&1; ); then
    {
      warning "could not remove rust from brew"
    }
    else
    {
      passed "removed rust from brew"
    }
    fi
  }
	fi

  if (install_requirements "mac" "
      unzip
      curl
      wget
    "
    ); then
  {
      warning ": failed to install some deps "
  }
  fi
  verify_is_installed "
    unzip
    curl
    wget
    tar
  "
  Installing "_add_variables_to_bashrc_zshrc for ROOT and USER"
  _add_variables_to_bashrc_zshrc

  export ARCHFLAGS="-arch $(uname -m)"

  ARCHFLAGS="-arch $(uname -m)"
  Installing "ROOT install:ARCHFLAGS='-arch ${ARCHFLAGS-}' curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh"
  curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs > rustup.sh
  local cpwd=$(realpath .)
  local -i _err=0
  chmod +x "${cpwd}/rustup.sh"
  ARCHFLAGS='-arch ${ARCHFLAGS-}' "${cpwd}/rustup.sh" --no-modify-path --target /root --quiet -y
  _err=$?
  if [ ${_err} -gt 0 ] ; then
  {
    rm -rf "${cpwd}/rustup.sh"
    failed "Failed to install for root err:${_err}"
  }
  else
  {
    passed "install for root"
  }
  fi
  [[ ! -e "${USER_HOME}/.cargo" ]] && cp -R /root/.cargo "${USER_HOME}/.cargo"
  chmod -R 755 "${USER_HOME}/.cargo"
	chown -R "${SUDO_USER}"   "${USER_HOME}/.rustup"
  chown -R "${SUDO_USER}"   "${USER_HOME}/.cargo"
  chown -R "${SUDO_USER}"   "${USER_HOME}/.cargo/bin"
  chown -R "${SUDO_USER}"   "${USER_HOME}/.cargo/env"
  Installing "USER install(${USER_HOME}):su - \"${SUDO_USER}\" -c \"ARCHFLAGS='-arch $(uname -m)' curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh\""
  # if su - "${SUDO_USER}" -c "ARCHFLAGS='-arch $(uname -m)' curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh" ; then
  chown -R "${SUDO_USER}" "${cpwd}/rustup.sh"
  su - "${SUDO_USER}" -c "ARCHFLAGS='-arch $(uname -m)' "${cpwd}/rustup.sh" --no-modify-path --target /home/zeus --quiet -y"
  _err=$?
  if [ ${_err} -gt 0 ] ; then
  {
    rm -rf "${cpwd}/rustup.sh"
    failed "Failed to install for user err:${_err}"
  }
  else
  {
    passed "install for user"
  }
  fi
  rm -rf "${cpwd}/rustup.sh"
  Installing "_add_variables_to_bashrc_zshrc for ROOT and USER"
  _add_variables_to_bashrc_zshrc

	chown -R "${SUDO_USER}"   "${USER_HOME}/.rustup"
  chown -R "${SUDO_USER}"   "${USER_HOME}/.cargo"
  chown -R "${SUDO_USER}"   "${USER_HOME}/.cargo/bin"
  chown -R "${SUDO_USER}"   "${USER_HOME}/.cargo/env"

  Installing "ROOT: rustup default stable"
  rustup default stable
  Installing "USER: su - \"${SUDO_USER}\" -c \"rustup default stable\""
  su - "${SUDO_USER}" -c "rustup default stable"
	chown -R "${SUDO_USER}"   "${USER_HOME}/.rustup"
  chown -R "${SUDO_USER}"   "${USER_HOME}/.cargo"
  chown -R "${SUDO_USER}"   "${USER_HOME}/.cargo/bin"
  chown -R "${SUDO_USER}"   "${USER_HOME}/.cargo/env"


} # end _darwin__64

_darwin__arm64() {
  trap  '_trap_on_error $0 "${?}" LINENO BASH_LINENO FUNCNAME BASH_COMMAND $FUNCNAME $BASH_LINENO $LINENO   $BASH_COMMAND'  ERR
  enforce_variable_with_value USER_HOME "${USER_HOME}"
  Checking "if rust is installed by brew and attempting remove it"
  local -i _err=0
 	local _target_bin_brew=""
 	_target_bin_brew="$(_find_executable_for "brew" "--prefix"  "bin/brew")"   # tail -1
  _err=$?
  if [ $_err -gt 0 ] ; then # failed
  {
    echo "${_target_bin_brew}"
    failed "to find brew"
  }
  fi
  Checking "_target_bin_brew:<${_target_bin_brew}>"
  _target_bin_brew="$(echo "${_target_bin_brew}" | tail -1 | xargs)"
  ensure "${_target_bin_brew}" or "failed to check executable for brew <${_target_bin_brew}>"
  _target_bin_brew="$(echo -n "${_target_bin_brew}" | tail -1)"
	enforce_variable_with_value _target_bin_brew "${_target_bin_brew}"
  su - "${SUDO_USER}" -c "${_target_bin_brew} list --formula"
  if ( ! su - "${SUDO_USER}" -c "${_target_bin_brew} list rust" >/dev/null 2>&1; ); then
  {
	  passed "rust not found"
	}
  else
	{
		passed "rust found"
		if ( ! su - "${SUDO_USER}" -c "${_target_bin_brew} remove rust" >/dev/null 2>&1; ); then
    {
      warning "could not remove rust from brew"
    }
    else
    {
      passed "removed rust from brew"
    }
    fi
  }
	fi

  if (install_requirements "mac" "
      unzip
      curl
      wget
    "
    ); then
  {
      warning ": failed to install some deps "
  }
  fi
  verify_is_installed "
    unzip
    curl
    wget
    tar
  "
  Installing "_add_variables_to_bashrc_zshrc for ROOT and USER"
  _add_variables_to_bashrc_zshrc

  export ARCHFLAGS="-arch $(uname -m)"

  ARCHFLAGS="-arch $(uname -m)"
  Installing "ROOT install:ARCHFLAGS='-arch ${ARCHFLAGS-}' curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh"
  curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs > rustup.sh
  local cpwd=$(realpath .)
  local -i _err=0
  chmod +x "${cpwd}/rustup.sh"
  ARCHFLAGS='-arch ${ARCHFLAGS-}' "${cpwd}/rustup.sh" --no-modify-path --target /root --quiet -y
  _err=$?
  if [ ${_err} -gt 0 ] ; then
  {
    rm -rf "${cpwd}/rustup.sh"
    failed "Failed to install for root err:${_err}"
  }
  else
  {
    passed "install for root"
  }
  fi
  [[ ! -e "${USER_HOME}/.cargo" ]] && cp -R /root/.cargo "${USER_HOME}/.cargo"
  chmod -R 755 "${USER_HOME}/.cargo"
	chown -R "${SUDO_USER}"   "${USER_HOME}/.rustup"
  chown -R "${SUDO_USER}"   "${USER_HOME}/.cargo"
  chown -R "${SUDO_USER}"   "${USER_HOME}/.cargo/bin"
  chown -R "${SUDO_USER}"   "${USER_HOME}/.cargo/env"
  Installing "USER install(${USER_HOME}):su - \"${SUDO_USER}\" -c \"ARCHFLAGS='-arch $(uname -m)' curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh\""
  # if su - "${SUDO_USER}" -c "ARCHFLAGS='-arch $(uname -m)' curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh" ; then
  chown -R "${SUDO_USER}" "${cpwd}/rustup.sh"
  su - "${SUDO_USER}" -c "ARCHFLAGS='-arch $(uname -m)' "${cpwd}/rustup.sh" --no-modify-path --target /home/zeus --quiet -y"
  _err=$?
  if [ ${_err} -gt 0 ] ; then
  {
    rm -rf "${cpwd}/rustup.sh"
    failed "Failed to install for user err:${_err}"
  }
  else
  {
    passed "install for user"
  }
  fi
  rm -rf "${cpwd}/rustup.sh"
  Installing "_add_variables_to_bashrc_zshrc for ROOT and USER"
  _add_variables_to_bashrc_zshrc

	chown -R "${SUDO_USER}"   "${USER_HOME}/.rustup"
  chown -R "${SUDO_USER}"   "${USER_HOME}/.cargo"
  chown -R "${SUDO_USER}"   "${USER_HOME}/.cargo/bin"
  chown -R "${SUDO_USER}"   "${USER_HOME}/.cargo/env"

  Installing "ROOT: rustup default stable"
  rustup default stable
  Installing "USER: su - \"${SUDO_USER}\" -c \"rustup default stable\""
  su - "${SUDO_USER}" -c "rustup default stable"
	chown -R "${SUDO_USER}"   "${USER_HOME}/.rustup"
  chown -R "${SUDO_USER}"   "${USER_HOME}/.cargo"
  chown -R "${SUDO_USER}"   "${USER_HOME}/.cargo/bin"
  chown -R "${SUDO_USER}"   "${USER_HOME}/.cargo/env"



} # end _darwin__arm64

_tar() {
  trap  '_trap_on_error $0 "${?}" LINENO BASH_LINENO FUNCNAME BASH_COMMAND $FUNCNAME $BASH_LINENO $LINENO   $BASH_COMMAND'  ERR
} # end tar

_windows__64() {
  trap  '_trap_on_error $0 "${?}" LINENO BASH_LINENO FUNCNAME BASH_COMMAND $FUNCNAME $BASH_LINENO $LINENO   $BASH_COMMAND'  ERR
  export ARCHFLAGS="-arch $(uname -m)"
  ARCHFLAGS="-arch $(uname -m)" curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
  su - "${SUDO_USER}" -c "ARCHFLAGS='-arch $(uname -m)' curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh"
} # end _windows__64

_windows__32() {
  trap  '_trap_on_error $0 "${?}" LINENO BASH_LINENO FUNCNAME BASH_COMMAND $FUNCNAME $BASH_LINENO $LINENO   $BASH_COMMAND'  ERR
  echo "_windows__32 Procedure not yet implemented. I don't know what to do."
} # end _windows__32
