#!/usr/bin/env bash
#
# @author Zeus Intuivo <zeus@intuivo.com>
#


PROJECT_DIR_F=""  # GLOBAL
set -E -o functrace

_find_project_location_PROJECT_DIR_F() {
  local _target_project=""
  Checking "location of project "
  local _list_posssibles="
    ${USER_HOME}/_/work/agrivero/projects
    ${USER_HOME}/_/work/agriveo
    /repo/work/agrivero/projects
  "
  local one=""
  while read -r one ; do
  {
    [[ -z "${one}" ]] && continue
    if it_exists_with_spaces "${one}" ; then
    {
     _target_project="${one}"
     break
    }
    fi
  }
  done <<< "${_list_posssibles}"
  [[ -z "${one}" ]] && warning "Could not find/determine location of project" && return 1
  passed "found of project dir ${_target_project}"
  PROJECT_DIR_F="${_target_project}"
  return 0
} # end _find_project_location_PROJECT_DIR_F

_step1_apt_installs() {

  trap 'echo -e "${RED}" && echo "ERROR err:$_err failed $0:$LINENO _debian_flavor_install agri_pd" && echo -e "${RESET}" && return 0' ERR
  # Batch 1 18.04
  apt update -y
  local package packages="
    autoconf
    bison
    build-essential
    libssl-dev
    libyaml-dev
    # libreadline6-dev
    zlib1g-dev
    libncurses5-dev
    libffi-dev
    make
    libbz2-dev
    libreadline-dev
    libsqlite3-dev
    wget
    curl
    llvm
    libncursesw5-dev
    xz-utils
    tk-dev
    libxml2-dev
    libxmlsec1-dev
		libffi-dev
    liblzma-dev
  "
  _package_list_installer "${packages}"
  # Batch 2 20.04
  local package packages="
    gcc
    libssl-dev
    libsensors-dev
    clang
    autoconf
    bison
    build-essential
    libssl-dev
    libyaml-dev
    # libreadline6-dev
    zlib1g-dev
    libncurses5-dev
    libffi-dev
  "
  if _package_list_installer "${packages}"; then
  {
    echo "Installer returned $?"
  }
  fi


} # end _step1_apt_installs

_step2_vimba_kernel_drivers() {
  local _topic="Vimba camera drivers"
  Installing "${_topic}"
  if _msg="$(__download_file_check_checksum .camera_driver_vimba "https://developer.files.com/VimbaX_Setup-2023-4-Linux64.tar.gz" "daa552b0b116c19c8d4d784a740bd630033e6eedc334f6361d114a9ce05e2bde" 2>&1)" ; then  # capture all sdout stdout input and output  sderr stderr
  {
    _err=0
	}
  else
	{
		_err=2
	}
	fi
  if [ ${_err} -gt 0 ] ; then
  {
    failed "\n +----     while running ${_topic}  __download_file_check_checksum() above _msg: ''' \n${_msg} \n '''\n  _err:${_err} ------+ \n "
  }
  fi
  if ( command -v nvidia-smi >/dev/null 2>&1; )  ; then
  {
    nvidia-smi
  }
  fi

  echo "ref: https://docs.alliedvision.com/Vimba_X/Vimba_X_DeveloperGuide/settings.html#linux-and-arm"
  Installing "Increasing the USBFS buffer size:"
  mkdir -p /sys/module/usbcore/parameters/
  touch /sys/module/usbcore/parameters/usbfs_memory_mb
  cat /sys/module/usbcore/parameters/usbfs_memory_mb
  sudo sh -c 'echo 1000 > /sys/module/usbcore/parameters/usbfs_memory_mb'
  cat /sys/module/usbcore/parameters/usbfs_memory_mb

  Installing "Increasing the OS receive buffer size:"
  sysctl -w net.core.rmem_max=33554432
  sysctl -w net.core.wmem_max=33554432
  sysctl -w net.core.rmem_default=33554432
  sysctl -w net.core.wmem_default=33554432

  Installing "Kernel update for nvdia jetson Vimba X ref: https://github.com/alliedvision/linux_nvidia_jetson/releases"
  file_exists_with_spaces   "${USER_HOME}/Downloads/AlliedVision_NVidia_L4T_35.4.1_5.1.2.gcf4fa7ea0.tar.gz"
  mkdir -p "${USER_HOME}/Downloads/AlliedVisionDriver"
  cd "${USER_HOME}/Downloads/AlliedVisionDriver"
  cp "${USER_HOME}/Downloads/AlliedVision_NVidia_L4T_35.4.1_5.1.2.gcf4fa7ea0.tar.gz"  "${USER_HOME}/Downloads/AlliedVisionDriver"
  tar -xvf   AlliedVision_NVidia_L4T_35.4.1_5.1.2.gcf4fa7ea0.tar.gz

  Installing "Execute install script inside   ./install.sh "
  Installing "Execute install script inside   ./install.sh "
  Installing "Execute install script inside   ./install.sh "
  Installing "Execute install script inside   ./install.sh "
  Installing "Execute install script inside   ./install.sh "
  Installing "Execute install script inside   ./install.sh "
  Installing "Execute install script inside   ./install.sh "
  Installing "Execute install script inside   ./install.sh "
  Installing "Execute install script inside   ./install.sh "
  # tar -czf folder . # perform backup
  # mkdir -p folder && cd folder && tar -xzf VimbaX_Setup-2023-4-Linux_ARM64.tar.gz # perform restore
} # end _step2_vimba_kernel_drivers

_step3_processing_data() {
  Checking "needs .ssh setup before using git@git  have added .ssh keys  yet ?  sshgenerate key ?? "
  Checking "needs .ssh setup before using git@git  have added .ssh keys  yet ?  sshgenerate key ?? "
  Checking "needs .ssh setup before using git@git  have added .ssh keys  yet ?  sshgenerate key ?? "
  Checking "needs .ssh setup before using git@git  have added .ssh keys  yet ?  sshgenerate key ?? "
  Checking "needs .ssh setup before using git@git  have added .ssh keys  yet ?  sshgenerate key ?? "

  file_exists_with_spaces "${USER_HOME}/.ssh/id_rsa.pub"

  cd "${PROJECTSBASEDIR}"
  _git_clone "${PROJECTGITREPO}" "${PROJECTREPO}" "${PROJECTGITREPOBRANCH}"
  directory_exists_with_spaces "${PROJECTREPO}"

  cd "${PROJECTREPO}"
	mkdir -p cam_capture/images
	chown -R "${SUDO_USER}"  "${PROJECTREPO}"

	_execute_project_command "${PROJECTREPO}" "pip install pipenv"
  # brew install pipenv  # <- takes very long but it could be an alternative
  _execute_project_command "${PROJECTREPO}" "pipenv install"

  Installing "Torch Package from Jetpack 6 / PyTorch v2.1"
  Checking "curl https://forums.developer.nvidia.com/t/pytorch-for-jetson/72048"

} # end _step3_processing_data


_execute_project_command() {
  # Sample usage:
  #   _execute_project_command "${PROJECTREPO}" "bundle exec rake db:migrate db:migrate:emails db:migrate:credit_check "
  #   _execute_project_command "${PWD}" sdkmanager --cli
  #
  trap  '_trap_on_error $0 "${?}" LINENO BASH_LINENO FUNCNAME BASH_COMMAND $FUNCNAME $BASH_LINENO $LINENO   $BASH_COMMAND'  ERR
  local PROJECTREPO=${1}
  enforce_parameter_with_value           1        PROJECTREPO      "${PROJECTREPO}"     "path folder where Gemfile or project is located "
  local _command=${2}
  enforce_parameter_with_value           2        _command         "${_command}"        "bash command to run"
  local _parameters="${*:3}"  # grab all parameters after second
  # _command="$(sed 's/["]/\\\"/g' <<< "${_command}")"
  echo "_command:${_command}"
  su - "${SUDO_USER}" -c  "bash -c 'cd "${PROJECTREPO}" && ${_command} ${_parameters} '"
} # end _execute_project_command

check_run_command_as_root() {
  # Sample usage:
  #  check_run_command_as_root
  #
  [[ "${EUID:-${UID}}" == "0" ]] || return

  # Allow Azure Pipelines/GitHub Actions/Docker/Concourse/Kubernetes to do everything as root (as it's normal there)
  [[ -f /.dockerenv ]] && return
  [[ -f /proc/1/cgroup ]] && grep -E "azpl_job|actions_job|docker|garden|kubepods" -q /proc/1/cgroup && return

  failed "Don't run this as root!"
}

__download_file_check_checksum() {
  # Sample usage:
  #    __download_file_check_checksum .torch_22_jetson_6_python_3_10 "https://developer.download.nvidia.cn/compute/redist/jp/v60dp/pytorch/torch-2.2.0a0+6a974be.nv23.11-cp310-cp310-linux_aarch64.whl" 94e70c4f45211737174a3c0f0b791b479c5fd9a2955ba77f573d31c0273e485e
  local -i _err=0
  local file_url_configuration="${1}"
        enforce_parameter_with_value           1        file_url_configuration      "${file_url_configuration}"     ".trained_model .torch_22_jetson_6_python_3_10 full path filename "
        if [[ ! -e "${file_url_configuration}" ]] ; then
        {
          failed "file_url_configuration=file:${file_url_configuration}  does not exists"
        }
        fi
  local sample_url_download="${2}"
        enforce_parameter_with_value           2       sample_url_download         "${sample_url_download}"     "https://developer.download.nvidia.cn/compute/redist/jp/v60dp/pytorch/torch-2.2.0a0+6a974be.nv23.11-cp310-cp310-linux_aarch64.whl"
  local hash_check_sum_to_check_against="${3}"
        enforce_parameter_with_value           3       hash_check_sum_to_check_against "${hash_check_sum_to_check_against}"    "94e70c4f45211737174a3c0f0b791b479c5fd9a2955ba77f573d31c0273e48"

  local service_url="$(<"${file_url_configuration}")"
        enforce_parameter_with_value           1        service_url      "${service_url}"    "${sample_url_download}"
        enforce_variable_with_value service_url  "${service_url}"
  local filename=$(basename "${service_url}")
        if [[ -e  "${filename}" ]] ; then
        {
          passed "Already downloaded: ${filename}"
        }
        else
        {
          ensure curl or "curl is needed to connect to download stuff - Cannot continue"
          local passwords="$(<.env)"
                enforce_parameter_with_value           2        passwords      "${passwords}"     "--proxy-user user:password --user user:password"
                enforce_variable_with_value service_url  "${passwords}"

          Intalling "Calling curl to sevice url: curl $passwords -k $service_url"
          curl $passwords -k $service_url
          _err=$?
          if [ ${_err} -gt 0 ] ; then
          {
            failed "while running curl above: curl  $passwords -k $service_url > \"${filename}\""
          }
          fi
        }
        fi

  Checking "checksum for ${filename}"
  file_exists_with_spaces "${filename}"
  local checksum=""
  checksum=$(sha256sum "${filename}" | cut -d' ' -f1)
  _err=$?
  if [ ${_err} -gt 0 ] ; then
  {
    failed "while running checksum above: sha256sum \"${filename}\""
  }
  fi
  if [[ "${checksum}" == "${hash_check_sum_to_check_against}" ]] ; then
  {
    passed "Checksum checks ${checksum}"
  }
  else
  {
    rm -rf ${filename}
    failed "removed file ${filename} Checksum DOES NOT check
		     GOT:${checksum}
		EXPECTED:${hash_check_sum_to_check_against}
	 	Try again to download again"
  }
  fi
} # end __download_file_check_checksum

_package_list_installer() {
  # trap  '_trap_on_error $0 "${?}" LINENO BASH_LINENO FUNCNAME BASH_COMMAND $FUNCNAME $BASH_LINENO $LINENO   $BASH_COMMAND'  ERR
  local package packages="${@}"
  trap 'echo -e "${RED}" && echo "ERROR failed $0:$LINENO _package_list_installer agri_pd" && echo -e "${RESET}" && return 0' ERR

  if ! install_requirements "linux" "${packages}" ; then
  {
    warning "installing requirements. ${CYAN} attempting to install one by one"
    while read package; do
    {
      [ -z ${package} ] && continue
      if ! install_requirements "linux" "${package}" ; then
      {
        _err=$?
        if [ ${_err} -gt 0 ] ; then
        {
          echo -e "${RED}"
          echo failed to install requirements "${package}"
          echo -e "${RESET}"
        }
        fi
      }
      fi
    }
    done <<< "${packages}"
  }
  fi
} # end _package_list_installer

_git_clone() {
  # Sample usage
  # _git_clone git@github.com:some-ai/processing_data.git  "$HOME"
  # _git_clone git@github.com:another-ai/processing_data.git  "$HOME" "i_experiment_branch"
  #
  trap  '_trap_on_error $0 "${?}" LINENO BASH_LINENO FUNCNAME BASH_COMMAND $FUNCNAME $BASH_LINENO $LINENO   $BASH_COMMAND'  ERR
  trap 'echo -e "${RED}" && echo "ERROR failed $0:$LINENO  _git_clone I3STATUS" && echo -e "${RESET}" && return 0' ERR
  local _source="${1-}"
  local _target="${2-}"
  local _branch="${3-}"
  Checking "${SUDO_USER} git clone ${_source}  ${_target}  --branch ${_branch} "
  pwd
  if  it_exists_with_spaces "${_target}" ; then # && it_exists_with_spaces "${_target}/.git" ; then
  {
    if it_exists_with_spaces "${_target}/.git" ; then
    {
      if ! cd "${_target}" ; then
      {
        warning Could not CD into "${_target}. There seems to be a problem"
        return 1
      }
      fi
      if [[ -n "${_branch}" ]] ; then
      {
        if ! git checkout "${_branch}" ; then
        {
          warning Could could not checkout such branch: "${_branch}"
          return 1
        }
        fi
      }
      fi
      if git config pull.rebase false ; then
      {
        warning Could not git config pull.rebase false
      }
      fi
      if git fetch  ; then
      {
        warning Could not git fetch
      }
      fi
      if git pull  ; then
      {
        warning Could not git pull
      }
      fi
    }
    fi
  }
  else
  {
    if git clone "${_source}" "${_target}"  ; then
    {
      warning Could not git clone "${_source}" "${_target}"
    }
    fi
      if ! cd "${_target}" ; then
      {
        warning Could not CD into "${_target}. There seems to be a problem. Clone failed!!!"
        return 1
      }
      fi
      if [[ -n "${_branch}" ]] ; then
      {
        if ! git checkout "${_branch}" ; then
        {
          warning Could could not checkout such branch: "${_branch}"
          return 1
        }
        fi
      }
      fi
      if git config pull.rebase false ; then
      {
        warning Could not git config pull.rebase false
      }
      fi
  }
  fi
  chown -R "${SUDO_USER}" "${_target}"

} # end _git_clone



_add_variables_to_bashrc_zshrc(){
  local XDG_DATA_HOME="${XDG_DATA_HOME:-${USER_HOME}/.local/share}"
  Checking "mkdir -p \"${XDG_DATA_HOME}/agri_pd-rust\""
  mkdir -p "${XDG_DATA_HOME}/agri_pd-rust"

  directory_exists_with_spaces "${XDG_DATA_HOME}/agri_pd-rust"
  directory_exists_with_spaces "${USER_HOME}/.agri_pd-rs"

  if [[ ! -e "${XDG_DATA_HOME}/agri_pd-rust/config.toml" ]] ; then
  {
    cp "${USER_HOME}/.agri_pd-rs/examples/config.toml" "${XDG_DATA_HOME}/agri_pd-rust/config.toml"
  }
  fi


  export XDG_DATA_HOME="${XDG_DATA_HOME}"
  cd "${USER_HOME}/.agri_pd-rs/"
  su - "${SUDO_USER}" -c 'cd '${USER_HOME}'/.agri_pd-rs/ && cargo build'
  su - "${SUDO_USER}" -c 'cd '${USER_HOME}'/.agri_pd-rs/ && cargo xtask generate-manpage'
  su - "${SUDO_USER}" -c 'cd '${USER_HOME}'/.agri_pd-rs/ && cargo install --path . --locked'
  cp -R "${USER_HOME}/.agri_pd-rs/files/"* "${XDG_DATA_HOME}/agri_pd-rust/"
  mkdir -p "${XDG_DATA_HOME}/man/man1/"
  directory_exists_with_spaces "${XDG_DATA_HOME}/man/man1/"

  cp "${USER_HOME}/.agri_pd-rs/man/agri_pd-rs.1" "${XDG_DATA_HOME}/man/man1/agri_pd-rs.1"
  local AGRI_PD_SH_CONTENT='

# AGRI_PD
if [[ -e "'${XDG_DATA_HOME}'" ]] ; then
{
  export XDG_DATA_HOME="'${XDG_DATA_HOME}'"
}
fi
'
  cd "${USER_HOME}"
  trap 'echo -e "${RED}" && echo "ERROR failed $0:$LINENO _add_variables_to_bashrc_zshrc agri_pd" && echo -e "${RESET}" && return 0' ERR
  Checking "${AGRI_PD_SH_CONTENT}"
  local INITFILE INITFILES="
   .bashrc
   .zshrc
   .bash_profile
   .profile
   .zshenv
   .zprofile
  "
  while read INITFILE; do
  {
    [ -z ${INITFILE} ] && continue
    Checking "${USER_HOME}/${INITFILE}"
    _if_not_contains "${USER_HOME}/${INITFILE}"  "# AGRI_PD" ||  echo "${AGRI_PD_SH_CONTENT}" >> "${USER_HOME}/${INITFILE}"
  }
  done <<< "${INITFILES}"
  # type agri_pd
  Checking "export XDG_DATA_HOME=${XDG_DATA_HOME}"

  chown -R "${SUDO_USER}" "${XDG_DATA_HOME}/agri_pd-rust"
  chown -R "${SUDO_USER}" "${USER_HOME}/.agri_pd-rs"
  chown -R "${SUDO_USER}" "${XDG_DATA_HOME}/man/man1/"
  echo "check configs:"
  echo ${INITFILES} | xargs | xargs -I {} echo "vim {}"
  echo " "
} # _add_variables_to_bashrc_zshrc

PROJECTSBASEDIR="${PROJECT_DIR_F-}" # global
PROJECTREPO="${PROJECT_DIR_F-}/processing_data" #  global
PROJECTGITREPO="git@github.com:agrivero-ai/processing_data.git" # global
PROJECTGITREPOBRANCH="will_experiments" # global

_debian_flavor_install() {
  trap  '_trap_on_error $0 "${?}" LINENO BASH_LINENO FUNCNAME BASH_COMMAND $FUNCNAME $BASH_LINENO $LINENO   $BASH_COMMAND'  ERR
  local -i _err=0
  if _find_project_location_PROJECT_DIR_F ; then
	{
    _err=0
	}
  else 
	{
		_err=2
	}
	fi
	echo _err:$_err
  if [ ${_err} -gt 0 ] ; then
  {
    warning "could not find  project folder. Making one.. _err:${_err}"
    mkdir -p "${USER_HOME}/_/work/agrivero/projects"
		chown -R "${SUDO_USER}" "${USER_HOME}/_/work"
    PROJECT_DIR_F="${USER_HOME}/_/work/agrivero/projects"
    cd "${USER_HOME}/_/work/agrivero/projects"
   }
  fi
  PROJECTSBASEDIR="${PROJECT_DIR_F}"
  PROJECTREPO="${PROJECT_DIR_F}/processing_data"
  PROJECTGITREPO="git@github.com:agrivero-ai/processing_data.git"
  PROJECTGITREPOBRANCH="will_experiments"
	local -i _err=0
  local _step=step1_apt_installs
  local _all_steps="
	  step1_apt_installs 
		step2_vimba_kernel_drivers
    step3_processing_data
		step4_processing_data
	"
	local _touch_name=""
	local _function_to_call=""
  while read -r _step ; do 
	{
		[[ -z "${_step}" ]] && continue
    [[ -f "${PROJECT_DIR_F}/.${_step}"  ]] && continue # skip if file exists == step done
    _function_to_call="_${_step}"
  	Working "Step .${_step}"
		if function_is_defined "${_function_to_call}" ; then
    {
      passed "function defined ${_function_to_call}"
      ${_function_to_call} # : command not found <-- could be triggered here also 
      # _assure_success
      _err=$?
      if [ ${_err} -gt 0 ] ; then
      {
        failed "while running ${_step} above _err:${_err}"
      }
      fi
      _touch_name="\"${PROJECT_DIR_F}/.${_step}\""
      _execute_project_command "${PROJECT_DIR_F}" "touch ${_touch_name} "
    }
    else
    {

			Checking "Failed $0:$LINENO funtion:${_function_to_call} for step:${_step}"
			Installing "it would look this:

${_function_to_call}() {
  trap \"echo Error:\$\?\" ERR INT
  local _parameters=\"\${*-}\"
  local -i _err=0
  callsomething \"\${_parameters-}\"
  _err=\$\?
  if [ \${_err} -gt 0 ] ; then
  {
    warning \"while running callsomething above _err:\${_err}\"
    return 1
 	}
  fi
	return 0
} # end ${_function_to_call}

"
			failed "$0:$LINENO funtion:${_function_to_call} for step:${_step}"
    }
		fi

	}
  done <<< "$(echo "${_all_steps}" | grep -vE '^#' | grep -vE '^\\s+#')"

} # end _debian_flavor_install

_redhat_flavor_install() {
  trap  '_trap_on_error $0 "${?}" LINENO BASH_LINENO FUNCNAME BASH_COMMAND $FUNCNAME $BASH_LINENO $LINENO   $BASH_COMMAND'  ERR
  dnf build-dep agri_pd -vy --allowerasing
  yes | dnf copr enable atim/agri_pd-rust
  dnf install agri_pd-rust -y --allowerasing
  # dnf install  -y openssl-devel
  # Batch Fedora 37
  local package packages="
    libyaml
    libyaml-devel
    autoconf
    bison
    bison-devel
    # ruby-build-agri_pd
    openssl1.1
    # openssl1.1-devel-1
    ncurses
    ncurses-devel
    ncurses-c++-libs
    ncurses-compat-libs
    ncurses-libs
    ncurses-static
    ncurses-base
    # ncurses-term conflicts with foot-terminfo
    readline
    readline-static
    readline-devel
    compat-readline5
    compat-readline5-devel
    compat-readline6
    compat-readline6-devel
    zlib
    zlib-devel
    zlibrary-devel
    zlibrary
    libffi
    libffi-devel
    libffi3.1
    # compat-gdbm
    # compat-gdbm-devel
    # compat-gdbm-libs
    gdbm
    gdbm-devel
    gdbm-libs
  "
  _package_list_installer "${packages}"

  local package packages="
    gcc
    openssl-devel
    lm_sensors-devel
    qt5-qtsensors-devel
    qt6-qtsensors-devel
    gvncpulse-devel
    rust-pulse-devel
    notmuch-devel
    pipewire-devel
    rust-pipewire-devel
    pipewire
    pipewire-alsa
    pipewire-gstreamer
    pipewire-libs
    # pipewire-media-session
    pipewire-pulseaudio
    pipewire-utils
    easyeffects
    helvum
    qpwgraph
    # wireplumber
    clang
    notmuch
    pandoc
  "
  if _package_list_installer "${packages}"; then
  {
    echo "Installer returned $?"
  }
  fi
  # ensure brew or "Canceling until brew is installed. try install_brew.bash install_brew.sh"
  # su - "${SUDO_USER}" -c 'brew install readline'
  # su - "${SUDO_USER}" -c 'brew install openssl@1.1'
  _git_clone "https://github.com/greshake/agri_pd-rust.git" "${USER_HOME}/.agri_pd-rs"

  _add_variables_to_bashrc_zshrc
  # ensure agri_pd or "Canceling until agri_pd did not install"
  # su - "${SUDO_USER}" -c 'agri_pd install -l'
  # su - "${SUDO_USER}" -c 'agri_pd rehash'
  ensure agri_pd-rs  or "Canceling until agri_pd-rs  is not working"
  # su - "${SUDO_USER}" -c 'ruby -v'
} # end _redhat_flavor_install

_arch_flavor_install() {
  trap  '_trap_on_error $0 "${?}" LINENO BASH_LINENO FUNCNAME BASH_COMMAND $FUNCNAME $BASH_LINENO $LINENO   $BASH_COMMAND'  ERR
  echo "Procedure not yet implemented. I don't know what to do."
} # end _readhat_flavor_install

_arch__32() {
  trap  '_trap_on_error $0 "${?}" LINENO BASH_LINENO FUNCNAME BASH_COMMAND $FUNCNAME $BASH_LINENO $LINENO   $BASH_COMMAND'  ERR
  _arch_flavor_install
} # end _arch__32

_arch__64() {
  trap  '_trap_on_error $0 "${?}" LINENO BASH_LINENO FUNCNAME BASH_COMMAND $FUNCNAME $BASH_LINENO $LINENO   $BASH_COMMAND'  ERR
  _arch_flavor_install
} # end _arch__64

_centos__32() {
  trap  '_trap_on_error $0 "${?}" LINENO BASH_LINENO FUNCNAME BASH_COMMAND $FUNCNAME $BASH_LINENO $LINENO   $BASH_COMMAND'  ERR
  _redhat_flavor_install
} # end _centos__32

_centos__64() {
  trap  '_trap_on_error $0 "${?}" LINENO BASH_LINENO FUNCNAME BASH_COMMAND $FUNCNAME $BASH_LINENO $LINENO   $BASH_COMMAND'  ERR
  _redhat_flavor_install
} # end _centos__64

_debian__32() {
  trap  '_trap_on_error $0 "${?}" LINENO BASH_LINENO FUNCNAME BASH_COMMAND $FUNCNAME $BASH_LINENO $LINENO   $BASH_COMMAND'  ERR
  _debian_flavor_install
} # end _debian__32

_debian__64() {
  trap  '_trap_on_error $0 "${?}" LINENO BASH_LINENO FUNCNAME BASH_COMMAND $FUNCNAME $BASH_LINENO $LINENO   $BASH_COMMAND'  ERR
  _debian_flavor_install
} # end _debian__64

_fedora__32() {
  trap  '_trap_on_error $0 "${?}" LINENO BASH_LINENO FUNCNAME BASH_COMMAND $FUNCNAME $BASH_LINENO $LINENO   $BASH_COMMAND'  ERR
  _redhat_flavor_install
} # end _fedora__32

_fedora__64() {
  trap  '_trap_on_error $0 "${?}" LINENO BASH_LINENO FUNCNAME BASH_COMMAND $FUNCNAME $BASH_LINENO $LINENO   $BASH_COMMAND'  ERR
  local _parameters="${*-}"
  _redhat_flavor_install "${_parameters-}"
} # end _fedora__64

_fedora_37__64(){
  # trap "echo Error:$?" ERR INT
  trap  '_trap_on_error $0 "${?}" LINENO BASH_LINENO FUNCNAME BASH_COMMAND $FUNCNAME $BASH_LINENO $LINENO   $BASH_COMMAND'  ERR
  local _parameters="${*-}"
  local -i _err=0
  _redhat_flavor_install "${_parameters-}"
} # end _fedora_37__64

_fedora_39__64(){
  # trap "echo Error:$?" ERR INT
  trap  '_trap_on_error $0 "${?}" LINENO BASH_LINENO FUNCNAME BASH_COMMAND $FUNCNAME $BASH_LINENO $LINENO   $BASH_COMMAND'  ERR
  local _parameters="${*-}"
  local -i _err=0
  _redhat_flavor_install "${_parameters-}"
} # end _fedora_39__64

_gentoo__32() {
  trap  '_trap_on_error $0 "${?}" LINENO BASH_LINENO FUNCNAME BASH_COMMAND $FUNCNAME $BASH_LINENO $LINENO   $BASH_COMMAND'  ERR
  _redhat_flavor_install
} # end _gentoo__32

_gentoo__64() {
  trap  '_trap_on_error $0 "${?}" LINENO BASH_LINENO FUNCNAME BASH_COMMAND $FUNCNAME $BASH_LINENO $LINENO   $BASH_COMMAND'  ERR
  _redhat_flavor_install
} # end _gentoo__64

_madriva__32() {
  trap  '_trap_on_error $0 "${?}" LINENO BASH_LINENO FUNCNAME BASH_COMMAND $FUNCNAME $BASH_LINENO $LINENO   $BASH_COMMAND'  ERR
  _redhat_flavor_install
} # end _madriva__32

_madriva__64() {
  trap  '_trap_on_error $0 "${?}" LINENO BASH_LINENO FUNCNAME BASH_COMMAND $FUNCNAME $BASH_LINENO $LINENO   $BASH_COMMAND'  ERR
  _redhat_flavor_install
} # end _madriva__64

_suse__32() {
  trap  '_trap_on_error $0 "${?}" LINENO BASH_LINENO FUNCNAME BASH_COMMAND $FUNCNAME $BASH_LINENO $LINENO   $BASH_COMMAND'  ERR
  _redhat_flavor_install
} # end _suse__32

_suse__64() {
  trap  '_trap_on_error $0 "${?}" LINENO BASH_LINENO FUNCNAME BASH_COMMAND $FUNCNAME $BASH_LINENO $LINENO   $BASH_COMMAND'  ERR
  _redhat_flavor_install
} # end _suse__64

_ubuntu__32() {
  trap  '_trap_on_error $0 "${?}" LINENO BASH_LINENO FUNCNAME BASH_COMMAND $FUNCNAME $BASH_LINENO $LINENO   $BASH_COMMAND'  ERR
  _debian_flavor_install
} # end _ubuntu__32

_ubuntu__64() {
  trap  '_trap_on_error $0 "${?}" LINENO BASH_LINENO FUNCNAME BASH_COMMAND $FUNCNAME $BASH_LINENO $LINENO   $BASH_COMMAND'  ERR
  _debian_flavor_install
} # end _ubuntu__64

_ubuntu__aarch64() {
  trap  '_trap_on_error $0 "${?}" LINENO BASH_LINENO FUNCNAME BASH_COMMAND $FUNCNAME $BASH_LINENO $LINENO   $BASH_COMMAND'  ERR
  _debian_flavor_install
} # end _ubuntu__aarch64

_ubuntu_22__aarch64() {
  trap  '_trap_on_error $0 "${?}" LINENO BASH_LINENO FUNCNAME BASH_COMMAND $FUNCNAME $BASH_LINENO $LINENO   $BASH_COMMAND'  ERR
  _debian_flavor_install
} # end _ubuntu_22__aarch64


_darwin__64() {
  trap  '_trap_on_error $0 "${?}" LINENO BASH_LINENO FUNCNAME BASH_COMMAND $FUNCNAME $BASH_LINENO $LINENO   $BASH_COMMAND'  ERR
  export HOMEBREW_NO_AUTO_UPDATE=1
  ensure brew or "Canceling until brew is installed"
  su - "${SUDO_USER}" -c 'brew install ruby-build'
  _git_clone "https://github.com/agri_pd/agri_pd.git" "${USER_HOME}/.agri_pd"
  _git_clone "https://github.com/agri_pd/ruby-build.git" "${USER_HOME}/.agri_pd/plugins/ruby-build"
  _add_variables_to_bashrc_zshrc
  ensure "${USER_HOME}/.agri_pd/bin/agri_pd" or "Canceling until agri_pd did not install"
  su - "${SUDO_USER}" -c "git -C ${USER_HOME}/.agri_pd/plugins/ruby-build pull"
  su - "${SUDO_USER}" -c "${USER_HOME}/.agri_pd/bin/agri_pd install -l"
  su - "${SUDO_USER}" -c "${USER_HOME}/.agri_pd/bin/agri_pd install 2.6.5"
  su - "${SUDO_USER}" -c "${USER_HOME}/.agri_pd/bin/agri_pd install 2.7.3"
  su - "${SUDO_USER}" -c "${USER_HOME}/.agri_pd/bin/agri_pd install 3.2.2"
  su - "${SUDO_USER}" -c "${USER_HOME}/.agri_pd/bin/agri_pd global 2.7.3"
  su - "${SUDO_USER}" -c "${USER_HOME}/.agri_pd/bin/agri_pd rehash"
  ensure ruby or "Canceling until ruby is not working"
  su - "${SUDO_USER}" -c 'ruby -v'
} # end _darwin__64

_darwin__arm64() {
  trap  '_trap_on_error $0 "${?}" LINENO BASH_LINENO FUNCNAME BASH_COMMAND $FUNCNAME $BASH_LINENO $LINENO   $BASH_COMMAND'  ERR
  _darwin__64
} # end _darwin__arm64

_tar() {
  trap  '_trap_on_error $0 "${?}" LINENO BASH_LINENO FUNCNAME BASH_COMMAND $FUNCNAME $BASH_LINENO $LINENO   $BASH_COMMAND'  ERR
  echo "Procedure not yet implemented. I don't know what to do."
} # end tar

_windows__64() {
  trap  '_trap_on_error $0 "${?}" LINENO BASH_LINENO FUNCNAME BASH_COMMAND $FUNCNAME $BASH_LINENO $LINENO   $BASH_COMMAND'  ERR
  echo "Procedure not yet implemented. I don't know what to do."
} # end _windows__64

_windows__32() {
  trap  '_trap_on_error $0 "${?}" LINENO BASH_LINENO FUNCNAME BASH_COMMAND $FUNCNAME $BASH_LINENO $LINENO   $BASH_COMMAND'  ERR
  echo "Procedure not yet implemented. I don't know what to do."
} # end _windows__32
