#!/usr/bin/bash

_debian_flavor_install() {
  echo "Procedure not yet implemented. I don't know what to do."
} # end _debian_flavor_install

_redhat_flavor_install() {
  echo "Procedure not yet implemented. I don't know what to do."
  HOW_TO_LOAD_JUST_ONE_SCRIPT_LOCAL_AND_ONLINE_EXECUTE_COMMAND
  dnf install -y snapd
  # ln -s /var/lib/snapd/snap /snap
  #if ! it_exists_with_spaces /var/lib/snapd/snap ; then 
	#{
    ln -sf /var/lib/snapd/snap /snap
	#}
	#fi
	snap install core
	snap refresh core
  snap install android-studio --classic
  snap list android-studio	
	ln -sf /snap/bin/android-studio /usr/local/bin/android-studio
	dnf install -y zlib.i686 ncurses-libs.i686 bzip2-libs.i686
  cd /tmp
  wget https://dl.google.com/dl/android/studio/ide-zips/2021.2.1.14/android-studio-2021.2.1.14-linux.tar.gz
  tar -zxvf android-studio-*-linux.tar.gz
  mv android-studio /opt/	
  ln -sf /opt/android-studio/bin/studio.sh /usr/local/bin/android-studio
  # vi /usr/share/applications/android-studio.desktop
  echo "[Desktop Entry]
Version=1.0
Type=Application
Name=Android Studio
Comment=Android Studio
Exec=bash -i "/opt/android-studio/bin/studio.sh" %f
Icon=/opt/android-studio/bin/studio.png
Categories=Development;IDE;
Terminal=false
StartupNotify=true
StartupWMClass=jetbrains-android-studio
Name[en_GB]=android-studio.desktop
  " > /usr/share/applications/android-studio.desktop

	su - "${SUDO_USER}" -c 'pip install xattr'
  su - "${SUDO_USER}" -c 'brew install GCC'
  su - "${SUDO_USER}" -c 'brew reinstall --cask android-studio'
  su - "${SUDO_USER}" -c 'brew reinstall --cask android-SDK'
  su - "${SUDO_USER}" -c 'brew reinstall --cask android-ndk'
  su - "${SUDO_USER}" -c 'brew reinstall --cask flutter'
  su - "${SUDO_USER}" -c 'brew reinstall --HEAD libimobiledevice'
  su - "${SUDO_USER}" -c 'brew reinstall ideviceinstaller'
  su - "${SUDO_USER}" -c 'brew reinstall ios-deploy cocoapods'
  su - "${SUDO_USER}" -c 'pod setup'
  su - "${SUDO_USER}" -c 'flutter doctor'
  # anounce_command xcodebuild -license
  su - "${SUDO_USER}" -c 'flutter config --android-SDK'
  su - "${SUDO_USER}" -c 'brew install --cask intel-haxm'

} # end _redhat_flavor_install

_arch_flavor_install() {
  echo "Procedure not yet implemented. I don't know what to do."
} # end _readhat_flavor_install

_arch__32() {
  _arch_flavor_install
} # end _arch__32

_arch__64() {
  _arch_flavor_install
} # end _arch__64

_centos__32() {
  _redhat_flavor_install
} # end _centos__32

_centos__64() {
  _redhat_flavor_install
} # end _centos__64

_debian__32() {
  _debian_flavor_install
} # end _debian__32

_debian__64() {
  _debian_flavor_install
} # end _debian__64

_fedora__32() {
  _redhat_flavor_install
} # end _fedora__32

_fedora_37__64(){
  _redhat_flavor_install
} # end _fedora_37__64

_fedora_38__64(){
  _redhat_flavor_install
} # end _fedora_38__64

_fedora_39__64(){
  _redhat_flavor_install
} # end _fedora_39__64

_fedora_40__64(){
  _redhat_flavor_install
} # end _fedora_40__64

_fedora__64() {
  _redhat_flavor_install
} # end _fedora__64

_gentoo__32() {
  _redhat_flavor_install
} # end _gentoo__32

_gentoo__64() {
  _redhat_flavor_install
} # end _gentoo__64

_madriva__32() {
  _redhat_flavor_install
} # end _madriva__32

_madriva__64() {
  _redhat_flavor_install
} # end _madriva__64

_suse__32() {
  _redhat_flavor_install
} # end _suse__32

_suse__64() {
  _redhat_flavor_install
} # end _suse__64

_ubuntu__32() {
  _debian_flavor_install
} # end _ubuntu__32

_ubuntu__64() {
  _debian_flavor_install
} # end _ubuntu__64

_darwin__arm64() {
  
    # Over write say with text version since Struct Testing say will speak on mac and make it so I can use anounce_command

  HOW_TO_LOAD_JUST_ONE_SCRIPT_LOCAL_AND_ONLINE_EXECUTE_COMMAND
  anounce_command _run_command pip install xattr
  anounce_command _run_command brew install GCC
  anounce_command _run_command  brew reinstall --cask android-studio
  anounce_command _run_command  brew reinstall --cask android-SDK
  anounce_command _run_command  brew reinstall --cask android-ndk
  anounce_command _run_command  brew reinstall --cask flutter
  anounce_command _run_command  brew reinstall libimobiledevice
  anounce_command _run_command  brew reinstall ideviceinstaller ios-deploy cocoapods
  anounce_command _run_command  pod setup
  anounce_command _run_command  flutter doctor
  anounce_command _run_command xcodebuild -license
  anounce_command _run_command flutter config --android-SDK
  anounce_command _run_command brew install --cask intel-haxm
} # end _darwin__arm64

_darwin__64() {
  
    # Over write say with text version since Struct Testing say will speak on mac and make it so I can use anounce_command

  HOW_TO_LOAD_JUST_ONE_SCRIPT_LOCAL_AND_ONLINE_EXECUTE_COMMAND
  anounce_command pip install xattr
  anounce_command  brew install GCC
  anounce_command  brew reinstall --cask android-studio
  anounce_command  brew reinstall --cask android-SDK
  anounce_command  brew reinstall --cask android-ndk
  anounce_command  brew reinstall --cask flutter
  anounce_command  brew reinstall --HEAD libimobiledevice
  anounce_command  brew reinstall ideviceinstaller ios-deploy cocoapods
  anounce_command  pod setup
  anounce_command  flutter doctor
  anounce_command xcodebuild -license
  anounce_command flutter config --android-SDK
  anounce_command brew install --cask intel-haxm
} # end _darwin__64

_tar() {
  echo "Procedure not yet implemented. I don't know what to do."
} # end tar

_windows__64() {
  echo "Procedure not yet implemented. I don't know what to do."
} # end _windows__64

_windows__32() {
  echo "Procedure not yet implemented. I don't know what to do."
} # end _windows__32
