#!/usr/bin/env bash
#!/bin/bash
#
# @author Zeus Intuivo <zeus@intuivo.com>
#
_version() {
  # fedora_32 https://www.scootersoftware.com/bcompare-4.3.3.24545.i386.rpm
  # https://www.scootersoftware.com/bcompare-4.3.3.24545.x86_64.rpm
  # zz=dl4&platform=mac, zz=dl4&platform=linux, zz=dl4&platform=win

  local PLATFORM="${1}"
  local PATTERN="${2}"
  # THOUGHT: local CODEFILE=$(curl -d "zz=dl4&platform=linux" -H "Content-Type: application/x-www-form-urlencoded" -X POST  -sSLo -  https://www.scootersoftware.com/download.php  2>&1;) # suppress only wget download messages, but keep wget output for variable
  local CODEFILE=$(curl -d "zz=dl4&platform=${PLATFORM}" -H "Content-Type: application/x-www-form-urlencoded" -X POST  -sSLo -  https://www.scootersoftware.com/download.php  2>&1;) # suppress only wget download messages, but keep wget output for variable
  # THOUGHT: local CODELASTESTBUILD=$(echo $CODEFILE | sed s/\</\\n\</g | grep "bcompare*.*.*.*.x86_64.rpm" | sed s/\"/\\n/g | grep "/" | cuet "/")
  # local CODELASTESTBUILD=$(echo $CODEFILE | sed s/\</\\n\</g | grep "${PATTERN}" | sed s/\"/\\n/g | grep "/" | cüt "/")
  local CODELASTESTBUILD=$(echo $CODEFILE | sed s/\</\\n\</g | grep "${PATTERN}" | sed s/\"/\\n/g | grep "/" | cüt "/files/")
  # fedora 32 local CODELASTESTBUILD=$(echo $CODEFILE | sed s/\</\\n\</g | grep "bcompare*.*.*.*.i386.rpm" | sed s/\"/\\n/g | grep "/" | cuet "/")
  wait
  [[ -z "${CODELASTESTBUILD}" ]] && failed "Beyond Compare Version not found! :${CODELASTESTBUILD}:"



  # enforce_variable_with_value USER_HOME "${USER_HOME}"
  # enforce_variable_with_value CODELASTESTBUILD "${CODELASTESTBUILD}"

  local CODENAME="${CODELASTESTBUILD}"
  echo "${CODELASTESTBUILD}"
  unset PATTERN
  unset PLATFORM
  unset CODEFILE
  unset CODELASTESTBUILD
} # end _version

_version_test(){
  local CODENAME=$(_version "linux" "bcompare*.*.*.*.x86_64.rpm")
	Checking "CODENAME:${CODENAME}" 
  enforce_variable_with_value CODENAME "${CODENAME}"
  exit 0
} # end _version_test
#_version_test

_darwin__64() {
  sudo_it
  export USER_HOME="/Users/${SUDO_USER}"
  enforce_variable_with_value USER_HOME "${USER_HOME}"

  local CODENAME=$(_version "mac" "BCompareOSX*.*.*.*.zip")
  enforce_variable_with_value CODENAME "${CODENAME}"
  # THOUGHT        local CODENAME="BCompareOSX-4.3.3.24545.zip"
  local URL="https://www.scootersoftware.com/${CODENAME}"

  # local TARGET_URL
  # TARGET_URL="${CODENAME}|Beyond Compare.app|${URL}"
  # enforce_variable_with_value TARGET_URL "${TARGET_URL}"
  # _install_dmgs_list "${TARGET_URL}"
  local DOWNLOADFOLDER="$USER_HOME/Downloads"
  enforce_variable_with_value DOWNLOADFOLDER "${DOWNLOADFOLDER}"
  cd "${DOWNLOADFOLDER}"
  echo _download_mac
  _download_mac "${URL}" "${DOWNLOADFOLDER}"
  local APPDIR="Beyond Compare.app"    # same as  $(basename "${APPDIR}")
  echo _remove_dmgs_app_if_exists
  _remove_dmgs_app_if_exists "${APPDIR}"
  echo _process_dmgs_dmg_or_zip
  _process_dmgs_dmg_or_zip "zip" "${DOWNLOADFOLDER}" "${CODENAME}" "${APPDIR}" "${CODENAME}"
  echo directory_exists_with_spaces
  directory_exists_with_spaces "/Applications/${APPDIR}"
  ls -d "/Applications/${APPDIR}"

  _trust_dmgs_application "${APPDIR}"
  ln -s /Applications/Beyond\ Compare.app/Contents/MacOS/bcomp /usr/local/bin/bcompare
  ln -s /Applications/Beyond\ Compare.app/Contents/MacOS/bcomp /usr/local/bin/bcomp
    # sudo hdiutil attach ${CODENAME}
    # sudo cp -R /Volumes/Beyond\ Compare/Beyond\ Compare.app /Applications/
    # sudo hdiutil detach /Volumes/Beyond \ Compare
} # end _darwin__64

_debian_flavor_install() {
  sudo_it
  trap 'echo -e "${RED}" && echo -e "ERROR failed \n$0:$LINENO _debian_flavor_install beyondcomapre" && echo -e "${RESET}" && return 0' ERR

  # export USER_HOME="/home/${SUDO_USER}"
  enforce_variable_with_value USER_HOME "${USER_HOME}"
  enforce_variable_with_value SUDO_USER "${SUDO_USER}"
  # THOUGHT          local CODENAME="bcompare-4.3.3.24545_amd64.deb"
  local CODENAME=$(_version "linux" "bcompare-*.*.*.*amd64.deb")
  enforce_variable_with_value CODENAME "${CODENAME}"
  local TARGET_URL="https://www.scootersoftware.com/${CODENAME}"
  enforce_variable_with_value TARGET_URL "${TARGET_URL}"
  local DOWNLOADFOLDER="$(_find_downloads_folder)"
  enforce_variable_with_value DOWNLOADFOLDER "${DOWNLOADFOLDER}"
  cd "${DOWNLOADFOLDER}"
  _download_mac "${TARGET_URL}" "${DOWNLOADFOLDER}"
  dpkg -i ${CODENAME}
} # end _debian_flavor_install

_package_list_installer() {
  local package packages="${@}"
  trap 'echo -e "${RED}" && echo -e "ERROR failed \n$0:$LINENO _package_list_installer rbenv" && echo -e "${RESET}" && return 0' ERR

  if ! install_requirements "linux" "${packages}" ; then
  {
    warning "installing requirements. ${CYAN} attempting to install one by one"
    while read package; do
    {
      [ -z ${package} ] && continue
      install_requirements "linux" "${package}"
      _err=$?
      if [ ${_err} -gt 0 ] ; then
      {
        failed to install requirements "${package}"
      }
      fi
    }
    done <<< "${packages}"
  }
  fi
} # end _package_list_installer

_ubuntu__64() {
  trap 'echo -e "${RED}" && echo "ERROR failed $0:$LINENO _ubuntu__64 beyondcomapre" && echo -e "${RESET}" && return 0' ERR

  local package packages="
    poppler-utils
  "
  _package_list_installer "${packages}"
  _debian_flavor_install
} # end _ubuntu__64

_ubuntu__32() {
  sudo_it
  # export USER_HOME="/Users/${SUDO_USER}"
  enforce_variable_with_value USER_HOME "${USER_HOME}"
  # _linux_prepare
  # THOUGHT local CODENAME="bcompare-4.3.3.24545_i386.deb"
  local CODENAME=$(_version "linux" "bcompare-*.*.*.*i386.deb")
  enforce_variable_with_value CODENAME "${CODENAME}"
  local TARGET_URL="https://www.scootersoftware.com/${CODENAME}"
  enforce_variable_with_value TARGET_URL "${TARGET_URL}"

  local DOWNLOADFOLDER="$(_find_downloads_folder)"
  enforce_variable_with_value DOWNLOADFOLDER "${DOWNLOADFOLDER}"
  cd "${DOWNLOADFOLDER}"
  _download_mac "${TARGET_URL}" "${DOWNLOADFOLDER}"
  sudo dpkg -i ${CODENAME}
} # end _ubuntu__32

_fedora__32() {
  sudo_it
  # export USER_HOME="/Users/${SUDO_USER}"
  enforce_variable_with_value USER_HOME "${USER_HOME}"
  # _linux_prepare
  local CODENAME=$(_version "linux" "bcompare*.*.*.*.i386.rpm")
  enforce_variable_with_value CODENAME "${CODENAME}"
  # THOUGHT                          bcompare-4.3.3.24545.i386.rpm
  local TARGET_URL="https://www.scootersoftware.com/${CODENAME}"
  enforce_variable_with_value TARGET_URL "${TARGET_URL}"
  local DOWNLOADFOLDER="$(_find_downloads_folder)"
  enforce_variable_with_value DOWNLOADFOLDER "${DOWNLOADFOLDER}"
  cd "${DOWNLOADFOLDER}"
  _download "${TARGET_URL}" "${USER_HOME}/Downloads" "${CODENAME}"
  file_exists_with_spaces "${DOWNLOADFOLDER}/${CODENAME}"
  ensure rpm or "Canceling Install. Could not find rpm command to execute install"
  # provide error handling , once learned goes here. LEarn under if, once learned here.
  # Start loop while ERROR flag in case needs to try again, based on error
  _try "rpm --import https://www.scootersoftware.com/RPM-GPG-KEY-scootersoftware"
  local msg=$(_try "rpm -ivh \"${DOWNLOADFOLDER}/${CODENAME}\"" )
  local ret=$?
  if [ $ret -gt 0 ] ; then
  {
    failed "${ret}:${msg}"
    # add error handling knowledge while learning.
  }
  else
  {
    passed Install with RPM success!
  }
  fi
  ensure bcompare or "Failed to install Beyond Compare"
  rm -f "${DOWNLOADFOLDER}/${CODENAME}"
  file_does_not_exist_with_spaces "${DOWNLOADFOLDER}/${CODENAME}"
} # end _fedora__32

_centos__64() {
  _fedora__64
} # end _centos__64

_fedora__64() {
  sudo_it
  # export USER_HOME="/Users/${SUDO_USER}"
  enforce_variable_with_value USER_HOME "${USER_HOME}"
  # _linux_prepare
  local CODENAME=$(_version "linux" "bcompare*.*.*.*.x86_64.rpm")
	Checking "_version:${_version}" 
  enforce_variable_with_value CODENAME "${CODENAME}"
  # THOUGHT  https://www.scootersoftware.com/bcompare-4.3.3.24545.x86_64.rpm
	local TARGET_URL="$(sed 's@//@/@g' <<<"www.scootersoftware.com/files/${CODENAME}")"
  TARGET_URL="https://${TARGET_URL}"
	Checking "TARGET_URL:${TARGET_URL}" 
  enforce_variable_with_value TARGET_URL "${TARGET_URL}"
  local DOWNLOADFOLDER="$(_find_downloads_folder)"
  enforce_variable_with_value DOWNLOADFOLDER "${DOWNLOADFOLDER}"
  cd "${DOWNLOADFOLDER}"
  _do_not_downloadtwice "${TARGET_URL}" "${DOWNLOADFOLDER}"  "${CODENAME}"
  _install_rpm "${TARGET_URL}" "${DOWNLOADFOLDER}"  "${CODENAME}" 0

  ensure bcompare or "Failed to install Beyond Compare"
  rm -f "${DOWNLOADFOLDER}/${CODENAME}"
  file_does_not_exist_with_spaces "${DOWNLOADFOLDER}/${CODENAME}"
} # end _fedora__64

_mingw__64() {
  sudo_it
  export USER_HOME="/Users/${SUDO_USER}"
  enforce_variable_with_value USER_HOME "${USER_HOME}"
  # _linux_prepare
    local CODENAME=$(_version "win" "BCompare*.*.*.*.exe")
    # THOUGHT        local CODENAME="BCompare-4.3.3.24545.exe"
    local URL="https://www.scootersoftware.com/${CODENAME}"
    cd $HOMEDIR
	  cd Downloads
    curl -O $URL
    ${CODENAME}
} # end _mingw__64

_mingw__32() {
	_linux_prepare
    local CODENAME=$(_version "win" "BCompare*.*.*.*.exe")
    # THOUGHT        local CODENAME="BCompare-4.3.3.24545.exe"
    local URL="https://www.scootersoftware.com/${CODENAME}"
    cd $HOMEDIR
    cd Downloads
	  curl -O $URL
	  ${CODENAME}
} # end


_main() {
  determine_os_and_fire_action
} # end _main

_main

echo ":)"


