#!/usr/bin/bash

_debian_flavor_install() {
  echo "Procedure not yet implemented. I don't know what to do."
} # end _debian_flavor_install

_redhat_flavor_install() {
  echo "Procedure not yet implemented. I don't know what to do."
} # end _redhat_flavor_install

_arch_flavor_install() {
  echo "Procedure not yet implemented. I don't know what to do."
} # end _readhat_flavor_install

_arch__32() {
  _arch_flavor_install
} # end _arch__32

_arch__64() {
  _arch_flavor_install
} # end _arch__64

_centos__32() {
  _redhat_flavor_install
} # end _centos__32

_centos__64() {
  _redhat_flavor_install
} # end _centos__64

_debian__32() {
  _debian_flavor_install
} # end _debian__32

_debian__64() {
  _debian_flavor_install
} # end _debian__64

_fedora__32() {
  _redhat_flavor_install
} # end _fedora__32

_fedora__64() {
  _redhat_flavor_install
} # end _fedora__64

_gentoo__32() {
  _redhat_flavor_install
} # end _gentoo__32

_gentoo__64() {
  _redhat_flavor_install
} # end _gentoo__64

_madriva__32() {
  _redhat_flavor_install
} # end _madriva__32

_madriva__64() {
  _redhat_flavor_install
} # end _madriva__64

_suse__32() {
  _redhat_flavor_install
} # end _suse__32

_suse__64() {
  _redhat_flavor_install
} # end _suse__64

_ubuntu__32() {
  _debian_flavor_install
} # end _ubuntu__32

_ubuntu__64() {
  git clone https://github.com/drogonframework/drogon 
  cd drogon
  git submodule update --init
  mkdir build
  cd build
  
  sudo apt install cmake -vy
  sudo apt-get install cmake -vy
  sudo apt-get install gddrescue -y
  sudo apt-get install cmake -y
  sudo apt install gcc -y
  sudo apt install g++ -y
  sudo apt install libjsoncpp-dev -y
  sudo apt install libjsoncpp -y
  sudo apt install uuid-dev -y
  sudo apt install libssl-dev -y
  sudo apt install zlib1g-dev -y
  sudo apt install zlib1g -y
  sudo apt-get install postgresql-all -y
  sudo apt-get install postgresql-server-dev -y
  sudo apt install libmariadbclient-dev -y
  sudo apt install libmariadb-dev-compat -y
  sudo apt-get install libsqlite3-dev -y
  udo apt-get install libhiredis-dev -y
  sudo apt-get install cmake  -y
  sudo apt-get install libhiredis-dev -y
  sudo apt-get install libsqlite3-dev -y
  cmake ..
  make && sudo make install
} # end _ubuntu__64

_darwin__64() {
  echo "Procedure not yet implemented. I don't know what to do."
} # end _darwin__64

_tar() {
  echo "Procedure not yet implemented. I don't know what to do."
} # end tar

_windows__64() {
  echo "Procedure not yet implemented. I don't know what to do."
} # end _windows__64

_windows__32() {
  echo "Procedure not yet implemented. I don't know what to do."
} # end _windows__32
