#!/bin/bash
#
# @author Zeus Intuivo <zeus@intuivo.com>
#
#


_debian__64(){
  enforce_variable_with_value USER_HOME "${USER_HOME}"
  local TARGET_URL=https://prerelease.keybase.io/keybase_amd64.deb
  Comment TARGET_URL "${TARGET_URL}"
  enforce_variable_with_value TARGET_URL "${TARGET_URL}"
  local CODENAME=$(basename "${TARGET_URL}")
  Comment CODENAME "${CODENAME}"
  enforce_variable_with_value CODENAME "${CODENAME}"
  local DOWNLOADFOLDER="$(_find_downloads_folder)"
  Comment DOWNLOADFOLDER "${DOWNLOADFOLDER}"
  enforce_variable_with_value DOWNLOADFOLDER "${DOWNLOADFOLDER}"
  _do_not_downloadtwice "${TARGET_URL}" "${DOWNLOADFOLDER}"  "${CODENAME}"
  _install_apt "${TARGET_URL}" "${DOWNLOADFOLDER}"  "${CODENAME}" 0
  _err=$?
  _remove_downloaded_codename_or_err  $_err "${DOWNLOADFOLDER}/${CODENAME}"
  _err=$?
  return  $_err
} # end __debian__64

_ubuntu__64(){
  _debian__64
} # end _ubuntu__64


_ubuntu__aarch64() {
  trap  '_trap_on_error $0 "${?}" LINENO BASH_LINENO FUNCNAME BASH_COMMAND $FUNCNAME $BASH_LINENO $LINENO   $BASH_COMMAND'  ERR
  _debian__64 # 2eVBOEDbQZEAEc9vCIwZKS85CPJ_2uiGFz2qwQXJJ2CHnEZ2G
} # end _ubuntu__aarch64

_ubuntu_22__aarch64() {
  trap  '_trap_on_error $0 "${?}" LINENO BASH_LINENO FUNCNAME BASH_COMMAND $FUNCNAME $BASH_LINENO $LINENO   $BASH_COMMAND'  ERR
	_debian__64
} # end _ubuntu_22__aarch64


_debian__32(){
  enforce_variable_with_value USER_HOME "${USER_HOME}"
  local TARGET_URL=https://prerelease.keybase.io/keybase_i386.deb
  Comment TARGET_URL "${TARGET_URL}"
  enforce_variable_with_value TARGET_URL "${TARGET_URL}"
  local CODENAME=$(basename "${TARGET_URL}")
  Comment CODENAME "${CODENAME}"
  enforce_variable_with_value CODENAME "${CODENAME}"
  local DOWNLOADFOLDER="${USER_HOME}/Downloads"
  Comment DOWNLOADFOLDER "${DOWNLOADFOLDER}"
  enforce_variable_with_value DOWNLOADFOLDER "${DOWNLOADFOLDER}"
  _do_not_downloadtwice "${TARGET_URL}" "${DOWNLOADFOLDER}"  "${CODENAME}"
  _install_apt "${TARGET_URL}" "${DOWNLOADFOLDER}"  "${CODENAME}" 0
  _err=$?
  _remove_downloaded_codename_or_err  $_err "${DOWNLOADFOLDER}/${CODENAME}"
  _err=$?
  return  $_err
} # end __debian__64

_fedora__32() {
  enforce_variable_with_value USER_HOME "${USER_HOME}"
  local TARGET_URL=https://prerelease.keybase.io/keybase_i386.rpm
  Comment TARGET_URL "${TARGET_URL}"
  enforce_variable_with_value TARGET_URL "${TARGET_URL}"
  local CODENAME=$(basename "${TARGET_URL}")
  Comment CODENAME "${CODENAME}"
  enforce_variable_with_value CODENAME "${CODENAME}"
  local DOWNLOADFOLDER="$(_find_downloads_folder)"
  Comment DOWNLOADFOLDER "${DOWNLOADFOLDER}"
  enforce_variable_with_value DOWNLOADFOLDER "${DOWNLOADFOLDER}"
  _do_not_downloadtwice "${TARGET_URL}" "${DOWNLOADFOLDER}"  "${CODENAME}"
  _install_rpm "${TARGET_URL}" "${DOWNLOADFOLDER}"  "${CODENAME}" 0
  _err=$?
  _remove_downloaded_codename_or_err  $_err "${DOWNLOADFOLDER}/${CODENAME}"
  _err=$?
  return  $_err
} # end _fedora__32
_centos__64(){
  _fedora__64
} # end _centos__64

_fedora_37__64(){
  _fedora__64
} # end _fedora_37__64

_fedora_38__64(){
  _fedora__64
} # end _fedora_38__64

_fedora_39__64(){
  _fedora__64
} # end _fedora_38__64

_fedora_40__64(){
  _fedora__64
} # end _fedora_40__64

_fedora__64() {
  enforce_variable_with_value USER_HOME "${USER_HOME}"
  local TARGET_URL=https://prerelease.keybase.io/keybase_amd64.rpm
  Comment TARGET_URL "${TARGET_URL}"
  enforce_variable_with_value TARGET_URL "${TARGET_URL}"
  local CODENAME=$(basename "${TARGET_URL}")
  Comment CODENAME "${CODENAME}"
  enforce_variable_with_value CODENAME "${CODENAME}"
  local DOWNLOADFOLDER="$(_find_downloads_folder)"
  Comment DOWNLOADFOLDER "${DOWNLOADFOLDER}"
  enforce_variable_with_value DOWNLOADFOLDER "${DOWNLOADFOLDER}"
  _do_not_downloadtwice "${TARGET_URL}" "${DOWNLOADFOLDER}"  "${CODENAME}"
  _install_rpm "${TARGET_URL}" "${DOWNLOADFOLDER}"  "${CODENAME}" 0
  _err=$?
	chown -R $USER /etc/keybase/
  _remove_downloaded_codename_or_err  $_err "${DOWNLOADFOLDER}/${CODENAME}"
  _err=$?
  return  $_err
} # end _fedora__64

_darwin__64(){
  su - "${SUDO_USER}" -c 'brew install keybase --force'
} # end _darwin__64

