#!/bin/bash
#
# @author Zeus Intuivo <zeus@intuivo.com>
#
#


_linux_prepare(){
  sudo_it
  [ $? -gt 0 ] && (failed to sudo_it raise_to_sudo_and_user_home  || exit 1)
  # export USER_HOME="/home/${SUDO_USER}"
  Checking USER_HOME "${USER_HOME}"
  enforce_variable_with_value USER_HOME "${USER_HOME}"
}  # end _linux_prepare

_debian__64(){
  _linux_prepare
  local TARGET_URL=https://prerelease.keybase.io/keybase_amd64.deb
  Comment TARGET_URL "${TARGET_URL}"
  enforce_variable_with_value TARGET_URL "${TARGET_URL}"
  local CODENAME=$(basename "${TARGET_URL}")
  Comment CODENAME "${CODENAME}"
  enforce_variable_with_value CODENAME "${CODENAME}"
  local DOWNLOADFOLDER="$(_find_downloads_folder)"
  Comment DOWNLOADFOLDER "${DOWNLOADFOLDER}"
  enforce_variable_with_value DOWNLOADFOLDER "${DOWNLOADFOLDER}"
  _do_not_downloadtwice "${TARGET_URL}" "${DOWNLOADFOLDER}"  "${CODENAME}"
  _install_apt "${TARGET_URL}" "${DOWNLOADFOLDER}"  "${CODENAME}" 0
  _err=$?
  _remove_downloaded_codename_or_err  $_err "${DOWNLOADFOLDER}/${CODENAME}"
  _err=$?
  return  $_err
} # end __debian__64

_ubuntu__64(){
  _debian__64
} # end _ubuntu__64

_debian__32(){
  _linux_prepare
  local TARGET_URL=https://prerelease.keybase.io/keybase_i386.deb
  Comment TARGET_URL "${TARGET_URL}"
  enforce_variable_with_value TARGET_URL "${TARGET_URL}"
  local CODENAME=$(basename "${TARGET_URL}")
  Comment CODENAME "${CODENAME}"
  enforce_variable_with_value CODENAME "${CODENAME}"
  local DOWNLOADFOLDER="${USER_HOME}/Downloads"
  Comment DOWNLOADFOLDER "${DOWNLOADFOLDER}"
  enforce_variable_with_value DOWNLOADFOLDER "${DOWNLOADFOLDER}"
  _do_not_downloadtwice "${TARGET_URL}" "${DOWNLOADFOLDER}"  "${CODENAME}"
  _install_apt "${TARGET_URL}" "${DOWNLOADFOLDER}"  "${CODENAME}" 0
  _err=$?
  _remove_downloaded_codename_or_err  $_err "${DOWNLOADFOLDER}/${CODENAME}"
  _err=$?
  return  $_err
} # end __debian__64

_fedora__32() {
  _linux_prepare
  local TARGET_URL=https://prerelease.keybase.io/keybase_i386.rpm
  Comment TARGET_URL "${TARGET_URL}"
  enforce_variable_with_value TARGET_URL "${TARGET_URL}"
  local CODENAME=$(basename "${TARGET_URL}")
  Comment CODENAME "${CODENAME}"
  enforce_variable_with_value CODENAME "${CODENAME}"
  local DOWNLOADFOLDER="$(_find_downloads_folder)"
  Comment DOWNLOADFOLDER "${DOWNLOADFOLDER}"
  enforce_variable_with_value DOWNLOADFOLDER "${DOWNLOADFOLDER}"
  _do_not_downloadtwice "${TARGET_URL}" "${DOWNLOADFOLDER}"  "${CODENAME}"
  _install_rpm "${TARGET_URL}" "${DOWNLOADFOLDER}"  "${CODENAME}" 0
  _err=$?
  _remove_downloaded_codename_or_err  $_err "${DOWNLOADFOLDER}/${CODENAME}"
  _err=$?
  return  $_err
} # end _fedora__32
_centos__64(){
  _fedora__64
} # end _centos__64
_fedora__64() {
  _linux_prepare
  local TARGET_URL=https://prerelease.keybase.io/keybase_amd64.rpm
  Comment TARGET_URL "${TARGET_URL}"
  enforce_variable_with_value TARGET_URL "${TARGET_URL}"
  local CODENAME=$(basename "${TARGET_URL}")
  Comment CODENAME "${CODENAME}"
  enforce_variable_with_value CODENAME "${CODENAME}"
  local DOWNLOADFOLDER="$(_find_downloads_folder)"
  Comment DOWNLOADFOLDER "${DOWNLOADFOLDER}"
  enforce_variable_with_value DOWNLOADFOLDER "${DOWNLOADFOLDER}"
  _do_not_downloadtwice "${TARGET_URL}" "${DOWNLOADFOLDER}"  "${CODENAME}"
  _install_rpm "${TARGET_URL}" "${DOWNLOADFOLDER}"  "${CODENAME}" 0
  _err=$?
  _remove_downloaded_codename_or_err  $_err "${DOWNLOADFOLDER}/${CODENAME}"
  _err=$?
  return  $_err
} # end _fedora__64

_darwin__64(){
  su - "${SUDO_USER}" -c 'brew install keybase --force'
}

