#!/usr/bin/bash

_debian_flavor_install() {
  # trap  '_trap_on_exit $0 "${?}" LINENO BASH_LINENO FUNCNAME BASH_COMMAND $FUNCNAME $BASH_LINENO $LINENO   $BASH_COMMAND'  EXIT
  trap  '_trap_on_error $0 "${?}" LINENO BASH_LINENO FUNCNAME BASH_COMMAND $FUNCNAME $BASH_LINENO $LINENO   $BASH_COMMAND'  ERR
  enforce_variable_with_value USER_HOME "${USER_HOME}"
  if
    (
    install_requirements "linux" "
      base64
      unzip
      curl
      wget
      ufw
      nginx
    "
    ); then
    {
      apt install base64 -y
      apt install unzip -y
      apt install nginx -y
    }
  fi
  verify_is_installed "
    unzip
    curl
    wget
    tar
    ufw
    nginx
  "
  local PB_VERSION=0.16.7
  local CODENAME="pocketbase_${PB_VERSION}_linux_amd64.zip"
  local TARGET_URL="https://github.com/pocketbase/pocketbase/releases/download/v${PB_VERSION}/${CODENAME}"
  local DOWNLOADFOLDER="$(_find_downloads_folder)"
  enforce_variable_with_value DOWNLOADFOLDER "${DOWNLOADFOLDER}"
  directory_exists_with_spaces "${DOWNLOADFOLDER}"
  cd "${DOWNLOADFOLDER}"
  _do_not_downloadtwice "${TARGET_URL}" "${DOWNLOADFOLDER}"  "${CODENAME}"
  # unzip "${DOWNLOADFOLDER}/${CODENAME}" -d $HOME/pb/
  local UNZIPDIR="${USER_HOME}/_/software"
  mkdir -p "${UNZIPDIR}"
  _unzip "${DOWNLOADFOLDER}" "${UNZIPDIR}" "${CODENAME}"
  local PATHTOPOCKETBASE="${UNZIPDIR}/pocketbase"
  local THISIP=$(myip)

} # end _debian_flavor_install

_redhat_flavor_install() {
  trap  '_trap_on_error $0 "${?}" LINENO BASH_LINENO FUNCNAME BASH_COMMAND $FUNCNAME $BASH_LINENO $LINENO   $BASH_COMMAND'  ERR
  echo "_redhat_flavor_install Procedure not yet implemented. I don't know what to do."
} # end _redhat_flavor_install

_arch_flavor_install() {
  trap  '_trap_on_error $0 "${?}" LINENO BASH_LINENO FUNCNAME BASH_COMMAND $FUNCNAME $BASH_LINENO $LINENO   $BASH_COMMAND'  ERR
  echo "_arch_flavor_install Procedure not yet implemented. I don't know what to do."
} # end _readhat_flavor_install

_arch__32() {
  trap  '_trap_on_error $0 "${?}" LINENO BASH_LINENO FUNCNAME BASH_COMMAND $FUNCNAME $BASH_LINENO $LINENO   $BASH_COMMAND'  ERR
  _arch_flavor_install
} # end _arch__32

_arch__64() {
  trap  '_trap_on_error $0 "${?}" LINENO BASH_LINENO FUNCNAME BASH_COMMAND $FUNCNAME $BASH_LINENO $LINENO   $BASH_COMMAND'  ERR
  _arch_flavor_install
} # end _arch__64

_centos__32() {
  trap  '_trap_on_error $0 "${?}" LINENO BASH_LINENO FUNCNAME BASH_COMMAND $FUNCNAME $BASH_LINENO $LINENO   $BASH_COMMAND'  ERR
  _redhat_flavor_install
} # end _centos__32

_centos__64() {
  trap  '_trap_on_error $0 "${?}" LINENO BASH_LINENO FUNCNAME BASH_COMMAND $FUNCNAME $BASH_LINENO $LINENO   $BASH_COMMAND'  ERR
  _redhat_flavor_install
} # end _centos__64

_debian__32() {
  trap  '_trap_on_error $0 "${?}" LINENO BASH_LINENO FUNCNAME BASH_COMMAND $FUNCNAME $BASH_LINENO $LINENO   $BASH_COMMAND'  ERR
  _debian_flavor_install
} # end _debian__32

_debian__64() {
  trap  '_trap_on_error $0 "${?}" LINENO BASH_LINENO FUNCNAME BASH_COMMAND $FUNCNAME $BASH_LINENO $LINENO   $BASH_COMMAND'  ERR
  _debian_flavor_install
} # end _debian__64

_fedora__32() {
  trap  '_trap_on_error $0 "${?}" LINENO BASH_LINENO FUNCNAME BASH_COMMAND $FUNCNAME $BASH_LINENO $LINENO   $BASH_COMMAND'  ERR
  _redhat_flavor_install
} # end _fedora__32

_fedora__64() {
  trap  '_trap_on_error $0 "${?}" LINENO BASH_LINENO FUNCNAME BASH_COMMAND $FUNCNAME $BASH_LINENO $LINENO   $BASH_COMMAND'  ERR
  _redhat_flavor_install
} # end _fedora__64

_fedora__64() {
  trap  '_trap_on_error $0 "${?}" LINENO BASH_LINENO FUNCNAME BASH_COMMAND $FUNCNAME $BASH_LINENO $LINENO   $BASH_COMMAND'  ERR
  _redhat_flavor_install
} # end _fedora__64

_fedora__64() {
  trap  '_trap_on_error $0 "${?}" LINENO BASH_LINENO FUNCNAME BASH_COMMAND $FUNCNAME $BASH_LINENO $LINENO   $BASH_COMMAND'  ERR
  _redhat_flavor_install
} # end _fedora__64

_fedora_36__64() {
  trap "echo Error:$?" ERR INT
  local _parameters="${*-}"
  local -i _err=0
  _err=$?
  if [ ${_err} -gt 0 ] ; then
  {
    failed "while running callsomething above _err:${_err}"
  }
  fi
  _redhat_flavor_install "${_parameters-}"
} # end _fedora_36__64

_fedora_37__64() {
  trap "echo Error:$?" ERR INT
  local _parameters="${*-}"
  local -i _err=0
  _err=$?
  if [ ${_err} -gt 0 ] ; then
  {
    failed "while running callsomething above _err:${_err}"
  }
  fi
  _redhat_flavor_install "${_parameters-}"
} # end _fedora_37__64

_fedora_38__64() {
  trap "echo Error:$?" ERR INT
  local _parameters="${*-}"
  local -i _err=0
  _err=$?
  if [ ${_err} -gt 0 ] ; then
  {
    failed "while running callsomething above _err:${_err}"
  }
  fi
  _redhat_flavor_install "${_parameters-}"
} # end _fedora_38__64

_fedora_39__64() {
  trap "echo Error:$?" ERR INT
  local _parameters="${*-}"
  local -i _err=0
  _err=$?
  if [ ${_err} -gt 0 ] ; then
  {
    failed "while running callsomething above _err:${_err}"
  }
  fi
  _redhat_flavor_install "${_parameters-}"
} # end _fedora_39__64

_gentoo__32() {
  trap  '_trap_on_error $0 "${?}" LINENO BASH_LINENO FUNCNAME BASH_COMMAND $FUNCNAME $BASH_LINENO $LINENO   $BASH_COMMAND'  ERR
  _redhat_flavor_install
} # end _gentoo__32

_gentoo__64() {
  trap  '_trap_on_error $0 "${?}" LINENO BASH_LINENO FUNCNAME BASH_COMMAND $FUNCNAME $BASH_LINENO $LINENO   $BASH_COMMAND'  ERR
  _redhat_flavor_install
} # end _gentoo__64

_madriva__32() {
  trap  '_trap_on_error $0 "${?}" LINENO BASH_LINENO FUNCNAME BASH_COMMAND $FUNCNAME $BASH_LINENO $LINENO   $BASH_COMMAND'  ERR
  _redhat_flavor_install
} # end _madriva__32

_madriva__64() {
  trap  '_trap_on_error $0 "${?}" LINENO BASH_LINENO FUNCNAME BASH_COMMAND $FUNCNAME $BASH_LINENO $LINENO   $BASH_COMMAND'  ERR
  _redhat_flavor_install
} # end _madriva__64

_suse__32() {
  trap  '_trap_on_error $0 "${?}" LINENO BASH_LINENO FUNCNAME BASH_COMMAND $FUNCNAME $BASH_LINENO $LINENO   $BASH_COMMAND'  ERR
  _redhat_flavor_install
} # end _suse__32

_netbsd__64() {
  trap  '_trap_on_error $0 "${?}" LINENO BASH_LINENO FUNCNAME BASH_COMMAND $FUNCNAME $BASH_LINENO $LINENO   $BASH_COMMAND'  ERR
  echo "This is installer is missing"
} # end _netbsd__64

_suse__64() {
  trap  '_trap_on_error $0 "${?}" LINENO BASH_LINENO FUNCNAME BASH_COMMAND $FUNCNAME $BASH_LINENO $LINENO   $BASH_COMMAND'  ERR
  _redhat_flavor_install
} # end _suse__64

_ubuntu__32() {
  trap  '_trap_on_error $0 "${?}" LINENO BASH_LINENO FUNCNAME BASH_COMMAND $FUNCNAME $BASH_LINENO $LINENO   $BASH_COMMAND'  ERR
  _debian_flavor_install
} # end _ubuntu__32

_ubuntu__64() {
  trap  '_trap_on_error $0 "${?}" LINENO BASH_LINENO FUNCNAME BASH_COMMAND $FUNCNAME $BASH_LINENO $LINENO   $BASH_COMMAND'  ERR
  _debian_flavor_install
} # end _ubuntu__64

_ubuntu__aarch64() {
  trap  '_trap_on_error $0 "${?}" LINENO BASH_LINENO FUNCNAME BASH_COMMAND $FUNCNAME $BASH_LINENO $LINENO   $BASH_COMMAND'  ERR
  _debian_flavor_install
} # end _ubuntu__aarch64

_ubuntu_22__aarch64() {
  trap  '_trap_on_error $0 "${?}" LINENO BASH_LINENO FUNCNAME BASH_COMMAND $FUNCNAME $BASH_LINENO $LINENO   $BASH_COMMAND'  ERR
  _debian_flavor_install
} # end _ubuntu_22__aarch64



_add_variables_to_bashrc_zshrc(){
  local CUDA_SH_CONTENT='

# CUDA
if [[ -e "'${USER_HOME}'/.cuda" ]] ; then
{
  export CUDA_ROOT="'${USER_HOME}'/.cuda"
  export PATH="'${USER_HOME}'/bin:${PATH}"
  export PATH="'${USER_HOME}'/.cuda/bin:${PATH}"
  eval "$(cuda init -)"
}
fi
'
  trap 'echo -e "${RED}" && echo "ERROR failed $0:$LINENO _add_variables_to_bashrc_zshrc cuda" && echo -e "${RESET}" && return 0' ERR
  Checking "${CUDA_SH_CONTENT}"
  local INITFILE INITFILES="
   .bashrc
   .zshrc
   .bash_profile
   .profile
   .zshenv
   .zprofile
  "
  while read INITFILE; do
  {
    [ -z ${INITFILE} ] && continue
    Checking "${USER_HOME}/${INITFILE}"
    _if_not_contains "${USER_HOME}/${INITFILE}"  "# CUDA" ||  echo "${CUDA_SH_CONTENT}" >> "${USER_HOME}/${INITFILE}"
    _if_not_contains "${USER_HOME}/${INITFILE}"  "CUDA_ROOT" ||  echo "${CUDA_SH_CONTENT}" >> "${USER_HOME}/${INITFILE}"
    _if_not_contains "${USER_HOME}/${INITFILE}"  "cuda init" ||  echo "${CUDA_SH_CONTENT}" >> "${USER_HOME}/${INITFILE}"
  }
  done <<< "${INITFILES}"
  # type cuda
  Checking "export PATH=\"${USER_HOME}/.cuda/bin:${PATH}\" "
  export PATH="${USER_HOME}/.cuda/bin:${PATH}"
  chown -R "${SUDO_USER}" "${USER_HOME}/.cuda"
  cd "${USER_HOME}/.cuda/bin"
  eval "$("${USER_HOME}"/.cuda/bin/cuda init -)"

  # cuda doctor
  # cuda install -l
  # cuda install 2.6.5
  # cuda global 2.6.5
  # cuda rehash
  # ruby -v

} # _add_variables_to_bashrc_zshrc

_darwin_13_6__64() {
  trap "echo Error:$?" ERR INT
  local _parameters="${*-}"
  local -i _err=0
  _darwin__64 "${_parameters-}"
  _err=$?
  if [ ${_err} -gt 0 ] ; then
  {
    failed "$0:$LINENO while running callsomething above _err:${_err}"
  }
  fi
} # end _darwin_13_6__64

_darwin__64() {
  trap  '_trap_on_error $0 "${?}" LINENO BASH_LINENO FUNCNAME BASH_COMMAND $FUNCNAME $BASH_LINENO $LINENO   $BASH_COMMAND'  ERR
  local _cwd=$(pwd)
  local -i _err=0

  if it_exists_with_spaces .venv ; then
  {
    python3 -m venv .venv
  }
  else
  {
    source .venv/bin/activate
  }
  fi

  # su - "${SUDO_USER}" -c "brew install python@3.9"
  # su - "${SUDO_USER}" -c "brew link --force --overwrite python@3.9"
  

  if it_exists_with_spaces /usr/local/bin/cuda-gdb ; then
  {
    pwd
    echo "Cuda version test:" 
    cuda-gdb --version
    passed "found dir /usr/local/bin/cuda-gdb already build"
  }
  else
  {


    if it_exists_with_spaces cuda-gdb-darwin-12.2.53-32947973.gz ; then
    {
      passed "found file cuda-gdb-darwin-12.2.53-32947973.gz"
    }
    fi

    local INSTALL_DIR=/usr/local/bin/cuda-gdb-darwin-12.2
    if it_exists_with_spaces "${INSTALL_DIR}" ; then
    {
      rm -rf "${INSTALL_DIR}"
    }
    fi
    mkdir -p "${INSTALL_DIR}"

    cp cuda-gdb-darwin-12.2.53-32947973.gz "${INSTALL_DIR}"
    cd "${INSTALL_DIR}" || failed "to move to dir cd ${INSTALL_DIR}"
    if it_exists_with_spaces cuda-gdb-darwin-12.2.53-32947973.gz ; then
    {
      passed "found file cuda-gdb-darwin-12.2.53-32947973.gz"
    }
    fi
    tar fxvz  cuda-gdb-darwin-12.2.53-32947973.gz
    cd "${INSTALL_DIR}/bin" || failed "to move to dir cd ${INSTALL_DIR}/bin"
    # _add_variables_to_bashrc_zshrc
    link_folder_scripts
    xattr -d  com.apple.quarantine cuda-binary-gdb 
    xattr -d  com.apple.quarantine cuda-gdb  
    xattr -d  com.apple.quarantine cuobjdump  
    xattr -d  com.apple.quarantine nvdisasm
    cuda-gdb --version
  }
  fi

  cd "${_cwd}"
  if it_exists_with_spaces opencv ; then
  {
    passed "found dir opencv"
  }
  else
  {
    git clone https://github.com/opencv/opencv.git "opencv"
  }
  fi
  cd "${_cwd}"
  if it_exists_with_spaces opencv_contrib ; then
  {
    passed "found dir opencv_contrib"
  }
  else
  {
    git clone https://github.com/opencv/opencv_contrib.git "opencv_contrib"
  }
  fi
  export PATH="/usr/local/opt/python@3.12/bin:$PATH"
  export LDFLAGS="-L/usr/local/opt/python@3.12/lib"
  export CPPFLAGS="-I/usr/local/opt/python@3.12/include"
  export PKG_CONFIG_PATH="/usr/local/opt/python@3.12/lib/pkgconfig"
  local PY3_INCLUDE_DIR=$(python3 -c "import sysconfig; print(sysconfig.get_paths()['include'])")
  local PY3_LIBRARY=$(python3 -c "import sysconfig; print(sysconfig.get_config_var('LIBDIR'))")/libpython3.12.dylib
  local PY3_PACKAGES_PATH=$(python3 -c "import site; print(site.getsitepackages()[0])")
  # local PY3_INCLUDE_DIR=$(python3 -c "from distutils.sysconfig import get_python_inc; print(get_python_inc())")
  # local PY3_LIBRARY=$(python3 -c "import sysconfig; print(sysconfig.get_config_var('LIBDIR'))")/libpython3.12.dylib
  # local PY3_PACKAGES_PATH=$(python3 -c "import site; print(site.getsitepackages()[0])")
  #     # -D PYTHON3_INCLUDE_DIR=/usr/local/opt/python@3.12/Frameworks/Python.framework/Versions/3.12/include/python3.12 \
      # -D PYTHON3_LIBRARY=/usr/local/opt/python@3.12/Frameworks/Python.framework/Versions/3.12/lib/libpython3.12.dylib \
      # -D PYTHON3_PACKAGES_PATH=/usr/local/opt/python@3.12/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages \

  # su - "${SUDO_USER}" -c "python3 -m ensurepip --upgrade"
  # su - "${SUDO_USER}" -c "python3 -m pip install setuptools"
  if it_exists_with_spaces opencv3.4.20-build-mac64-osx13 ; then
  {
    pwd
    echo "opencv 3.4.20 version test:" 
    ./opencv3.4.20-build-mac64-osx13/bin/opencv_version
    passed "found dir opencv3.4.20-build-mac64-osx13 already build"
  }
  else
  {
    rm -rf opencv3.4.20/build
    mkdir -p opencv3.4.20/build
    mkdir -p opencv4.8.0-build-mac64-osx13
    cd opencv3.4.20/build
    cmake -D CMAKE_BUILD_TYPE=Release \
        -D CMAKE_INSTALL_PREFIX=../../opencv3.4.20-build-mac64-osx13 \
        -D OPENCV_EXTRA_MODULES_PATH=../../opencv_contrib3.4.20/modules \
        -D WITH_OPENCL=ON \
        -D WITH_OPENCL_SVM=OFF \
        -D WITH_OPENCLAMDFFT=OFF \
        -D WITH_OPENCLAMDBLAS=OFF \
        -D BUILD_OPENCV_DNN=OFF \
        -D BUILD_opencv_dnn=OFF \
        -D BUILD_OPENCV_XPHOTO=OFF \
        -D BUILD_opencv_xphoto=OFF \
        -D PYTHON3_EXECUTABLE=$(which python3) \
        -D PYTHON3_INCLUDE_DIR="${PY3_INCLUDE_DIR}" \
        -D PYTHON3_LIBRARY="${PY3_LIBRARY}" \
        -D PYTHON3_PACKAGES_PATH="${PY3_PACKAGES_PATH}" \
        ..

    echo "" > build3.4.20.log
    make VERBOSE=1  -j$(sysctl -n hw.logicalcpu) 2>&1 | tee build3.4.20.log
    _err=$?
    if ( grep -qi 'error' build3.4.20.log ) ; then
    {
      grep -i 'error' build3.4.20.log > errors3.4.20.log
    }
    fi
    if ( grep -qi 'undefined reference' build3.4.20.log ) ; then
    {
      grep -i 'undefined reference' build3.4.20.log > reference3.4.20.log
    }
    fi
    if ( grep -qi 'undefined' build3.4.20.log ) ; then
    {
      grep -i 'undefined' build3.4.20.log > undefined3.4.20.log
    }
    fi
    if ( grep -qi 'missing' build3.4.20.log ) ; then
    {
      grep -i 'missing' build3.4.20.log > missing3.4.20.log
    }
    fi
    if ( grep -qi 'failed' build3.4.20.log ) ; then
    {
      grep -i 'failed' build3.4.20.log > failed3.4.20.log
    }
    fi
    if [ ${_err} -gt 0 ] ; then
    {
      rm -rf ../../opencv3.4.20-build-mac64-osx13 &
      failed " $0:$LINENO while running make for opencv3.4.20  removing build target also _err:${_err}"
    }
    fi
  }
  fi
  cd "${_cwd}"

  if it_exists_with_spaces opencv4.8.0-build-mac64-osx13 ; then
  {
    pwd
    echo "opencv 4.8.0 version test:" 
    ./opencv4.8.0-build-mac64-osx13/bin/opencv_version
    passed "found dir opencv4.8.0-build-mac64-osx13 already build"
  }
  else
  {
    rm -rf opencv4.8.0/build
    mkdir -p opencv4.8.0/build
    mkdir -p opencv4.8.0-build-mac64-osx13
    cd opencv4.8.0/build
    
    cmake -D CMAKE_BUILD_TYPE=Release \
        -D CMAKE_INSTALL_PREFIX=../../opencv4.8.0-build-mac64-osx13 \
        -D OPENCV_EXTRA_MODULES_PATH=../../opencv_contrib4.8.0/modules \
        -D WITH_OPENCL=ON \
        -D WITH_OPENCL_SVM=OFF \
        -D WITH_OPENCLAMDFFT=OFF \
        -D WITH_OPENCLAMDBLAS=OFF \
        -D BUILD_OPENCV_DNN=OFF \
        -D BUILD_opencv_dnn=OFF \
        -D PYTHON3_EXECUTABLE=$(which python3) \
        -D PYTHON3_INCLUDE_DIR="${PY3_INCLUDE_DIR}" \
        -D PYTHON3_LIBRARY="${PY3_LIBRARY}" \
        -D PYTHON3_PACKAGES_PATH="${PY3_PACKAGES_PATH}" \
        ..

    echo "" > build4.8.0.log
    make VERBOSE=1  -j$(sysctl -n hw.logicalcpu) 2>&1 | tee build4.8.0.log
    _err=$?
    if ( grep -qi 'error' build4.8.0.log ) ; then
    {
      grep -i 'error' build4.8.0.log > errors4.8.0.log
    }
    fi
    if ( grep -qi 'undefined reference' build4.8.0.log ) ; then
    {
      grep -i 'undefined reference' build4.8.0.log > reference4.8.0.log
    }
    fi
    if ( grep -qi 'undefined' build4.8.0.log ) ; then
    {
      grep -i 'undefined' build4.8.0.log > undefined4.8.0.log
    }
    fi
    if ( grep -qi 'missing' build4.8.0.log ) ; then
    {
      grep -i 'missing' build4.8.0.log > missing4.8.0.log
    }
    fi
    if ( grep -qi 'failed' build4.8.0.log ) ; then
    {
      grep -i 'failed' build4.8.0.log > failed4.8.0.log
    }
    fi
    if [ ${_err} -gt 0 ] ; then
    {
      rm -rf ../../opencv4.8.0-build-mac64-osx13 &
      failed " $0:$LINENO while running make for opencv4.8.0  removing build target also _err:${_err}"
    }
    fi
  }
  fi

  cd "${_cwd}"

  if it_exists_with_spaces /usr/local/bin/opencv_version ; then
  {
    pwd
    echo "opencv latest version test:" 
    opencv_version
    passed "found dir /usr/local/bin/opencv_version already build"
  }
  else
  {
    rm -rf opencv/build
    mkdir -p opencv/build
    cd opencv/build
    
    su - "${SUDO_USER}" -c "brew installl --force --overwrite python@3.12"
    su - "${SUDO_USER}" -c "brew link --force --overwrite python@3.12"
    su - "${SUDO_USER}" -c "brew postinstall python@3.12"

    
    cmake -D CMAKE_BUILD_TYPE=Release \
        -D CMAKE_INSTALL_PREFIX=/usr/local \
        -D OPENCV_EXTRA_MODULES_PATH=../../opencv_contrib/modules \
        -D WITH_OPENCL=ON \
        -D WITH_OPENCL_SVM=OFF \
        -D WITH_OPENCLAMDFFT=OFF \
        -D WITH_OPENCLAMDBLAS=OFF \
        -D PYTHON3_EXECUTABLE=$(which python3) \
        -D PYTHON3_INCLUDE_DIR="${PY3_INCLUDE_DIR}" \
        -D PYTHON3_LIBRARY="${PY3_LIBRARY}" \
        -D PYTHON3_PACKAGES_PATH="${PY3_PACKAGES_PATH}" \
        ..
  
    echo "" > build_lastest.log
    make -j$(sysctl -n hw.logicalcpu) 2>&1 | tee build_lastest.log
    _err=$?
    if ( grep -qi 'error' build_lastest.log ) ; then
    {
      grep -i 'error' build_lastest.log > errors_lastest.log
    }
    fi
    if ( grep -qi 'undefined reference' build_lastest.log ) ; then
    {
      grep -i 'undefined reference' build_lastest.log > reference_lastest.log
    }
    fi
    if ( grep -qi 'undefined' build_lastest.log ) ; then
    {
      grep -i 'undefined' build_lastest.log > undefined_lastest.log
    }
    fi
    if ( grep -qi 'missing' build_lastest.log ) ; then
    {
      grep -i 'missing' build_lastest.log > missing_lastest.log
    }
    fi
    if ( grep -qi 'failed' build_lastest.log ) ; then
    {
      grep -i 'failed' build_lastest.log > failed_lastest.log
    }
    fi
    if [ ${_err} -gt 0 ] ; then
    {
      failed "$0:$LINENO while running make for opencv lastest also _err:${_err}"
    }
    fi
    make install

    su - "${SUDO_USER}" -c "python3 -c 'import cv2; print(cv2.__version__)'"
  }
  fi
  echo "install brew stuff ?"
  echo "install brew stuff ?"
  echo "install brew stuff ?"
  echo "install brew stuff ?"
  echo "install brew stuff ?"
  echo "install brew stuff ?"
  echo "install brew stuff ?"
  echo "install brew stuff ?"


  su - "${SUDO_USER}" -c "brew install cmake pkg-config"
  su - "${SUDO_USER}" -c "brew install ffmpeg"
  

} # end _darwin__64


_git_clone() {
  trap  '_trap_on_error $0 "${?}" LINENO BASH_LINENO FUNCNAME BASH_COMMAND $FUNCNAME $BASH_LINENO $LINENO   $BASH_COMMAND'  ERR
  trap 'echo -e "${RED}" && echo "ERROR failed $0:$LINENO  _git_clone CUDA" && echo -e "${RESET}" && return 0' ERR
  local _source="${1}"
  local _target="${2}"
  Checking "${SUDO_USER}" "${_target}"
  pwd
  if  it_exists_with_spaces "${_target}" ; then # && it_exists_with_spaces "${_target}/.git" ; then
  {
    if it_exists_with_spaces "${_target}/.git" ; then
    {
      cd "${_target}"
      if git config pull.rebase false ; then
      {
        warning Could not git config pull.rebase false
      }
      fi
      if git fetch  ; then
      {
        warning Could not git fetch
      }
      fi
      if git pull  ; then
      {
        warning Could not git pull
      }
      fi
    }
    fi
  }
  else
  {
    if git clone "${_source}" "${_target}"  ; then
    {
      warning Could not git clone "${_source}" "${_target}"
    }
    fi
  }
  fi
  chown -R "${SUDO_USER}" "${_target}"

} # end _git_clone


_darwin__arm64() {
  trap  '_trap_on_error $0 "${?}" LINENO BASH_LINENO FUNCNAME BASH_COMMAND $FUNCNAME $BASH_LINENO $LINENO   $BASH_COMMAND'  ERR
  echo "_darwin__arm64 Procedure not yet implemented. I don't know what to do."
} # end _darwin__arm64

_tar() {
  trap  '_trap_on_error $0 "${?}" LINENO BASH_LINENO FUNCNAME BASH_COMMAND $FUNCNAME $BASH_LINENO $LINENO   $BASH_COMMAND'  ERR
  echo "_tar Procedure not yet implemented. I don't know what to do."
} # end tar

_windows__64() {
  trap  '_trap_on_error $0 "${?}" LINENO BASH_LINENO FUNCNAME BASH_COMMAND $FUNCNAME $BASH_LINENO $LINENO   $BASH_COMMAND'  ERR
  echo "_windows__64 Procedure not yet implemented. I don't know what to do."
} # end _windows__64

_windows__32() {
  trap  '_trap_on_error $0 "${?}" LINENO BASH_LINENO FUNCNAME BASH_COMMAND $FUNCNAME $BASH_LINENO $LINENO   $BASH_COMMAND'  ERR
  echo "_windows__32 Procedure not yet implemented. I don't know what to do."
} # end _windows__32
