#!/usr/bin/env bash
#
# @author Zeus Intuivo <zeus@intuivo.com>
#
_debian_flavor_install() {
  echo "Procedure not yet implemented. I don't know what to do."
} # end _debian_flavor_install

_redhat_flavor_install() {
  Comment Based on OpenSuse Repos REF: https://build.opensuse.org/repositories/network:im:signal
  dnf install https://download.opensuse.org/repositories/network:/im:/signal/Fedora_36/x86_64/nodejs-electron-devel-21.3.0-2.4.x86_64.rpm  https://download.opensuse.org/repositories/network:/im:/signal/Fedora_36/x86_64/nodejs-electron-21.3.0-2.4.x86_64.rpm -vy
  dnf install https://download.opensuse.org/repositories/network:/im:/signal/Fedora_36/x86_64/signal-libringrtc-2.21.2-2.1.x86_64.rpm https://download.opensuse.org/repositories/network:/im:/signal/Fedora_36/x86_64/libheif1-1.13.0-35.1.x86_64.rpm https://download.opensuse.org/repositories/network:/im:/signal/Fedora_36/x86_64/libheif-devel-1.13.0-35.1.x86_64.rpm -vy
  dnf install https://download.opensuse.org/repositories/network:/im:/signal/Fedora_36/x86_64/gdk-pixbuf-loader-libheif-1.13.0-35.1.x86_64.rpm -vy
  dnf install https://download.opensuse.org/repositories/network:/im:/signal/Fedora_36/x86_64/esbuild-0.15.11-4.1.x86_64.rpm -vy
  curl -sSLO https://download.opensuse.org/repositories/network:/im:/signal/Fedora_36/x86_64/app-builder-3.4.2%5e20220309g4e2aa6a1-5.116.x86_64.rpm
  dnf install ./app-builder-3.4.2%5e20220309g4e2aa6a1-5.116.x86_64.rpm -vy
  rm ./app-builder-3.4.2%5e20220309g4e2aa6a1-5.116.x86_64.rpm
  dnf install https://download.opensuse.org/repositories/network:/im:/signal/Fedora_36/x86_64/signal-desktop-5.63.1-3.1.x86_64.rpm -vy
  echo "Procedure not yet implemented. I don't know what to do."
} # end _redhat_flavor_install

_arch_flavor_install() {
  echo "Procedure not yet implemented. I don't know what to do."
} # end _readhat_flavor_install

_arch__32() {
  _arch_flavor_install
} # end _arch__32

_arch__64() {
  _arch_flavor_install
} # end _arch__64

_centos__32() {
  _redhat_flavor_install
} # end _centos__32

_centos__64() {
  _redhat_flavor_install
} # end _centos__64

_debian__32() {
  _debian_flavor_install
} # end _debian__32

_debian__64() {
  _debian_flavor_install
} # end _debian__64

_fedora__32() {
  _redhat_flavor_install
} # end _fedora__32

_fedora__64() {
  _redhat_flavor_install
} # end _fedora__64

_gentoo__32() {
  _redhat_flavor_install
} # end _gentoo__32

_gentoo__64() {
  _redhat_flavor_install
} # end _gentoo__64

_madriva__32() {
  _redhat_flavor_install
} # end _madriva__32

_madriva__64() {
  _redhat_flavor_install
} # end _madriva__64

_suse__32() {
  _redhat_flavor_install
} # end _suse__32

_suse__64() {
  _redhat_flavor_install
} # end _suse__64

_ubuntu__32() {
  _debian_flavor_install
} # end _ubuntu__32

_ubuntu__64() {
  _debian_flavor_install
} # end _ubuntu__64

_darwin__64() {
  echo "Procedure not yet implemented. I don't know what to do."
} # end _darwin__64

_tar() {
  echo "Procedure not yet implemented. I don't know what to do."
} # end tar

_windows__64() {
  echo "Procedure not yet implemented. I don't know what to do."
} # end _windows__64

_windows__32() {
  echo "Procedure not yet implemented. I don't know what to do."
} # end _windows__32
