#!/usr/bin/env bash
#
# @author Zeus Intuivo <zeus@intuivo.com>
#
set -E -o functrace
_version() {
  local -i _err=0
  trap '[[ -z "$FUNCNAME" ]] && echo -e "${RED}ERROR failed ${#FUNCNAME[@]} $BASH_SOURCE:$LINENO \t\t\t  function:$FUNCNAME ${RESET}" && exit 0 || [[ -n "$FUNCNAME" ]] && echo -e "${RED}ERROR failed ${#FUNCNAME[@]} $BASH_SOURCE:$LINENO \t\t\t  function:$FUNCNAME ${RESET}" && return 1 ' ERR
  trap '[[ -z "$FUNCNAME" ]] && exit 0 || [[ -n "$FUNCNAME" ]] && echo -e "${PURPLE}INTERRUPTED ${YELLOW} ${#FUNCNAME[@]} $BASH_SOURCE:$LINENO \t\t\t function:$FUNCNAME ${RESET}" && return 1 ' INT
  local PLATFORM="${1}" # mac windows linux
  local PATTERN="${2}"
  local -i _err=0
  # THOUGHT:   https://download-cf.jetbrains.com/webstorm/WebStorm-2020.3.dmg
  local CODEFILE=""
  if [ -f step2_failed_CODELASTESTBUILD_was_empty.html ] ; then
  {
    CODEFILE="$(<step2_failed_CODELASTESTBUILD_was_empty.html)"
  }
  else
  {
    # older than 2023 CODEFILE="""$(wget --quiet --no-check-certificate  https://www.jetbrains.com/webstorm/ -O -  2>/dev/null )""" # suppress only wget download messages, but keep wget output for variable
    # CODEFILE="""$(wget --quiet --no-check-certificate  https://www.jetbrains.com/webstorm/download/\#section\=${PLATFORM} -O -  2>/dev/null )""" # suppress only wget download messages, but keep wget output for variable
    CODEFILE="""$(wget --quiet --no-check-certificate  https://data.services.jetbrains.com/products\?platform\=${PLATFORM} -O -  2>/dev/null )""" # suppress only wget download messages, but keep wget output for variable
  }
  fi
  _err=$?
  wait
  if [ -z "${CODEFILE}" ] || [ ${_err} -gt 0 ] ; then
  {
    echo "$BASH_SOURCE:$LINENO function:$FUNCNAME variable is empty CODEFILE"
    return 1  # here one is for error
  }
  fi
  enforce_variable_with_value CODEFILE "${CODEFILE}"
  local CODELASTESTBUILD=$(echo "${CODEFILE}" \
 | sed s/\</\\n\</g \
 | sed s/\>/\>\\n/g \
 | sed "s/&apos;/\'/g" \
 | sed 's/&nbsp;/ /g' \
 | sed 's/,/\n/g' | grep WebStorm | grep -v aarch64  | grep tar.gz | grep link | head -1 | sed 's/"/\n/g' | grep https \
 | tail -1 )
# | grep  "linux" | sed s/\ /\\n/g | grep href | sed 's/"/\n/g' | grep linux \
# | sed s/\ /\\n/g \
# | grep  "New in WebStorm ${PATTERN}" \
# | grep "What&apos;s New in&nbsp;WebStorm&nbsp;" | sed 's/\;/\;'\\n'/g' | sed s/\</\\n\</g  )
  _err=$?
  wait
  if [ -z "${CODELASTESTBUILD}" ] || [ ${_err} -gt 0 ] ; then
  {
    echo "${CODEFILE}" > step2_failed_CODELASTESTBUILD_was_empty.html
    echo "$BASH_SOURCE:$LINENO function:$FUNCNAME variable is empty CODELASTESTBUILD _err:$_err"
    echo '
    wget --quiet --no-check-certificate https://data.services.jetbrains.com/products\?platform\=${PLATFORM} -O - > step2_failed_CODELASTESTBUILD_was_empty.html 
    cat step2_failed_CODELASTESTBUILD_was_empty.html \
   | sed s/\</\\n\</g  \
   | sed s/\>/\>\\n/g  \ '
   echo "   | sed \"s/&apos;/'/g\" \\
   | sed 's/&nbsp;/ /g' \\
   "
   # | grep  \"New in WebStorm ${PATTERN}\" \\
   # echo " | sed s/\\ /\\\\n/g \\
   # echo "   | grep  linux | sed s/\ /\\n/g | grep href \\ "
   # echo "   | sed 's/\"/\n/g' | grep linux  \\
   echo "    | sed 's/,/\n/g' | grep WebStorm | grep -v aarch64  | grep tar.gz | grep link | head -1 | sed 's/\"/\n/g' | grep https \\ 
   | tail -1
   "

    return 1  # here one is for error
  }
  fi
  enforce_variable_with_value CODELASTESTBUILD "${CODELASTESTBUILD}"
  _err=$?
  if [ -z "${CODELASTESTBUILD}" ] || [ ${_err} -gt 0 ] ; then
  {
    return 1  # here one is for error
  }
  fi
  rm -rf step2_failed_CODELASTESTBUILD_was_empty.html
  local CODENAME=""
  case ${PLATFORM} in
  mac)
    # older than 2023 CODENAME="https://download-cf.jetbrains.com/webstorm/WebStorm-${CODELASTESTBUILD}.dmg"
    # CODENAME="https:${CODELASTESTBUILD}"
    CODENAME="${CODELASTESTBUILD}"
    ;;

  windows)
    # older than 2023 CODENAME="https://download-cf.jetbrains.com/webstorm/WebStorm-${CODELASTESTBUILD}.exe"
    # older than 2023 CODENAME="https://download-cf.jetbrains.com/webstorm/WebStorm-${CODELASTESTBUILD}.win.zip"
    # CODENAME="https:${CODELASTESTBUILD}"
    CODENAME="${CODELASTESTBUILD}"
    ;;

  linux)
    # older than 2023 CODENAME="https://download-cf.jetbrains.com/webstorm/WebStorm-${CODELASTESTBUILD}.tar.gz"
    # CODENAME="https:${CODELASTESTBUILD}"
    CODENAME="${CODELASTESTBUILD}"
    ;;

  *)
    CODENAME=""
    ;;
  esac
  enforce_variable_with_value CODENAME "${CODENAME}"
  _err=$?
  if [ -z "${CODENAME}" ] || [ ${_err} -gt 0 ] ; then
  {
    echo "$BASH_SOURCE:$LINENO function:$FUNCNAME variable is empty CODELASTESTBUILD _err:$_err"
    return 1  # here one is for error
  }
  fi
  unset PATTERN
  unset PLATFORM
  unset CODEFILE
  unset CODELASTESTBUILD
  echo "${CODENAME}"
  return 0
} # end _version
function _unzip(){
  # Sample use
  #
  #     _unzip "${DOWNLOADFOLDER}" "${UNZIPDIR}" "${CODENAME}"
  #
  local DOWNLOADFOLDER="${1}"
  enforce_variable_with_value DOWNLOADFOLDER "${DOWNLOADFOLDER}"

  local UNZIPDIR="${2}"
  enforce_variable_with_value UNZIPDIR "${UNZIPDIR}"

  local CODENAME="${3}"
  enforce_variable_with_value CODENAME "${CODENAME}"

  file_exists_with_spaces "${DOWNLOADFOLDER}/${CODENAME}"
  if  it_exists_with_spaces "${DOWNLOADFOLDER}${UNZIPDIR}" ; then
  {
    rm -rf "${DOWNLOADFOLDER}${UNZIPDIR}"
    directory_does_not_exist_with_spaces "${DOWNLOADFOLDER}${UNZIPDIR}"
  }
  fi

  ensure tar or "Canceling Install. Could not find tar command to execute unzip"
  ensure awk or "Canceling Install. Could not find awk command to execute unzip"
  ensure pv or "Canceling Install. Could not find pv command to execute unzip"
  ensure du or "Canceling Install. Could not find du command to execute unzip"
  ensure gzip or "Canceling Install. Could not find gzip command to execute unzip"
  ensure gio or "Canceling Install. Could not find gio command to execute unzip"
  ensure update-mime-database or "Canceling Install. Could not find update-mime-database command to execute unzip"
  ensure update-desktop-database or "Canceling Install. Could not find update-desktop-database command to execute unzip"
  ensure touch or "Canceling Install. Could not find touch command to execute unzip"

  # provide error handling , once learned goes here. LEarn under if, once learned here.
  # Start loop while ERROR flag in case needs to try again, based on error
  cd "${DOWNLOADFOLDER}"
  #_try "tar xvzf  \"${DOWNLOADFOLDER}/${CODENAME}.tar.gz\"--directory=${DOWNLOADFOLDER}"
  # GROw bar with tar Progress bar tar REF: https://superuser.com/questions/168749/is-there-a-way-to-see-any-tar-progress-per-file
  # Compress tar cvfj big-files.tar.bz2 folder-with-big-files
  # Compress tar cf - ${DOWNLOADFOLDER}/${CODENAME}.tar.gz --directory=${DOWNLOADFOLDER} -P | pv -s $(du -sb ${DOWNLOADFOLDER}/${CODENAME}.tar.gz | awk '{print $1}') | gzip > big-files.tar.gz
  # Extract tar Progress bar REF: https://coderwall.com/p/l_m2yg/tar-untar-on-osx-linux-with-progress-bars
  # Extract tar sample pv file.tgz | tar xzf - -C target_directory
  # Working simplme tar:  tar xvzf ${DOWNLOADFOLDER}/${CODENAME}.tar.gz --directory=${DOWNLOADFOLDER}
  local -i ret=$?
  Comment "pv \"${DOWNLOADFOLDER}${CODENAME}\"  | tar xzf - -C \"${DOWNLOADFOLDER}${UNZIPDIR}\""
  pv "${DOWNLOADFOLDER}${CODENAME}"  | tar xzf - -C "${DOWNLOADFOLDER}${UNZIPDIR}"
  ret=$?
  #local msg=$(_try "tar xvzf  \"${DOWNLOADFOLDER}/${CODENAME}.tar.gz\" --directory=${DOWNLOADFOLDER} " )
  #  tar xvzf file.tar.gz
  # Where,
  # x: This option tells tar to extract the files.
  # v: The “v” stands for “verbose.” This option will list all of the files one by one in the archive.
  # z: The z option is very important and tells the tar command to uncompress the file (gzip).
  # f: This options tells tar that you are going to give it a file name to work with.
  local msg
  local folder_date
  if [ $ret -gt 0 ] ; then
  {
    failed "${ret}:${msg}"
    # add error handling knowledge while learning.
  }
  else
  {
    passed Install with Untar Unzip success!
  }
  fi

  # local NEWDIRCODENAME=$(ls -1tr "${DOWNLOADFOLDER}/"  | tail  -1)
  # local FROMUZIPPED="${DOWNLOADFOLDER}/${NEWDIRCODENAME}"
  # directory_exists_with_spaces  "${FROMUZIPPED}"
  # directory_exists_with_spaces "${DOWNLOADFOLDER}/${CODENAME}"

} # end _unzip
_backup_current_target_and_remove_if_exists(){
  # Sample use
  #
  #     _backup_current_target_and_remove_if_exists "${TARGETFOLDER}"
  #     _backup_current_target_and_remove_if_exists "${TARGETFOLDER}"
  #
  local TARGETFOLDER="${1}"
  enforce_variable_with_value TARGETFOLDER "${TARGETFOLDER}"

  if  it_exists_with_spaces "${TARGETFOLDER}/webstorm" ; then
  {
     local folder_date=$(date +"%Y%m%d")
     if  it_exists_with_spaces "${TARGETFOLDER}/webstorm_${folder_date}" ; then
     {
       warning "A backup already exists for today ${ret}:${msg} \n ... adding time"
       folder_date=$(date +"%Y%m%d%H%M")
     }
     fi
     local msg=$(mv "${TARGETFOLDER}/webstorm" "${TARGETFOLDER}/webstorm_${folder_date}")
     local ret=$?
     if [ $ret -gt 0 ] ; then
     {
       warning failed to move backup "${ret}:${msg} \n"
     }
     fi
     directory_exists_with_spaces "${TARGETFOLDER}/webstorm_${folder_date}"
     file_does_not_exist_with_spaces "${TARGETFOLDER}/webstorm"
  }
  fi
} # end _backup_current_target_and_remove_if_exists
_install_to_target(){
  # Sample use
  #
  #     _install_to_target "${TARGETFOLDER}" "${FROM_DOWNLOADEDFOLDER_UNZIPPED}"
  #
  local TARGETFOLDER="${1}"
  Comment enforce_variable_with_value TARGETFOLDER "${TARGETFOLDER}"
  enforce_variable_with_value TARGETFOLDER "${TARGETFOLDER}"

  local FROM_DOWNLOADEDFOLDER_UNZIPPED="${2}"
  Comment enforce_variable_with_value FROM_DOWNLOADEDFOLDER_UNZIPPED "${FROM_DOWNLOADEDFOLDER_UNZIPPED}"
  enforce_variable_with_value FROM_DOWNLOADEDFOLDER_UNZIPPED "${FROM_DOWNLOADEDFOLDER_UNZIPPED}"

  mkdir -p "${TARGETFOLDER}"
  directory_exists_with_spaces "${TARGETFOLDER}"
  directory_exists_with_spaces "${FROM_DOWNLOADEDFOLDER_UNZIPPED}"

  mv "${FROM_DOWNLOADEDFOLDER_UNZIPPED}" "${TARGETFOLDER}/webstorm"
  _err=$?
  if [ $ret -gt 0 ] ; then
   {
     failed to move "${FROM_DOWNLOADEDFOLDER_UNZIPPED}" to "${TARGETFOLDER}/webstorm"  "${ret}:${msg} \n"
   }
   fi
  directory_exists_with_spaces "${TARGETFOLDER}/webstorm"
  directory_exists_with_spaces "${TARGETFOLDER}/webstorm/bin"
} # end _install_to_target
_add_mine_associacions_and_browser_click_to_open (){
  # Sample use
  #
  #     _add_mine_associacions_and_browser_click_to_open "${TARGETFOLDER}" "${LOCALSHAREFOLDER}"  "${LOGGERFOLDER}"
  #     _add_mine_associacions_and_browser_click_to_open "${TARGETFOLDER}" "${USER_HOME}/.local/share" $USER_HOME/_/work"
  #
  local TARGETFOLDER="${1}"
  enforce_variable_with_value TARGETFOLDER "${TARGETFOLDER}"
  local LOCALSHAREFOLDER="${2}"
  enforce_variable_with_value LOCALSHAREFOLDER "${LOCALSHAREFOLDER}"
  local LOGGERFOLDER="${3}"
  enforce_variable_with_value LOGGERFOLDER "${LOGGERFOLDER}"

  mkdir -p "${LOCALSHAREFOLDER}/applications"
  directory_exists_with_spaces "${LOCALSHAREFOLDER}/applications"
  mkdir -p "${LOCALSHAREFOLDER}/mime/packages"
  directory_exists_with_spaces "${LOCALSHAREFOLDER}/mime/packages"
  file_exists_with_spaces "${TARGETFOLDER}/webstorm/bin/webstorm.sh"
  chown $SUDO_USER:$SUDO_USER -R "${TARGETFOLDER}/webstorm"
  # Now Proceed to register REF:  https://gist.github.com/c80609a/752e566093b1489bd3aef0e56ee0426c
  ensure cat or "Failed to use cat command does not exists"
  ensure xdg-mime or "Failed to install run xdg-mime"

   cat << EOF > ${TARGETFOLDER}/webstorm/bin/mine-open.rb
#!/usr/bin/env ruby

# ${TARGETFOLDER}/webstorm/bin/mine-open.rb
# script opens URL in format webstorm://open?file=%{file}:%{line} in WebStorm

require 'uri'

begin
    url = ARGV.first
    u = URI.parse(url)
    # puts u
    q = URI.decode_www_form(u.query)
    # puts q
    h = q.to_h
    # puts h
    file = h['file']
    line = h['line']
    # puts file
    # puts line
    if line
        arg = "#{file}:#{line}"
    else
        arg = "#{file}"
    end
rescue
    arg = ""
end
puts arg
EOF
  file_exists_with_spaces "${TARGETFOLDER}/webstorm/bin/mine-open.rb"
  chown $SUDO_USER:$SUDO_USER -R "${TARGETFOLDER}/webstorm/bin/mine-open.rb"
  chmod +x ${TARGETFOLDER}/webstorm/bin/mine-open.rb


    cat << EOF > ${TARGETFOLDER}/webstorm/bin/mine-open.sh
#!/usr/bin/env bash
#encoding: UTF-8
# ${TARGETFOLDER}/webstorm/bin/mine-open.sh
# script opens URL in format webstorm://open?file=%{file}:%{line} in WebStorm

echo "\${@}"
echo "\${@}" >>  ${LOGGERFOLDER}/requested.log
${TARGETFOLDER}/webstorm/bin/mine-open.rb \${@}
filetoopen=\$(${TARGETFOLDER}/webstorm/bin/mine-open.rb "\${@}")
echo filetoopen "\${filetoopen}"
echo "\${filetoopen}" >>  ${LOGGERFOLDER}/requestedfiletoopen.log
mine "\${filetoopen}"

EOF
  mkdir -p ${LOGGERFOLDER}/
  directory_exists_with_spaces ${LOGGERFOLDER}/
  chown $SUDO_USER:$SUDO_USER ${LOGGERFOLDER}/
  touch ${LOGGERFOLDER}/requestedfiletoopen.log
  file_exists_with_spaces ${LOGGERFOLDER}/requestedfiletoopen.log
  chown $SUDO_USER:$SUDO_USER -R ${LOGGERFOLDER}/requestedfiletoopen.log
  file_exists_with_spaces "${TARGETFOLDER}/webstorm/bin/mine-open.sh"
  chown $SUDO_USER:$SUDO_USER -R "${TARGETFOLDER}/webstorm/bin/mine-open.sh"
  chmod +x ${TARGETFOLDER}/webstorm/bin/mine-open.sh

 cat << EOF > ${LOCALSHAREFOLDER}/mime/packages/application-x-mine.xml
<?xml version="1.0" encoding="UTF-8"?>
<mime-info xmlns="http://www.freedesktop.org/standards/shared-mime-info">
  <mime-type type="application/x-mine">
    <comment>new mime type</comment>
    <glob pattern="*.x-mine;*.rb;*.html;*.html.erb;*.js.erb;*.html.haml;*.js.haml;*.erb;*.haml;*.js"/>
  </mime-type>
</mime-info>
EOF
  file_exists_with_spaces "${LOCALSHAREFOLDER}/mime/packages/application-x-mine.xml"
  chown $SUDO_USER:$SUDO_USER -R "${LOCALSHAREFOLDER}/mime/packages/application-x-mine.xml"




  cat << EOF > ${LOCALSHAREFOLDER}/applications/jetbrains-webstorm.desktop
# ${LOCALSHAREFOLDER}/applications/jetbrains-webstorm.desktop
[Desktop Entry]
Encoding=UTF-8
Version=2019.3.2
Type=Application
Name=WebStorm
Icon=${TARGETFOLDER}/webstorm/bin/webstorm.svg
Exec="${TARGETFOLDER}/webstorm/bin/webstorm.sh" %f
MimeType=application/x-mine;text/x-mine;text/plain;text/x-chdr;text/x-csrc;text/x-c++hdr;text/x-c++src;text/x-java;text/x-dsrc;text/x-pascal;text/x-perl;text/x-python;application/x-php;application/x-httpd-php3;application/x-httpd-php4;application/x-httpd-php5;application/xml;text/html;text/css;text/x-sql;text/x-diff;x-directory/normal;inode/directory;
Comment=The Most Intelligent Ruby and Rails IDE
Categories=Development;IDE;
Terminal=true
StartupWMClass=jetbrains-webstorm
EOF
  file_exists_with_spaces "${LOCALSHAREFOLDER}/applications/jetbrains-webstorm.desktop"
  chown $SUDO_USER:$SUDO_USER -R "${LOCALSHAREFOLDER}/applications/jetbrains-webstorm.desktop"


  cat << EOF > ${LOCALSHAREFOLDER}/applications/mimeinfo.cache
# ${LOCALSHAREFOLDER}/applications/mimeinfo.cache

[MIME Cache]
x-scheme-handler/webstorm=mine-open.desktop;
EOF
  file_exists_with_spaces "${LOCALSHAREFOLDER}/applications/mimeinfo.cache"
  chown $SUDO_USER:$SUDO_USER -R "${LOCALSHAREFOLDER}/applications/mimeinfo.cache"

  cat << EOF > ${LOCALSHAREFOLDER}/applications/mine-open.desktop
# ${LOCALSHAREFOLDER}/applications/mine-open.desktop
[Desktop Entry]
Encoding=UTF-8
Version=1.0
Type=Application
Terminal=true
Exec="${TARGETFOLDER}/webstorm/bin/mine-open.sh" %f
MimeType=application/webstorm;x-scheme-handler/webstorm;
Name=MineOpen
Comment=BetterErrors
EOF
  file_exists_with_spaces "${LOCALSHAREFOLDER}/applications/mine-open.desktop"
  chown $SUDO_USER:$SUDO_USER -R "${LOCALSHAREFOLDER}/applications/mine-open.desktop"

  # xdg-mime default jetbrains-webstorm.desktop text/plain;text/x-chdr;text/x-csrc;text/x-c++hdr;text/x-c++src;text/x-java;text/x-dsrc;text/x-pascal;text/x-perl;text/x-python;application/x-php;application/x-httpd-php3;application/x-httpd-php4;application/x-httpd-php5;application/xml;text/html;text/css;text/x-sql;text/x-diff;x-directory/normal;inode/directory;
  # xdg-mime default mine-open.desktop x-scheme-handler/webstorm
  # msg=$(_try "xdg-mime default mine-open.desktop x-scheme-handler/webstorm" )
  su - "${SUDO_USER}" -c "xdg-mime default mine-open.desktop x-scheme-handler/webstorm"
  su - "${SUDO_USER}" -c "xdg-mime default mine-open.desktop text/webstorm"
  su - "${SUDO_USER}" -c "xdg-mime default mine-open.desktop application/webstorm"
  su - "${SUDO_USER}" -c "xdg-mime default jetbrains-webstorm.desktop x-scheme-handler/x-mine"
  su - "${SUDO_USER}" -c "xdg-mime default jetbrains-webstorm.desktop text/x-mine"
  su - "${SUDO_USER}" -c "xdg-mime default jetbrains-webstorm.desktop application/x-mine"

  #   cat << EOF > $USER_HOME/.config/mimeapps.list
  #   cat << EOF > ${LOCALSHAREFOLDER}/applications/mimeapps.list
  # [Default Applications]
  # x-scheme-handler/webstorm=mine-open.desktop
  # text/webstorm=mine-open.desktop
  # application/webstorm=mine-open.desktop
  # x-scheme-handler/x-mine=jetbrains-webstorm.desktop
  # text/x-mine=jetbrains-webstorm.desktop
  # application/x-mine=jetbrains-webstorm.desktop

  # [Added Associations]
  # x-scheme-handler/webstorm=mine-open.desktop;
  # text/webstorm=mine-open.desktop;
  # application/webstorm=mine-open.desktop;
  # x-scheme-handler/x-mine=jetbrains-webstorm.desktop;
  # text/x-mine=jetbrains-webstorm.desktop;
  # application/x-mine=jetbrains-webstorm.desktop;
  # EOF
  #   file_exists_with_spaces "${LOCALSHAREFOLDER}/applications/mimeapps.list"
  #   file_exists_with_spaces "$USER_HOME/.config/mimeapps.list"
  ln -fs "$USER_HOME/.config/mimeapps.list" "${LOCALSHAREFOLDER}/applications/mimeapps.list"
  softlink_exists_with_spaces "${LOCALSHAREFOLDER}/applications/mimeapps.list>$USER_HOME/.config/mimeapps.list"
  chown $SUDO_USER:$SUDO_USER -R  "${LOCALSHAREFOLDER}/applications/mimeapps.list"

  file_exists_with_spaces "${TARGETFOLDER}/webstorm/bin/mine-open.sh"

  su - "${SUDO_USER}" -c "xdg-mime query default x-scheme-handler/webstorm"
  su - "${SUDO_USER}" -c "xdg-mime query default x-scheme-handler/x-mine"
  su - "${SUDO_USER}" -c "xdg-mime query default text/x-mine"
  su - "${SUDO_USER}" -c "xdg-mime query default application/x-mine"
  su - "${SUDO_USER}" -c "xdg-mime query default text/webstorm"
  su - "${SUDO_USER}" -c "xdg-mime query default application/webstorm"
  msg=$(_try "su - \"${SUDO_USER}\" -c \"xdg-mime query default x-scheme-handler/webstorm\"")
  ret=$?
  if [ $ret -gt 0 ] ; then
  {

    failed "${ret}:${msg} Install with xdg-mime scheme failed!"
  }
  else
  {
    passed Install with xdg-mime scheme success!
  }
  fi
  su - "${SUDO_USER}" -c "update-mime-database \"${LOCALSHAREFOLDER}/mime\""
  su - "${SUDO_USER}" -c "update-desktop-database \"${LOCALSHAREFOLDER}/applications\""
  su - "${SUDO_USER}" -c "touch test12345.rb "
  su - "${SUDO_USER}" -c "gio info test12345.rb  | grep \"standard::content-type\""
  su - "${SUDO_USER}" -c "touch test12345.erb "
  su - "${SUDO_USER}" -c "gio info test12345.erb  | grep \"standard::content-type\""
  su - "${SUDO_USER}" -c "touch test12345.js.erb "
  su - "${SUDO_USER}" -c "gio info test12345.js.erb  | grep \"standard::content-type\""
  su - "${SUDO_USER}" -c "touch test12345.html.erb "
  su - "${SUDO_USER}" -c "gio info test12345.html.erb  | grep \"standard::content-type\""
  su - "${SUDO_USER}" -c "touch test12345.haml "
  su - "${SUDO_USER}" -c "gio info test12345.haml  | grep \"standard::content-type\""
  su - "${SUDO_USER}" -c "touch test12345.html.haml "
  su - "${SUDO_USER}" -c "gio info test12345.html.haml  | grep \"standard::content-type\""
  su - "${SUDO_USER}" -c "touch test12345.js.haml "
  su - "${SUDO_USER}" -c "gio info test12345.js.haml  | grep \"standard::content-type\""

  su - "${SUDO_USER}" -c "gio mime x-scheme-handler/webstorm"
  su - "${SUDO_USER}" -c "gio mime x-scheme-handler/x-mine"
  su - "${SUDO_USER}" -c "gio mime text/x-mine"
  su - "${SUDO_USER}" -c "gio mime application/x-mine"
  su - "${SUDO_USER}" -c "gio mime text/webstorm"
  su - "${SUDO_USER}" -c "gio mime application/webstorm"
  su - "${SUDO_USER}" -c "rm test12345.rb"
  su - "${SUDO_USER}" -c "rm test12345.erb"
  su - "${SUDO_USER}" -c "rm test12345.js.erb"
  su - "${SUDO_USER}" -c "rm test12345.html.erb"
  su - "${SUDO_USER}" -c "rm test12345.haml"
  su - "${SUDO_USER}" -c "rm test12345.js.haml"
  su - "${SUDO_USER}" -c "rm test12345.html.haml"
  echo " "
  echo "HINT: Add this to your config/initializers/better_errors.rb file "
  echo "better_errors.rb
  # ... /path_to_ruby_project/ ... /config/initializers/better_errors.rb

  if defined?(BetterErrors)
    BetterErrors.editor = \"webstorm://open?file=%{file}:%{line}\"
    BetterErrors.editor = \"x-mine://open?file=%{file}:%{line}\"
  end
  "
} # end _add_mine_associacions_and_browser_click_to_open

_darwin__64() {
  verify_is_installed "
    wget
  "
  local -i _err=$?
  local CODENAME=$(_version "mac" "*.*")
  _err=$?
  echo "$0:$LINENO DEBUG: CODENAME:${CODENAME}";
  [ $_err -gt 0 ] &&  echo -e "\n \n  ERROR! $0:$LINENO  _version:$_err  \n \n  " && exit 1
  if [ -z "${CODENAME}" ] || [ ${_err} -gt 0 ] ; then
  {
    return 1  # here one is for error
  }
  fi

  local TARGET_URL="$(echo -en "${CODENAME}" | tail -1)"
  CODENAME="$(basename "${TARGET_URL}" )"
  local VERSION="$(echo -en "${CODENAME}" | sed 's/WebStorm-//g' | sed 's/.dmg//g' )"
  enforce_variable_with_value VERSION "${VERSION}"
  local UNZIPDIR="$(echo -en "${CODENAME}" | sed 's/'"${VERSION}"'//g' | sed 's/.dmg//g'| sed 's/-//g')"
  local APPDIR="$(echo -en "${CODENAME}" | sed 's/'"${VERSION}"'//g' | sed 's/.dmg//g'| sed 's/-//g').app"
  # echo "${CODENAME}";
  # echo "${URL}";
  echo "$0:$LINENO CODENAME: ${CODENAME}"
  enforce_variable_with_value CODENAME "${CODENAME}"
  enforce_variable_with_value TARGET_URL "${TARGET_URL}"
  enforce_variable_with_value HOME "${HOME}"
  echo "$0:$LINENO UNZIPDIR: ${UNZIPDIR}"
  enforce_variable_with_value UNZIPDIR "${UNZIPDIR}"
  echo "$0:$LINENO APPDIR: ${APPDIR}"
  enforce_variable_with_value APPDIR "${APPDIR}"
  local DOWNLOADFOLDER="${HOME}/Downloads"
  enforce_variable_with_value DOWNLOADFOLDER "${DOWNLOADFOLDER}"
  directory_exists_with_spaces "${DOWNLOADFOLDER}"
  # _do_not_downloadtwice
  if it_exists_with_spaces "${DOWNLOADFOLDER}/${CODENAME}" ; then
  {
    file_exists_with_spaces "${DOWNLOADFOLDER}/${CODENAME}"
  }
  else
  {
    cd "${DOWNLOADFOLDER}"
    _download "${TARGET_URL}" "${DOWNLOADFOLDER}"  ${CODENAME}
    file_exists_with_spaces "${DOWNLOADFOLDER}/${CODENAME}"
  }
  fi
  if  it_exists_with_spaces "/Applications/${APPDIR}" ; then
  {
    echo Remove  unzipped "/Applications/${APPDIR}"
    sudo rm -rf  "/Applications/${APPDIR}"
    directory_does_not_exist_with_spaces  "/Applications/${APPDIR}"
  }
  fi
  echo Attaching dmg downloaded
  sudo hdiutil attach "${DOWNLOADFOLDER}/${CODENAME}"
  ls "/Volumes"
  directory_exists_with_spaces "/Volumes/${UNZIPDIR}"
  directory_exists_with_spaces "/Volumes/${UNZIPDIR}/${APPDIR}"
  echo "sudo  cp -R /Volumes/${UNZIPDIR}/${APPDIR} /Applications/"
  sudo  cp -R /Volumes/${UNZIPDIR}/${APPDIR} /Applications/
  ls -d "/Applications/${APPDIR}"
  directory_exists_with_spaces "/Applications/${APPDIR}"
  sudo hdiutil detach "/Volumes/${UNZIPDIR}"
} # end _darwin__64

_ubuntu__64() {
  local -i _err=$?
  local CODENAME=$(_version "linux" "WebStorm-*.*.*.*amd64.deb")
  _err=$?
  echo "DEBUG: CODENAME:${CODENAME}";
  [ $_err -gt 0 ] &&  echo -e "\n \n  ERROR! $0:$LINENO  _version:$_err  \n \n  " && exit 1
  if [ -z "${CODENAME}" ] || [ ${_err} -gt 0 ] ; then
  {
    return 1  # here one is for error
  }
  fi

  # THOUGHT          local CODENAME="WebStorm-4.3.3.24545_amd64.deb"
  local URL="https://download-cf.jetbrains.com/webstorm/${CODENAME}"
  cd $USER_HOME/Downloads/
  _download "${URL}"
  _err=$?
  wait
  if [ ${_err} -gt 0 ] ; then
  {
    return 1  # here one is for error
  }
  fi
  sudo dpkg -i ${CODENAME}
} # end _ubuntu__64

_ubuntu__32() {
  local -i _err=$?
  local CODENAME=$(_version "linux" "WebStorm-*.*.*.*i386.deb")
  _err=$?
  echo "DEBUG: CODENAME:${CODENAME}";
  [ $_err -gt 0 ] &&  echo -e "\n \n  ERROR! $0:$LINENO  _version:$_err  \n \n  " && exit 1
  if [ -z "${CODENAME}" ] || [ ${_err} -gt 0 ] ; then
  {
    return 1  # here one is for error
  }
  fi
  # THOUGHT local CODENAME="WebStorm-4.3.3.24545_i386.deb"
  local URL="https://download-cf.jetbrains.com/webstorm/${CODENAME}"
  cd $USER_HOME/Downloads/
  _download "${URL}"
  _err=$?
  wait
  if [ ${_err} -gt 0 ] ; then
  {
    return 1  # here one is for error
  }
  fi
  sudo dpkg -i ${CODENAME}
} # end _ubuntu__32

_fedora__32() {
  local -i _err=$?
  local CODENAME=$(_version "linux" "WebStorm*.*.*.*.i386.rpm")
  _err=$?
  echo "DEBUG: CODENAME:${CODENAME}";
  [ $_err -gt 0 ] &&  echo -e "\n \n  ERROR! $0:$LINENO  _version:$_err  \n \n  " && exit 1
  if [ -z "${CODENAME}" ] || [ ${_err} -gt 0 ] ; then
  {
    return 1  # here one is for error
  }
  fi
  # THOUGHT                          WebStorm-4.3.3.24545.i386.rpm
  local TARGET_URL="https://download-cf.jetbrains.com/webstorm/${CODENAME}"
  file_exists_with_spaces $USER_HOME/Downloads
  enforce_variable_with_value CODENAME "${CODENAME}"
  enforce_variable_with_value TARGET_URL "${TARGET_URL}"
  enforce_variable_with_value USER_HOME "${USER_HOME}"
  cd $USER_HOME/Downloads
  _download "${TARGET_URL}" $USER_HOME/Downloads  ${CODENAME}
  file_exists_with_spaces "$USER_HOME/Downloads/${CODENAME}"
  ensure tar or "Canceling Install. Could not find tar command to execute unzip"

  # provide error handling , once learned goes here. LEarn under if, once learned here.
  # Start loop while ERROR flag in case needs to try again, based on error
  _try "rpm --import https://download-cf.jetbrains.com/webstorm/RPM-GPG-KEY-scootersoftware"
  local msg=$(_try "rpm -ivh \"$USER_HOME/Downloads/${CODENAME}\"" )
  local -i ret=$?
  if [ $ret -gt 0 ] ; then
  {
    failed "${ret}:${msg}"
    # add error handling knowledge while learning.
  }
  else
  {
    passed Install with RPM success!
  }
  fi
  ensure WebStorm or "Failed to install WebStorm"
  rm -f "$USER_HOME/Downloads/${CODENAME}"
  file_does_not_exist_with_spaces "$USER_HOME/Downloads/${CODENAME}"
} # end _fedora__32

_centos__64() {
  _fedora__64 "${*}"
} # end _centos__64

_fedora_37__64() {
  _fedora__64 "${*}"
} # end _fedora_37__64

_fedora_39__64() {
  _fedora__64 "${*}"
} # end _fedora_39__64

_fedora__64() {
  local -i _err=0
  trap 'pkill wget && exit 0' EXIT
  trap '[[ -z "$FUNCNAME" ]] && echo -e "${RED}ERROR failed ${#FUNCNAME[@]} $BASH_SOURCE:$LINENO \t\t\t  function:$FUNCNAME ${RESET}" && exit 0 || [[ -n "$FUNCNAME" ]] && echo -e "${RED}ERROR failed ${#FUNCNAME[@]} $BASH_SOURCE:$LINENO \t\t\t  function:$FUNCNAME ${RESET}" && return 1 ' ERR
  trap '[[ -z "$FUNCNAME" ]] && exit 0 || [[ -n "$FUNCNAME" ]] && echo -e "${PURPLE}INTERRUPTED ${YELLOW241} ${#FUNCNAME[@]} $BASH_SOURCE:$LINENO \t\t\t function:$FUNCNAME ${RESET}" && return 1 ' INT
  local CODENAME=""
  local found_tar=$(ls -hctr1 "${USER_HOME}"/Downloads/WebStorm*.* | grep WebStorm | grep tar.gz  | tail -1)
  _err=$?
  local TARGET_URL=""
  if [[ -n "${found_tar}" ]] && [ ${_err} -eq 0 ] ; then
  {
    Comment "found a zip to install :$found_tar"
    CODENAME="$(basename "${found_tar}" )"
    DOWNLOADFOLDER="${USER_HOME}/Downloads/"
  }
  else
  {
    Comment "Calling _version to get lastest version from website https://data.services.jetbrains.com/products?platform\=linux "
    CODENAME="$(_version "linux" "*.*")"
    _err=$?
    Comment  "$0:$LINENO DEBUG: CODENAME:„„„${CODENAME}”””";
    if [[ -z "${CODENAME}" ]] ; then
    {
      echo -e "${RED}\nERROR $0:$LINENO  CODENAME is empty function _fedora__64()  \n${RESET}   "
      return 1 # one is for error
    }
    fi
    CODENAME=$(tail -1 <<< "${CODENAME}")
    if [ ${_err} -gt 0 ] ; then
    {
      echo -e "\n \n${RED}ERROR! $0:$LINENO function return error function _fedora__64()  function _version:$_err  \n \n ${RESET}  "
      return 1  # here one is for error
    }
    fi

    TARGET_URL="$(echo "${CODENAME}" | tail -1)"
    CODENAME="$(basename "${TARGET_URL}" )"
    # CODENAME="WebStorm-2024.1.2.tar.gz"
    DOWNLOADFOLDER="$(_find_downloads_folder)"
    _err=$?
    wait
    if [ ${_err} -gt 0 ] ; then
    {
      return 1  # here one is for error
    }
    fi

    Comment enforce_variable_with_value CODENAME "${CODENAME}"
    Comment enforce_variable_with_value TARGET_URL "${TARGET_URL}"
    Comment enforce_variable_with_value HOME "${HOME}"
    Comment enforce_variable_with_value USER_HOME "${USER_HOME}"

    enforce_variable_with_value CODENAME "${CODENAME}"
    enforce_variable_with_value TARGET_URL "${TARGET_URL}"
    enforce_variable_with_value HOME "${HOME}"
    enforce_variable_with_value USER_HOME "${USER_HOME}"

    Comment enforce_variable_with_value DOWNLOADFOLDER "${DOWNLOADFOLDER}"
    enforce_variable_with_value DOWNLOADFOLDER "${DOWNLOADFOLDER}"

    # _remove_if_corrypted_zipfile_folder?
    if it_exists_with_spaces /tmp/corrupted.tar.gzeraseit ; then
    {
      if it_exists_with_spaces "${DOWNLOADFOLDER}/${CODENAME}"; then
      {
        passed Removing Corrupted zip file
        rm "${DOWNLOADFOLDER}/${CODENAME}"
        file_does_not_exist_with_spaces "${DOWNLOADFOLDER}/${CODENAME}"
        rm  /tmp/corrupted.tar.gzeraseit
      }
      fi
    }
    fi
    Comment "_do_not_downloadtwice \"${TARGET_URL}\" \"${DOWNLOADFOLDER}\"  \"${CODENAME}\""
    _do_not_downloadtwice "${TARGET_URL}" "${DOWNLOADFOLDER}"  "${CODENAME}"
    _err=$?
    wait
    if [ ${_err} -gt 0 ] ; then
    {
      return 1  # here one is for error
    }
    fi
  }
  fi
  local UNZIPDIR="$(echo "${CODENAME}" | sed 's/.tar.gz//g' )"
  Comment enforce_variable_with_value UNZIPDIR "${UNZIPDIR}"
  enforce_variable_with_value UNZIPDIR "${UNZIPDIR}"

  local TARGETFOLDER="${USER_HOME}/_/software"
  Comment enforce_variable_with_value TARGETFOLDER "${TARGETFOLDER}"
  enforce_variable_with_value TARGETFOLDER "${TARGETFOLDER}"

  Comment "_unzip \"${DOWNLOADFOLDER}\" \"${UNZIPDIR}\" \"${CODENAME}\""
  if _unzip "${DOWNLOADFOLDER}" "${UNZIPDIR}" "${CODENAME}" ; then
  {
    Comment "unzipping failed. Downloading again"
    rm -rf "${DOWNLOADFOLDER}/${UNZIPDIR}"
  }
  fi
  Comment "_backup_current_target_and_remove_if_exists \"${TARGETFOLDER}\""
  _backup_current_target_and_remove_if_exists "${TARGETFOLDER}"
  _err=$?
  wait
  if [ ${_err} -gt 0 ] ; then
  {
    return 1  # here one is for error
  }
  fi
  Comment "_install_to_target \"${TARGETFOLDER}\" \"${DOWNLOADFOLDER}/${UNZIPDIR}\""
  _install_to_target "${TARGETFOLDER}" "${DOWNLOADFOLDER}/${UNZIPDIR}"
  _err=$?
  wait
  if [ ${_err} -gt 0 ] ; then
  {
    return 1  # here one is for error
  }
  fi

  # _remove_unzipped_folder?
  rm "${DOWNLOADFOLDER}/${UNZIPDIR}"
  _err=$?
  wait
  if [ ${_err} -gt 0 ] ; then
  {
    return 1  # here one is for error
  }
  fi
  directory_does_not_exist_with_spaces "${DOWNLOADFOLDER}/${UNZIPDIR}"

  # _remove_downloaded_file?
  rm "${DOWNLOADFOLDER}/${CODENAME}"
  _err=$?
  wait
  if [ ${_err} -gt 0 ] ; then
  {
    return 1  # here one is for error
  }
  fi
  file_does_not_exist_with_spaces "${DOWNLOADFOLDER}/${CODENAME}"

  Comment "_add_mine_associacions_and_browser_click_to_open \"${TARGETFOLDER}\" \"${USER_HOME}/.local/share\" \"${USER_HOME}/_/work\""
  _add_mine_associacions_and_browser_click_to_open "${TARGETFOLDER}" "${USER_HOME}/.local/share" "${USER_HOME}/_/work"
  Comment "end _fedora__64"

} # end _fedora__64

_mingw__64() {
    local CODENAME=$(_version "win" "WebStorm*.*.*.*.exe")
    # THOUGHT        local CODENAME="WebStorm-4.3.3.24545.exe"
    local URL="https://download-cf.jetbrains.com/webstorm/${CODENAME}"
    cd $HOMEDIR
    cd Downloads
    curl -O $URL
    ${CODENAME}
} # end _mingw__64

_mingw__32() {
    local CODENAME=$(_version "win" "WebStorm*.*.*.*.exe")
    # THOUGHT        local CODENAME="WebStorm-4.3.3.24545.exe"
    local URL="https://download-cf.jetbrains.com/webstorm/${CODENAME}"
    cd $HOMEDIR
    cd Downloads
    curl -O $URL
    ${CODENAME}
} # end





